# coding: utf-8

"""
    cpaas

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class DataForGetTemplateV2Output(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'business_type': 'str',
        'language_code': 'str',
        'language_name': 'str',
        'scene_template_code': 'str',
        'scene_template_name': 'str',
        'template_list': 'list[TemplateListForGetTemplateV2Output]'
    }

    attribute_map = {
        'business_type': 'BusinessType',
        'language_code': 'LanguageCode',
        'language_name': 'LanguageName',
        'scene_template_code': 'SceneTemplateCode',
        'scene_template_name': 'SceneTemplateName',
        'template_list': 'TemplateList'
    }

    def __init__(self, business_type=None, language_code=None, language_name=None, scene_template_code=None, scene_template_name=None, template_list=None, _configuration=None):  # noqa: E501
        """DataForGetTemplateV2Output - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._business_type = None
        self._language_code = None
        self._language_name = None
        self._scene_template_code = None
        self._scene_template_name = None
        self._template_list = None
        self.discriminator = None

        if business_type is not None:
            self.business_type = business_type
        if language_code is not None:
            self.language_code = language_code
        if language_name is not None:
            self.language_name = language_name
        if scene_template_code is not None:
            self.scene_template_code = scene_template_code
        if scene_template_name is not None:
            self.scene_template_name = scene_template_name
        if template_list is not None:
            self.template_list = template_list

    @property
    def business_type(self):
        """Gets the business_type of this DataForGetTemplateV2Output.  # noqa: E501


        :return: The business_type of this DataForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._business_type

    @business_type.setter
    def business_type(self, business_type):
        """Sets the business_type of this DataForGetTemplateV2Output.


        :param business_type: The business_type of this DataForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._business_type = business_type

    @property
    def language_code(self):
        """Gets the language_code of this DataForGetTemplateV2Output.  # noqa: E501


        :return: The language_code of this DataForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._language_code

    @language_code.setter
    def language_code(self, language_code):
        """Sets the language_code of this DataForGetTemplateV2Output.


        :param language_code: The language_code of this DataForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._language_code = language_code

    @property
    def language_name(self):
        """Gets the language_name of this DataForGetTemplateV2Output.  # noqa: E501


        :return: The language_name of this DataForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._language_name

    @language_name.setter
    def language_name(self, language_name):
        """Sets the language_name of this DataForGetTemplateV2Output.


        :param language_name: The language_name of this DataForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._language_name = language_name

    @property
    def scene_template_code(self):
        """Gets the scene_template_code of this DataForGetTemplateV2Output.  # noqa: E501


        :return: The scene_template_code of this DataForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._scene_template_code

    @scene_template_code.setter
    def scene_template_code(self, scene_template_code):
        """Sets the scene_template_code of this DataForGetTemplateV2Output.


        :param scene_template_code: The scene_template_code of this DataForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._scene_template_code = scene_template_code

    @property
    def scene_template_name(self):
        """Gets the scene_template_name of this DataForGetTemplateV2Output.  # noqa: E501


        :return: The scene_template_name of this DataForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._scene_template_name

    @scene_template_name.setter
    def scene_template_name(self, scene_template_name):
        """Sets the scene_template_name of this DataForGetTemplateV2Output.


        :param scene_template_name: The scene_template_name of this DataForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._scene_template_name = scene_template_name

    @property
    def template_list(self):
        """Gets the template_list of this DataForGetTemplateV2Output.  # noqa: E501


        :return: The template_list of this DataForGetTemplateV2Output.  # noqa: E501
        :rtype: list[TemplateListForGetTemplateV2Output]
        """
        return self._template_list

    @template_list.setter
    def template_list(self, template_list):
        """Sets the template_list of this DataForGetTemplateV2Output.


        :param template_list: The template_list of this DataForGetTemplateV2Output.  # noqa: E501
        :type: list[TemplateListForGetTemplateV2Output]
        """

        self._template_list = template_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataForGetTemplateV2Output, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataForGetTemplateV2Output):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DataForGetTemplateV2Output):
            return True

        return self.to_dict() != other.to_dict()
