# coding: utf-8

"""
    cpaas

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class ElementStyleForCreateTemplateV2Input(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'element_type': 'str',
        'expires_time': 'int',
        'has_expires': 'bool',
        'has_security': 'bool',
        'real_content': 'str',
        'resource_code': 'str',
        'resource_name': 'str',
        'resource_url': 'str'
    }

    attribute_map = {
        'element_type': 'ElementType',
        'expires_time': 'ExpiresTime',
        'has_expires': 'HasExpires',
        'has_security': 'HasSecurity',
        'real_content': 'RealContent',
        'resource_code': 'ResourceCode',
        'resource_name': 'ResourceName',
        'resource_url': 'ResourceUrl'
    }

    def __init__(self, element_type=None, expires_time=None, has_expires=None, has_security=None, real_content=None, resource_code=None, resource_name=None, resource_url=None, _configuration=None):  # noqa: E501
        """ElementStyleForCreateTemplateV2Input - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._element_type = None
        self._expires_time = None
        self._has_expires = None
        self._has_security = None
        self._real_content = None
        self._resource_code = None
        self._resource_name = None
        self._resource_url = None
        self.discriminator = None

        if element_type is not None:
            self.element_type = element_type
        if expires_time is not None:
            self.expires_time = expires_time
        if has_expires is not None:
            self.has_expires = has_expires
        if has_security is not None:
            self.has_security = has_security
        if real_content is not None:
            self.real_content = real_content
        if resource_code is not None:
            self.resource_code = resource_code
        if resource_name is not None:
            self.resource_name = resource_name
        if resource_url is not None:
            self.resource_url = resource_url

    @property
    def element_type(self):
        """Gets the element_type of this ElementStyleForCreateTemplateV2Input.  # noqa: E501


        :return: The element_type of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :rtype: str
        """
        return self._element_type

    @element_type.setter
    def element_type(self, element_type):
        """Sets the element_type of this ElementStyleForCreateTemplateV2Input.


        :param element_type: The element_type of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :type: str
        """

        self._element_type = element_type

    @property
    def expires_time(self):
        """Gets the expires_time of this ElementStyleForCreateTemplateV2Input.  # noqa: E501


        :return: The expires_time of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :rtype: int
        """
        return self._expires_time

    @expires_time.setter
    def expires_time(self, expires_time):
        """Sets the expires_time of this ElementStyleForCreateTemplateV2Input.


        :param expires_time: The expires_time of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :type: int
        """

        self._expires_time = expires_time

    @property
    def has_expires(self):
        """Gets the has_expires of this ElementStyleForCreateTemplateV2Input.  # noqa: E501


        :return: The has_expires of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :rtype: bool
        """
        return self._has_expires

    @has_expires.setter
    def has_expires(self, has_expires):
        """Sets the has_expires of this ElementStyleForCreateTemplateV2Input.


        :param has_expires: The has_expires of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :type: bool
        """

        self._has_expires = has_expires

    @property
    def has_security(self):
        """Gets the has_security of this ElementStyleForCreateTemplateV2Input.  # noqa: E501


        :return: The has_security of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :rtype: bool
        """
        return self._has_security

    @has_security.setter
    def has_security(self, has_security):
        """Sets the has_security of this ElementStyleForCreateTemplateV2Input.


        :param has_security: The has_security of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :type: bool
        """

        self._has_security = has_security

    @property
    def real_content(self):
        """Gets the real_content of this ElementStyleForCreateTemplateV2Input.  # noqa: E501


        :return: The real_content of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :rtype: str
        """
        return self._real_content

    @real_content.setter
    def real_content(self, real_content):
        """Sets the real_content of this ElementStyleForCreateTemplateV2Input.


        :param real_content: The real_content of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :type: str
        """

        self._real_content = real_content

    @property
    def resource_code(self):
        """Gets the resource_code of this ElementStyleForCreateTemplateV2Input.  # noqa: E501


        :return: The resource_code of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :rtype: str
        """
        return self._resource_code

    @resource_code.setter
    def resource_code(self, resource_code):
        """Sets the resource_code of this ElementStyleForCreateTemplateV2Input.


        :param resource_code: The resource_code of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :type: str
        """

        self._resource_code = resource_code

    @property
    def resource_name(self):
        """Gets the resource_name of this ElementStyleForCreateTemplateV2Input.  # noqa: E501


        :return: The resource_name of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :rtype: str
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name):
        """Sets the resource_name of this ElementStyleForCreateTemplateV2Input.


        :param resource_name: The resource_name of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :type: str
        """

        self._resource_name = resource_name

    @property
    def resource_url(self):
        """Gets the resource_url of this ElementStyleForCreateTemplateV2Input.  # noqa: E501


        :return: The resource_url of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :rtype: str
        """
        return self._resource_url

    @resource_url.setter
    def resource_url(self, resource_url):
        """Sets the resource_url of this ElementStyleForCreateTemplateV2Input.


        :param resource_url: The resource_url of this ElementStyleForCreateTemplateV2Input.  # noqa: E501
        :type: str
        """

        self._resource_url = resource_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ElementStyleForCreateTemplateV2Input, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ElementStyleForCreateTemplateV2Input):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ElementStyleForCreateTemplateV2Input):
            return True

        return self.to_dict() != other.to_dict()
