# coding: utf-8

"""
    cpaas

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class ExtendAttrsForGetTemplateV2Output(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'coupon_code': 'str',
        'phone_number': 'str',
        'variable': 'str',
        'website_url': 'str',
        'website_url_type': 'str'
    }

    attribute_map = {
        'coupon_code': 'CouponCode',
        'phone_number': 'PhoneNumber',
        'variable': 'Variable',
        'website_url': 'WebsiteUrl',
        'website_url_type': 'WebsiteUrlType'
    }

    def __init__(self, coupon_code=None, phone_number=None, variable=None, website_url=None, website_url_type=None, _configuration=None):  # noqa: E501
        """ExtendAttrsForGetTemplateV2Output - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._coupon_code = None
        self._phone_number = None
        self._variable = None
        self._website_url = None
        self._website_url_type = None
        self.discriminator = None

        if coupon_code is not None:
            self.coupon_code = coupon_code
        if phone_number is not None:
            self.phone_number = phone_number
        if variable is not None:
            self.variable = variable
        if website_url is not None:
            self.website_url = website_url
        if website_url_type is not None:
            self.website_url_type = website_url_type

    @property
    def coupon_code(self):
        """Gets the coupon_code of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501


        :return: The coupon_code of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._coupon_code

    @coupon_code.setter
    def coupon_code(self, coupon_code):
        """Sets the coupon_code of this ExtendAttrsForGetTemplateV2Output.


        :param coupon_code: The coupon_code of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._coupon_code = coupon_code

    @property
    def phone_number(self):
        """Gets the phone_number of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501


        :return: The phone_number of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this ExtendAttrsForGetTemplateV2Output.


        :param phone_number: The phone_number of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._phone_number = phone_number

    @property
    def variable(self):
        """Gets the variable of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501


        :return: The variable of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._variable

    @variable.setter
    def variable(self, variable):
        """Sets the variable of this ExtendAttrsForGetTemplateV2Output.


        :param variable: The variable of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._variable = variable

    @property
    def website_url(self):
        """Gets the website_url of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501


        :return: The website_url of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._website_url

    @website_url.setter
    def website_url(self, website_url):
        """Sets the website_url of this ExtendAttrsForGetTemplateV2Output.


        :param website_url: The website_url of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._website_url = website_url

    @property
    def website_url_type(self):
        """Gets the website_url_type of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501


        :return: The website_url_type of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._website_url_type

    @website_url_type.setter
    def website_url_type(self, website_url_type):
        """Sets the website_url_type of this ExtendAttrsForGetTemplateV2Output.


        :param website_url_type: The website_url_type of this ExtendAttrsForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._website_url_type = website_url_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExtendAttrsForGetTemplateV2Output, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExtendAttrsForGetTemplateV2Output):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ExtendAttrsForGetTemplateV2Output):
            return True

        return self.to_dict() != other.to_dict()
