# coding: utf-8

"""
    cpaas

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class TemplateStatusForListTemplateV2Output(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'audit_status': 'str',
        'reason': 'str',
        'template_type': 'str'
    }

    attribute_map = {
        'audit_status': 'AuditStatus',
        'reason': 'Reason',
        'template_type': 'TemplateType'
    }

    def __init__(self, audit_status=None, reason=None, template_type=None, _configuration=None):  # noqa: E501
        """TemplateStatusForListTemplateV2Output - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._audit_status = None
        self._reason = None
        self._template_type = None
        self.discriminator = None

        if audit_status is not None:
            self.audit_status = audit_status
        if reason is not None:
            self.reason = reason
        if template_type is not None:
            self.template_type = template_type

    @property
    def audit_status(self):
        """Gets the audit_status of this TemplateStatusForListTemplateV2Output.  # noqa: E501


        :return: The audit_status of this TemplateStatusForListTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._audit_status

    @audit_status.setter
    def audit_status(self, audit_status):
        """Sets the audit_status of this TemplateStatusForListTemplateV2Output.


        :param audit_status: The audit_status of this TemplateStatusForListTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._audit_status = audit_status

    @property
    def reason(self):
        """Gets the reason of this TemplateStatusForListTemplateV2Output.  # noqa: E501


        :return: The reason of this TemplateStatusForListTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this TemplateStatusForListTemplateV2Output.


        :param reason: The reason of this TemplateStatusForListTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._reason = reason

    @property
    def template_type(self):
        """Gets the template_type of this TemplateStatusForListTemplateV2Output.  # noqa: E501


        :return: The template_type of this TemplateStatusForListTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._template_type

    @template_type.setter
    def template_type(self, template_type):
        """Sets the template_type of this TemplateStatusForListTemplateV2Output.


        :param template_type: The template_type of this TemplateStatusForListTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._template_type = template_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TemplateStatusForListTemplateV2Output, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TemplateStatusForListTemplateV2Output):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TemplateStatusForListTemplateV2Output):
            return True

        return self.to_dict() != other.to_dict()
