# coding: utf-8

"""
    cpaas

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class TemplateListForGetTemplateV2Output(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'card_button_type': 'list[str]',
        'card_header_type': 'str',
        'carousel_body': 'str',
        'format': 'str',
        'page_dto_list': 'list[PageDTOListForGetTemplateV2Output]',
        'template_type': 'str',
        'variables_dto_list': 'list[VariablesDTOListForGetTemplateV2Output]',
        'whatsapp_catagory': 'str'
    }

    attribute_map = {
        'card_button_type': 'CardButtonType',
        'card_header_type': 'CardHeaderType',
        'carousel_body': 'CarouselBody',
        'format': 'Format',
        'page_dto_list': 'PageDTOList',
        'template_type': 'TemplateType',
        'variables_dto_list': 'VariablesDTOList',
        'whatsapp_catagory': 'WhatsappCatagory'
    }

    def __init__(self, card_button_type=None, card_header_type=None, carousel_body=None, format=None, page_dto_list=None, template_type=None, variables_dto_list=None, whatsapp_catagory=None, _configuration=None):  # noqa: E501
        """TemplateListForGetTemplateV2Output - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._card_button_type = None
        self._card_header_type = None
        self._carousel_body = None
        self._format = None
        self._page_dto_list = None
        self._template_type = None
        self._variables_dto_list = None
        self._whatsapp_catagory = None
        self.discriminator = None

        if card_button_type is not None:
            self.card_button_type = card_button_type
        if card_header_type is not None:
            self.card_header_type = card_header_type
        if carousel_body is not None:
            self.carousel_body = carousel_body
        if format is not None:
            self.format = format
        if page_dto_list is not None:
            self.page_dto_list = page_dto_list
        if template_type is not None:
            self.template_type = template_type
        if variables_dto_list is not None:
            self.variables_dto_list = variables_dto_list
        if whatsapp_catagory is not None:
            self.whatsapp_catagory = whatsapp_catagory

    @property
    def card_button_type(self):
        """Gets the card_button_type of this TemplateListForGetTemplateV2Output.  # noqa: E501


        :return: The card_button_type of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :rtype: list[str]
        """
        return self._card_button_type

    @card_button_type.setter
    def card_button_type(self, card_button_type):
        """Sets the card_button_type of this TemplateListForGetTemplateV2Output.


        :param card_button_type: The card_button_type of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :type: list[str]
        """

        self._card_button_type = card_button_type

    @property
    def card_header_type(self):
        """Gets the card_header_type of this TemplateListForGetTemplateV2Output.  # noqa: E501


        :return: The card_header_type of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._card_header_type

    @card_header_type.setter
    def card_header_type(self, card_header_type):
        """Sets the card_header_type of this TemplateListForGetTemplateV2Output.


        :param card_header_type: The card_header_type of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._card_header_type = card_header_type

    @property
    def carousel_body(self):
        """Gets the carousel_body of this TemplateListForGetTemplateV2Output.  # noqa: E501


        :return: The carousel_body of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._carousel_body

    @carousel_body.setter
    def carousel_body(self, carousel_body):
        """Sets the carousel_body of this TemplateListForGetTemplateV2Output.


        :param carousel_body: The carousel_body of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._carousel_body = carousel_body

    @property
    def format(self):
        """Gets the format of this TemplateListForGetTemplateV2Output.  # noqa: E501


        :return: The format of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this TemplateListForGetTemplateV2Output.


        :param format: The format of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._format = format

    @property
    def page_dto_list(self):
        """Gets the page_dto_list of this TemplateListForGetTemplateV2Output.  # noqa: E501


        :return: The page_dto_list of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :rtype: list[PageDTOListForGetTemplateV2Output]
        """
        return self._page_dto_list

    @page_dto_list.setter
    def page_dto_list(self, page_dto_list):
        """Sets the page_dto_list of this TemplateListForGetTemplateV2Output.


        :param page_dto_list: The page_dto_list of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :type: list[PageDTOListForGetTemplateV2Output]
        """

        self._page_dto_list = page_dto_list

    @property
    def template_type(self):
        """Gets the template_type of this TemplateListForGetTemplateV2Output.  # noqa: E501


        :return: The template_type of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._template_type

    @template_type.setter
    def template_type(self, template_type):
        """Sets the template_type of this TemplateListForGetTemplateV2Output.


        :param template_type: The template_type of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._template_type = template_type

    @property
    def variables_dto_list(self):
        """Gets the variables_dto_list of this TemplateListForGetTemplateV2Output.  # noqa: E501


        :return: The variables_dto_list of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :rtype: list[VariablesDTOListForGetTemplateV2Output]
        """
        return self._variables_dto_list

    @variables_dto_list.setter
    def variables_dto_list(self, variables_dto_list):
        """Sets the variables_dto_list of this TemplateListForGetTemplateV2Output.


        :param variables_dto_list: The variables_dto_list of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :type: list[VariablesDTOListForGetTemplateV2Output]
        """

        self._variables_dto_list = variables_dto_list

    @property
    def whatsapp_catagory(self):
        """Gets the whatsapp_catagory of this TemplateListForGetTemplateV2Output.  # noqa: E501


        :return: The whatsapp_catagory of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :rtype: str
        """
        return self._whatsapp_catagory

    @whatsapp_catagory.setter
    def whatsapp_catagory(self, whatsapp_catagory):
        """Sets the whatsapp_catagory of this TemplateListForGetTemplateV2Output.


        :param whatsapp_catagory: The whatsapp_catagory of this TemplateListForGetTemplateV2Output.  # noqa: E501
        :type: str
        """

        self._whatsapp_catagory = whatsapp_catagory

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TemplateListForGetTemplateV2Output, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TemplateListForGetTemplateV2Output):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TemplateListForGetTemplateV2Output):
            return True

        return self.to_dict() != other.to_dict()
