# coding: utf-8

"""
    privatelink

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class ModifyVpcEndpointZoneConnectionResourceAttributesRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'endpoint_id': 'str',
        'resource_id': 'str',
        'resource_replace_mode': 'str',
        'service_id': 'str',
        'zone_id': 'str'
    }

    attribute_map = {
        'endpoint_id': 'EndpointId',
        'resource_id': 'ResourceId',
        'resource_replace_mode': 'ResourceReplaceMode',
        'service_id': 'ServiceId',
        'zone_id': 'ZoneId'
    }

    def __init__(self, endpoint_id=None, resource_id=None, resource_replace_mode=None, service_id=None, zone_id=None, _configuration=None):  # noqa: E501
        """ModifyVpcEndpointZoneConnectionResourceAttributesRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._endpoint_id = None
        self._resource_id = None
        self._resource_replace_mode = None
        self._service_id = None
        self._zone_id = None
        self.discriminator = None

        self.endpoint_id = endpoint_id
        self.resource_id = resource_id
        self.resource_replace_mode = resource_replace_mode
        self.service_id = service_id
        self.zone_id = zone_id

    @property
    def endpoint_id(self):
        """Gets the endpoint_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501


        :return: The endpoint_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501
        :rtype: str
        """
        return self._endpoint_id

    @endpoint_id.setter
    def endpoint_id(self, endpoint_id):
        """Sets the endpoint_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.


        :param endpoint_id: The endpoint_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and endpoint_id is None:
            raise ValueError("Invalid value for `endpoint_id`, must not be `None`")  # noqa: E501

        self._endpoint_id = endpoint_id

    @property
    def resource_id(self):
        """Gets the resource_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501


        :return: The resource_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.


        :param resource_id: The resource_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and resource_id is None:
            raise ValueError("Invalid value for `resource_id`, must not be `None`")  # noqa: E501

        self._resource_id = resource_id

    @property
    def resource_replace_mode(self):
        """Gets the resource_replace_mode of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501


        :return: The resource_replace_mode of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501
        :rtype: str
        """
        return self._resource_replace_mode

    @resource_replace_mode.setter
    def resource_replace_mode(self, resource_replace_mode):
        """Sets the resource_replace_mode of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.


        :param resource_replace_mode: The resource_replace_mode of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and resource_replace_mode is None:
            raise ValueError("Invalid value for `resource_replace_mode`, must not be `None`")  # noqa: E501

        self._resource_replace_mode = resource_replace_mode

    @property
    def service_id(self):
        """Gets the service_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501


        :return: The service_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501
        :rtype: str
        """
        return self._service_id

    @service_id.setter
    def service_id(self, service_id):
        """Sets the service_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.


        :param service_id: The service_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and service_id is None:
            raise ValueError("Invalid value for `service_id`, must not be `None`")  # noqa: E501

        self._service_id = service_id

    @property
    def zone_id(self):
        """Gets the zone_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501


        :return: The zone_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501
        :rtype: str
        """
        return self._zone_id

    @zone_id.setter
    def zone_id(self, zone_id):
        """Sets the zone_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.


        :param zone_id: The zone_id of this ModifyVpcEndpointZoneConnectionResourceAttributesRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and zone_id is None:
            raise ValueError("Invalid value for `zone_id`, must not be `None`")  # noqa: E501

        self._zone_id = zone_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModifyVpcEndpointZoneConnectionResourceAttributesRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModifyVpcEndpointZoneConnectionResourceAttributesRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ModifyVpcEndpointZoneConnectionResourceAttributesRequest):
            return True

        return self.to_dict() != other.to_dict()
