# coding: utf-8

# flake8: noqa
"""
    vs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from byteplussdkvs.models.create_voice_task_request import CreateVoiceTaskRequest
from byteplussdkvs.models.create_voice_task_response import CreateVoiceTaskResponse
from byteplussdkvs.models.data_for_create_voice_task_output import DataForCreateVoiceTaskOutput
from byteplussdkvs.models.number_info_list_for_create_voice_task_input import NumberInfoListForCreateVoiceTaskInput
from byteplussdkvs.models.voice_content_for_create_voice_task_input import VoiceContentForCreateVoiceTaskInput
