# coding: utf-8

"""
    vs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class CreateVoiceTaskRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'display_num': 'str',
        'max_hang_up_time': 'int',
        'max_ring_time': 'int',
        'number_info_list': 'NumberInfoListForCreateVoiceTaskInput',
        'repeating_count': 'int',
        'send_time': 'str',
        'service_code': 'str',
        'task_id': 'str',
        'task_name': 'str',
        'time_zone': 'str',
        'voice_content': 'VoiceContentForCreateVoiceTaskInput'
    }

    attribute_map = {
        'display_num': 'DisplayNum',
        'max_hang_up_time': 'MaxHangUpTime',
        'max_ring_time': 'MaxRingTime',
        'number_info_list': 'NumberInfoList',
        'repeating_count': 'RepeatingCount',
        'send_time': 'SendTime',
        'service_code': 'ServiceCode',
        'task_id': 'TaskId',
        'task_name': 'TaskName',
        'time_zone': 'TimeZone',
        'voice_content': 'VoiceContent'
    }

    def __init__(self, display_num=None, max_hang_up_time=None, max_ring_time=None, number_info_list=None, repeating_count=None, send_time=None, service_code=None, task_id=None, task_name=None, time_zone=None, voice_content=None, _configuration=None):  # noqa: E501
        """CreateVoiceTaskRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._display_num = None
        self._max_hang_up_time = None
        self._max_ring_time = None
        self._number_info_list = None
        self._repeating_count = None
        self._send_time = None
        self._service_code = None
        self._task_id = None
        self._task_name = None
        self._time_zone = None
        self._voice_content = None
        self.discriminator = None

        self.display_num = display_num
        if max_hang_up_time is not None:
            self.max_hang_up_time = max_hang_up_time
        if max_ring_time is not None:
            self.max_ring_time = max_ring_time
        if number_info_list is not None:
            self.number_info_list = number_info_list
        if repeating_count is not None:
            self.repeating_count = repeating_count
        if send_time is not None:
            self.send_time = send_time
        self.service_code = service_code
        self.task_id = task_id
        self.task_name = task_name
        if time_zone is not None:
            self.time_zone = time_zone
        if voice_content is not None:
            self.voice_content = voice_content

    @property
    def display_num(self):
        """Gets the display_num of this CreateVoiceTaskRequest.  # noqa: E501


        :return: The display_num of this CreateVoiceTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._display_num

    @display_num.setter
    def display_num(self, display_num):
        """Sets the display_num of this CreateVoiceTaskRequest.


        :param display_num: The display_num of this CreateVoiceTaskRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and display_num is None:
            raise ValueError("Invalid value for `display_num`, must not be `None`")  # noqa: E501

        self._display_num = display_num

    @property
    def max_hang_up_time(self):
        """Gets the max_hang_up_time of this CreateVoiceTaskRequest.  # noqa: E501


        :return: The max_hang_up_time of this CreateVoiceTaskRequest.  # noqa: E501
        :rtype: int
        """
        return self._max_hang_up_time

    @max_hang_up_time.setter
    def max_hang_up_time(self, max_hang_up_time):
        """Sets the max_hang_up_time of this CreateVoiceTaskRequest.


        :param max_hang_up_time: The max_hang_up_time of this CreateVoiceTaskRequest.  # noqa: E501
        :type: int
        """

        self._max_hang_up_time = max_hang_up_time

    @property
    def max_ring_time(self):
        """Gets the max_ring_time of this CreateVoiceTaskRequest.  # noqa: E501


        :return: The max_ring_time of this CreateVoiceTaskRequest.  # noqa: E501
        :rtype: int
        """
        return self._max_ring_time

    @max_ring_time.setter
    def max_ring_time(self, max_ring_time):
        """Sets the max_ring_time of this CreateVoiceTaskRequest.


        :param max_ring_time: The max_ring_time of this CreateVoiceTaskRequest.  # noqa: E501
        :type: int
        """

        self._max_ring_time = max_ring_time

    @property
    def number_info_list(self):
        """Gets the number_info_list of this CreateVoiceTaskRequest.  # noqa: E501


        :return: The number_info_list of this CreateVoiceTaskRequest.  # noqa: E501
        :rtype: NumberInfoListForCreateVoiceTaskInput
        """
        return self._number_info_list

    @number_info_list.setter
    def number_info_list(self, number_info_list):
        """Sets the number_info_list of this CreateVoiceTaskRequest.


        :param number_info_list: The number_info_list of this CreateVoiceTaskRequest.  # noqa: E501
        :type: NumberInfoListForCreateVoiceTaskInput
        """

        self._number_info_list = number_info_list

    @property
    def repeating_count(self):
        """Gets the repeating_count of this CreateVoiceTaskRequest.  # noqa: E501


        :return: The repeating_count of this CreateVoiceTaskRequest.  # noqa: E501
        :rtype: int
        """
        return self._repeating_count

    @repeating_count.setter
    def repeating_count(self, repeating_count):
        """Sets the repeating_count of this CreateVoiceTaskRequest.


        :param repeating_count: The repeating_count of this CreateVoiceTaskRequest.  # noqa: E501
        :type: int
        """

        self._repeating_count = repeating_count

    @property
    def send_time(self):
        """Gets the send_time of this CreateVoiceTaskRequest.  # noqa: E501


        :return: The send_time of this CreateVoiceTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._send_time

    @send_time.setter
    def send_time(self, send_time):
        """Sets the send_time of this CreateVoiceTaskRequest.


        :param send_time: The send_time of this CreateVoiceTaskRequest.  # noqa: E501
        :type: str
        """

        self._send_time = send_time

    @property
    def service_code(self):
        """Gets the service_code of this CreateVoiceTaskRequest.  # noqa: E501


        :return: The service_code of this CreateVoiceTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._service_code

    @service_code.setter
    def service_code(self, service_code):
        """Sets the service_code of this CreateVoiceTaskRequest.


        :param service_code: The service_code of this CreateVoiceTaskRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and service_code is None:
            raise ValueError("Invalid value for `service_code`, must not be `None`")  # noqa: E501

        self._service_code = service_code

    @property
    def task_id(self):
        """Gets the task_id of this CreateVoiceTaskRequest.  # noqa: E501


        :return: The task_id of this CreateVoiceTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this CreateVoiceTaskRequest.


        :param task_id: The task_id of this CreateVoiceTaskRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and task_id is None:
            raise ValueError("Invalid value for `task_id`, must not be `None`")  # noqa: E501

        self._task_id = task_id

    @property
    def task_name(self):
        """Gets the task_name of this CreateVoiceTaskRequest.  # noqa: E501


        :return: The task_name of this CreateVoiceTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_name

    @task_name.setter
    def task_name(self, task_name):
        """Sets the task_name of this CreateVoiceTaskRequest.


        :param task_name: The task_name of this CreateVoiceTaskRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and task_name is None:
            raise ValueError("Invalid value for `task_name`, must not be `None`")  # noqa: E501

        self._task_name = task_name

    @property
    def time_zone(self):
        """Gets the time_zone of this CreateVoiceTaskRequest.  # noqa: E501


        :return: The time_zone of this CreateVoiceTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._time_zone

    @time_zone.setter
    def time_zone(self, time_zone):
        """Sets the time_zone of this CreateVoiceTaskRequest.


        :param time_zone: The time_zone of this CreateVoiceTaskRequest.  # noqa: E501
        :type: str
        """

        self._time_zone = time_zone

    @property
    def voice_content(self):
        """Gets the voice_content of this CreateVoiceTaskRequest.  # noqa: E501


        :return: The voice_content of this CreateVoiceTaskRequest.  # noqa: E501
        :rtype: VoiceContentForCreateVoiceTaskInput
        """
        return self._voice_content

    @voice_content.setter
    def voice_content(self, voice_content):
        """Sets the voice_content of this CreateVoiceTaskRequest.


        :param voice_content: The voice_content of this CreateVoiceTaskRequest.  # noqa: E501
        :type: VoiceContentForCreateVoiceTaskInput
        """

        self._voice_content = voice_content

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateVoiceTaskRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateVoiceTaskRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateVoiceTaskRequest):
            return True

        return self.to_dict() != other.to_dict()
