# coding: utf-8

"""
    vs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class NumberInfoListForCreateVoiceTaskInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'callee_number': 'str',
        'param_obj': 'str'
    }

    attribute_map = {
        'callee_number': 'calleeNumber',
        'param_obj': 'paramObj'
    }

    def __init__(self, callee_number=None, param_obj=None, _configuration=None):  # noqa: E501
        """NumberInfoListForCreateVoiceTaskInput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._callee_number = None
        self._param_obj = None
        self.discriminator = None

        if callee_number is not None:
            self.callee_number = callee_number
        if param_obj is not None:
            self.param_obj = param_obj

    @property
    def callee_number(self):
        """Gets the callee_number of this NumberInfoListForCreateVoiceTaskInput.  # noqa: E501


        :return: The callee_number of this NumberInfoListForCreateVoiceTaskInput.  # noqa: E501
        :rtype: str
        """
        return self._callee_number

    @callee_number.setter
    def callee_number(self, callee_number):
        """Sets the callee_number of this NumberInfoListForCreateVoiceTaskInput.


        :param callee_number: The callee_number of this NumberInfoListForCreateVoiceTaskInput.  # noqa: E501
        :type: str
        """

        self._callee_number = callee_number

    @property
    def param_obj(self):
        """Gets the param_obj of this NumberInfoListForCreateVoiceTaskInput.  # noqa: E501


        :return: The param_obj of this NumberInfoListForCreateVoiceTaskInput.  # noqa: E501
        :rtype: str
        """
        return self._param_obj

    @param_obj.setter
    def param_obj(self, param_obj):
        """Sets the param_obj of this NumberInfoListForCreateVoiceTaskInput.


        :param param_obj: The param_obj of this NumberInfoListForCreateVoiceTaskInput.  # noqa: E501
        :type: str
        """

        self._param_obj = param_obj

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NumberInfoListForCreateVoiceTaskInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NumberInfoListForCreateVoiceTaskInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NumberInfoListForCreateVoiceTaskInput):
            return True

        return self.to_dict() != other.to_dict()
