# coding: utf-8

"""
    vs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class VoiceContentForCreateVoiceTaskInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base_file': 'str',
        'file_name': 'str',
        'source': 'int',
        'text': 'str',
        'tts_language': 'str',
        'tts_speed': 'int',
        'voice_id': 'str'
    }

    attribute_map = {
        'base_file': 'baseFile',
        'file_name': 'fileName',
        'source': 'source',
        'text': 'text',
        'tts_language': 'ttsLanguage',
        'tts_speed': 'ttsSpeed',
        'voice_id': 'voiceId'
    }

    def __init__(self, base_file=None, file_name=None, source=None, text=None, tts_language=None, tts_speed=None, voice_id=None, _configuration=None):  # noqa: E501
        """VoiceContentForCreateVoiceTaskInput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._base_file = None
        self._file_name = None
        self._source = None
        self._text = None
        self._tts_language = None
        self._tts_speed = None
        self._voice_id = None
        self.discriminator = None

        if base_file is not None:
            self.base_file = base_file
        if file_name is not None:
            self.file_name = file_name
        if source is not None:
            self.source = source
        if text is not None:
            self.text = text
        if tts_language is not None:
            self.tts_language = tts_language
        if tts_speed is not None:
            self.tts_speed = tts_speed
        if voice_id is not None:
            self.voice_id = voice_id

    @property
    def base_file(self):
        """Gets the base_file of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501


        :return: The base_file of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :rtype: str
        """
        return self._base_file

    @base_file.setter
    def base_file(self, base_file):
        """Sets the base_file of this VoiceContentForCreateVoiceTaskInput.


        :param base_file: The base_file of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :type: str
        """

        self._base_file = base_file

    @property
    def file_name(self):
        """Gets the file_name of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501


        :return: The file_name of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this VoiceContentForCreateVoiceTaskInput.


        :param file_name: The file_name of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def source(self):
        """Gets the source of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501


        :return: The source of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :rtype: int
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this VoiceContentForCreateVoiceTaskInput.


        :param source: The source of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :type: int
        """

        self._source = source

    @property
    def text(self):
        """Gets the text of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501


        :return: The text of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this VoiceContentForCreateVoiceTaskInput.


        :param text: The text of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def tts_language(self):
        """Gets the tts_language of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501


        :return: The tts_language of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :rtype: str
        """
        return self._tts_language

    @tts_language.setter
    def tts_language(self, tts_language):
        """Sets the tts_language of this VoiceContentForCreateVoiceTaskInput.


        :param tts_language: The tts_language of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :type: str
        """

        self._tts_language = tts_language

    @property
    def tts_speed(self):
        """Gets the tts_speed of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501


        :return: The tts_speed of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :rtype: int
        """
        return self._tts_speed

    @tts_speed.setter
    def tts_speed(self, tts_speed):
        """Sets the tts_speed of this VoiceContentForCreateVoiceTaskInput.


        :param tts_speed: The tts_speed of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :type: int
        """

        self._tts_speed = tts_speed

    @property
    def voice_id(self):
        """Gets the voice_id of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501


        :return: The voice_id of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :rtype: str
        """
        return self._voice_id

    @voice_id.setter
    def voice_id(self, voice_id):
        """Sets the voice_id of this VoiceContentForCreateVoiceTaskInput.


        :param voice_id: The voice_id of this VoiceContentForCreateVoiceTaskInput.  # noqa: E501
        :type: str
        """

        self._voice_id = voice_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VoiceContentForCreateVoiceTaskInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VoiceContentForCreateVoiceTaskInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VoiceContentForCreateVoiceTaskInput):
            return True

        return self.to_dict() != other.to_dict()
