# coding: utf-8

# flake8: noqa

"""
    sts

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from byteplussdksts.api.sts_api import STSApi

# import models into sdk package
from byteplussdksts.models.assume_role_request import AssumeRoleRequest
from byteplussdksts.models.assume_role_response import AssumeRoleResponse
from byteplussdksts.models.assumed_role_user_for_assume_role_output import AssumedRoleUserForAssumeRoleOutput
from byteplussdksts.models.credentials_for_assume_role_output import CredentialsForAssumeRoleOutput
from byteplussdksts.models.get_caller_identity_request import GetCallerIdentityRequest
from byteplussdksts.models.get_caller_identity_response import GetCallerIdentityResponse
from byteplussdksts.models.tag_for_assume_role_input import TagForAssumeRoleInput
