# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class CopyGeniusProjectRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'genius_project_id': 'str',
        'lang': 'str'
    }

    attribute_map = {
        'genius_project_id': 'GeniusProjectId',
        'lang': 'Lang'
    }

    def __init__(self, genius_project_id=None, lang=None, _configuration=None):  # noqa: E501
        """CopyGeniusProjectRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._genius_project_id = None
        self._lang = None
        self.discriminator = None

        if genius_project_id is not None:
            self.genius_project_id = genius_project_id
        if lang is not None:
            self.lang = lang

    @property
    def genius_project_id(self):
        """Gets the genius_project_id of this CopyGeniusProjectRequest.  # noqa: E501


        :return: The genius_project_id of this CopyGeniusProjectRequest.  # noqa: E501
        :rtype: str
        """
        return self._genius_project_id

    @genius_project_id.setter
    def genius_project_id(self, genius_project_id):
        """Sets the genius_project_id of this CopyGeniusProjectRequest.


        :param genius_project_id: The genius_project_id of this CopyGeniusProjectRequest.  # noqa: E501
        :type: str
        """

        self._genius_project_id = genius_project_id

    @property
    def lang(self):
        """Gets the lang of this CopyGeniusProjectRequest.  # noqa: E501


        :return: The lang of this CopyGeniusProjectRequest.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this CopyGeniusProjectRequest.


        :param lang: The lang of this CopyGeniusProjectRequest.  # noqa: E501
        :type: str
        """

        self._lang = lang

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CopyGeniusProjectRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CopyGeniusProjectRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CopyGeniusProjectRequest):
            return True

        return self.to_dict() != other.to_dict()
