# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class CreateMaterialRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aspect_ratio': 'str',
        'category_code': 'str',
        'channel_id': 'str',
        'client_extra_info': 'str',
        'description': 'str',
        'extra': 'str',
        'extra_str': 'str',
        'folder_id': 'str',
        'is_cloud_nle_template': 'bool',
        'is_exclusive': 'bool',
        'lang': 'str',
        'media_extension': 'str',
        'media_first_category': 'str',
        'preview_video': 'str',
        'provider': 'str',
        'provider_attach_info': 'str',
        'provider_media_id': 'str',
        'region': 'str',
        'resource_item': 'str',
        'script_json': 'str',
        'source_from': 'str',
        'store_id': 'str',
        'tags': 'list[str]',
        'team_space_id': 'str',
        'team_visibility': 'bool',
        'template_type': 'str',
        'title': 'str',
        'user_upload_cover': 'bool',
        'user_upload_preview': 'bool'
    }

    attribute_map = {
        'aspect_ratio': 'AspectRatio',
        'category_code': 'CategoryCode',
        'channel_id': 'ChannelId',
        'client_extra_info': 'ClientExtraInfo',
        'description': 'Description',
        'extra': 'Extra',
        'extra_str': 'ExtraStr',
        'folder_id': 'FolderId',
        'is_cloud_nle_template': 'IsCloudNleTemplate',
        'is_exclusive': 'IsExclusive',
        'lang': 'Lang',
        'media_extension': 'MediaExtension',
        'media_first_category': 'MediaFirstCategory',
        'preview_video': 'PreviewVideo',
        'provider': 'Provider',
        'provider_attach_info': 'ProviderAttachInfo',
        'provider_media_id': 'ProviderMediaId',
        'region': 'Region',
        'resource_item': 'ResourceItem',
        'script_json': 'ScriptJson',
        'source_from': 'SourceFrom',
        'store_id': 'StoreId',
        'tags': 'Tags',
        'team_space_id': 'TeamSpaceId',
        'team_visibility': 'TeamVisibility',
        'template_type': 'TemplateType',
        'title': 'Title',
        'user_upload_cover': 'UserUploadCover',
        'user_upload_preview': 'UserUploadPreview'
    }

    def __init__(self, aspect_ratio=None, category_code=None, channel_id=None, client_extra_info=None, description=None, extra=None, extra_str=None, folder_id=None, is_cloud_nle_template=None, is_exclusive=None, lang=None, media_extension=None, media_first_category=None, preview_video=None, provider=None, provider_attach_info=None, provider_media_id=None, region=None, resource_item=None, script_json=None, source_from=None, store_id=None, tags=None, team_space_id=None, team_visibility=None, template_type=None, title=None, user_upload_cover=None, user_upload_preview=None, _configuration=None):  # noqa: E501
        """CreateMaterialRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._aspect_ratio = None
        self._category_code = None
        self._channel_id = None
        self._client_extra_info = None
        self._description = None
        self._extra = None
        self._extra_str = None
        self._folder_id = None
        self._is_cloud_nle_template = None
        self._is_exclusive = None
        self._lang = None
        self._media_extension = None
        self._media_first_category = None
        self._preview_video = None
        self._provider = None
        self._provider_attach_info = None
        self._provider_media_id = None
        self._region = None
        self._resource_item = None
        self._script_json = None
        self._source_from = None
        self._store_id = None
        self._tags = None
        self._team_space_id = None
        self._team_visibility = None
        self._template_type = None
        self._title = None
        self._user_upload_cover = None
        self._user_upload_preview = None
        self.discriminator = None

        if aspect_ratio is not None:
            self.aspect_ratio = aspect_ratio
        if category_code is not None:
            self.category_code = category_code
        if channel_id is not None:
            self.channel_id = channel_id
        if client_extra_info is not None:
            self.client_extra_info = client_extra_info
        if description is not None:
            self.description = description
        if extra is not None:
            self.extra = extra
        if extra_str is not None:
            self.extra_str = extra_str
        if folder_id is not None:
            self.folder_id = folder_id
        if is_cloud_nle_template is not None:
            self.is_cloud_nle_template = is_cloud_nle_template
        if is_exclusive is not None:
            self.is_exclusive = is_exclusive
        if lang is not None:
            self.lang = lang
        if media_extension is not None:
            self.media_extension = media_extension
        if media_first_category is not None:
            self.media_first_category = media_first_category
        if preview_video is not None:
            self.preview_video = preview_video
        if provider is not None:
            self.provider = provider
        if provider_attach_info is not None:
            self.provider_attach_info = provider_attach_info
        if provider_media_id is not None:
            self.provider_media_id = provider_media_id
        if region is not None:
            self.region = region
        if resource_item is not None:
            self.resource_item = resource_item
        if script_json is not None:
            self.script_json = script_json
        if source_from is not None:
            self.source_from = source_from
        if store_id is not None:
            self.store_id = store_id
        if tags is not None:
            self.tags = tags
        if team_space_id is not None:
            self.team_space_id = team_space_id
        if team_visibility is not None:
            self.team_visibility = team_visibility
        if template_type is not None:
            self.template_type = template_type
        if title is not None:
            self.title = title
        if user_upload_cover is not None:
            self.user_upload_cover = user_upload_cover
        if user_upload_preview is not None:
            self.user_upload_preview = user_upload_preview

    @property
    def aspect_ratio(self):
        """Gets the aspect_ratio of this CreateMaterialRequest.  # noqa: E501


        :return: The aspect_ratio of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._aspect_ratio

    @aspect_ratio.setter
    def aspect_ratio(self, aspect_ratio):
        """Sets the aspect_ratio of this CreateMaterialRequest.


        :param aspect_ratio: The aspect_ratio of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._aspect_ratio = aspect_ratio

    @property
    def category_code(self):
        """Gets the category_code of this CreateMaterialRequest.  # noqa: E501


        :return: The category_code of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._category_code

    @category_code.setter
    def category_code(self, category_code):
        """Sets the category_code of this CreateMaterialRequest.


        :param category_code: The category_code of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._category_code = category_code

    @property
    def channel_id(self):
        """Gets the channel_id of this CreateMaterialRequest.  # noqa: E501


        :return: The channel_id of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._channel_id

    @channel_id.setter
    def channel_id(self, channel_id):
        """Sets the channel_id of this CreateMaterialRequest.


        :param channel_id: The channel_id of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._channel_id = channel_id

    @property
    def client_extra_info(self):
        """Gets the client_extra_info of this CreateMaterialRequest.  # noqa: E501


        :return: The client_extra_info of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_extra_info

    @client_extra_info.setter
    def client_extra_info(self, client_extra_info):
        """Sets the client_extra_info of this CreateMaterialRequest.


        :param client_extra_info: The client_extra_info of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._client_extra_info = client_extra_info

    @property
    def description(self):
        """Gets the description of this CreateMaterialRequest.  # noqa: E501


        :return: The description of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateMaterialRequest.


        :param description: The description of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def extra(self):
        """Gets the extra of this CreateMaterialRequest.  # noqa: E501


        :return: The extra of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """Sets the extra of this CreateMaterialRequest.


        :param extra: The extra of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._extra = extra

    @property
    def extra_str(self):
        """Gets the extra_str of this CreateMaterialRequest.  # noqa: E501


        :return: The extra_str of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._extra_str

    @extra_str.setter
    def extra_str(self, extra_str):
        """Sets the extra_str of this CreateMaterialRequest.


        :param extra_str: The extra_str of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._extra_str = extra_str

    @property
    def folder_id(self):
        """Gets the folder_id of this CreateMaterialRequest.  # noqa: E501


        :return: The folder_id of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._folder_id

    @folder_id.setter
    def folder_id(self, folder_id):
        """Sets the folder_id of this CreateMaterialRequest.


        :param folder_id: The folder_id of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._folder_id = folder_id

    @property
    def is_cloud_nle_template(self):
        """Gets the is_cloud_nle_template of this CreateMaterialRequest.  # noqa: E501


        :return: The is_cloud_nle_template of this CreateMaterialRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_cloud_nle_template

    @is_cloud_nle_template.setter
    def is_cloud_nle_template(self, is_cloud_nle_template):
        """Sets the is_cloud_nle_template of this CreateMaterialRequest.


        :param is_cloud_nle_template: The is_cloud_nle_template of this CreateMaterialRequest.  # noqa: E501
        :type: bool
        """

        self._is_cloud_nle_template = is_cloud_nle_template

    @property
    def is_exclusive(self):
        """Gets the is_exclusive of this CreateMaterialRequest.  # noqa: E501


        :return: The is_exclusive of this CreateMaterialRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_exclusive

    @is_exclusive.setter
    def is_exclusive(self, is_exclusive):
        """Sets the is_exclusive of this CreateMaterialRequest.


        :param is_exclusive: The is_exclusive of this CreateMaterialRequest.  # noqa: E501
        :type: bool
        """

        self._is_exclusive = is_exclusive

    @property
    def lang(self):
        """Gets the lang of this CreateMaterialRequest.  # noqa: E501


        :return: The lang of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this CreateMaterialRequest.


        :param lang: The lang of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._lang = lang

    @property
    def media_extension(self):
        """Gets the media_extension of this CreateMaterialRequest.  # noqa: E501


        :return: The media_extension of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._media_extension

    @media_extension.setter
    def media_extension(self, media_extension):
        """Sets the media_extension of this CreateMaterialRequest.


        :param media_extension: The media_extension of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._media_extension = media_extension

    @property
    def media_first_category(self):
        """Gets the media_first_category of this CreateMaterialRequest.  # noqa: E501


        :return: The media_first_category of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._media_first_category

    @media_first_category.setter
    def media_first_category(self, media_first_category):
        """Sets the media_first_category of this CreateMaterialRequest.


        :param media_first_category: The media_first_category of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._media_first_category = media_first_category

    @property
    def preview_video(self):
        """Gets the preview_video of this CreateMaterialRequest.  # noqa: E501


        :return: The preview_video of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._preview_video

    @preview_video.setter
    def preview_video(self, preview_video):
        """Sets the preview_video of this CreateMaterialRequest.


        :param preview_video: The preview_video of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._preview_video = preview_video

    @property
    def provider(self):
        """Gets the provider of this CreateMaterialRequest.  # noqa: E501


        :return: The provider of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this CreateMaterialRequest.


        :param provider: The provider of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._provider = provider

    @property
    def provider_attach_info(self):
        """Gets the provider_attach_info of this CreateMaterialRequest.  # noqa: E501


        :return: The provider_attach_info of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._provider_attach_info

    @provider_attach_info.setter
    def provider_attach_info(self, provider_attach_info):
        """Sets the provider_attach_info of this CreateMaterialRequest.


        :param provider_attach_info: The provider_attach_info of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._provider_attach_info = provider_attach_info

    @property
    def provider_media_id(self):
        """Gets the provider_media_id of this CreateMaterialRequest.  # noqa: E501


        :return: The provider_media_id of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._provider_media_id

    @provider_media_id.setter
    def provider_media_id(self, provider_media_id):
        """Sets the provider_media_id of this CreateMaterialRequest.


        :param provider_media_id: The provider_media_id of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._provider_media_id = provider_media_id

    @property
    def region(self):
        """Gets the region of this CreateMaterialRequest.  # noqa: E501


        :return: The region of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this CreateMaterialRequest.


        :param region: The region of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._region = region

    @property
    def resource_item(self):
        """Gets the resource_item of this CreateMaterialRequest.  # noqa: E501


        :return: The resource_item of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._resource_item

    @resource_item.setter
    def resource_item(self, resource_item):
        """Sets the resource_item of this CreateMaterialRequest.


        :param resource_item: The resource_item of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._resource_item = resource_item

    @property
    def script_json(self):
        """Gets the script_json of this CreateMaterialRequest.  # noqa: E501


        :return: The script_json of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._script_json

    @script_json.setter
    def script_json(self, script_json):
        """Sets the script_json of this CreateMaterialRequest.


        :param script_json: The script_json of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._script_json = script_json

    @property
    def source_from(self):
        """Gets the source_from of this CreateMaterialRequest.  # noqa: E501


        :return: The source_from of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._source_from

    @source_from.setter
    def source_from(self, source_from):
        """Sets the source_from of this CreateMaterialRequest.


        :param source_from: The source_from of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._source_from = source_from

    @property
    def store_id(self):
        """Gets the store_id of this CreateMaterialRequest.  # noqa: E501


        :return: The store_id of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._store_id

    @store_id.setter
    def store_id(self, store_id):
        """Sets the store_id of this CreateMaterialRequest.


        :param store_id: The store_id of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._store_id = store_id

    @property
    def tags(self):
        """Gets the tags of this CreateMaterialRequest.  # noqa: E501


        :return: The tags of this CreateMaterialRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this CreateMaterialRequest.


        :param tags: The tags of this CreateMaterialRequest.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def team_space_id(self):
        """Gets the team_space_id of this CreateMaterialRequest.  # noqa: E501


        :return: The team_space_id of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._team_space_id

    @team_space_id.setter
    def team_space_id(self, team_space_id):
        """Sets the team_space_id of this CreateMaterialRequest.


        :param team_space_id: The team_space_id of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._team_space_id = team_space_id

    @property
    def team_visibility(self):
        """Gets the team_visibility of this CreateMaterialRequest.  # noqa: E501


        :return: The team_visibility of this CreateMaterialRequest.  # noqa: E501
        :rtype: bool
        """
        return self._team_visibility

    @team_visibility.setter
    def team_visibility(self, team_visibility):
        """Sets the team_visibility of this CreateMaterialRequest.


        :param team_visibility: The team_visibility of this CreateMaterialRequest.  # noqa: E501
        :type: bool
        """

        self._team_visibility = team_visibility

    @property
    def template_type(self):
        """Gets the template_type of this CreateMaterialRequest.  # noqa: E501


        :return: The template_type of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._template_type

    @template_type.setter
    def template_type(self, template_type):
        """Sets the template_type of this CreateMaterialRequest.


        :param template_type: The template_type of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._template_type = template_type

    @property
    def title(self):
        """Gets the title of this CreateMaterialRequest.  # noqa: E501


        :return: The title of this CreateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CreateMaterialRequest.


        :param title: The title of this CreateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def user_upload_cover(self):
        """Gets the user_upload_cover of this CreateMaterialRequest.  # noqa: E501


        :return: The user_upload_cover of this CreateMaterialRequest.  # noqa: E501
        :rtype: bool
        """
        return self._user_upload_cover

    @user_upload_cover.setter
    def user_upload_cover(self, user_upload_cover):
        """Sets the user_upload_cover of this CreateMaterialRequest.


        :param user_upload_cover: The user_upload_cover of this CreateMaterialRequest.  # noqa: E501
        :type: bool
        """

        self._user_upload_cover = user_upload_cover

    @property
    def user_upload_preview(self):
        """Gets the user_upload_preview of this CreateMaterialRequest.  # noqa: E501


        :return: The user_upload_preview of this CreateMaterialRequest.  # noqa: E501
        :rtype: bool
        """
        return self._user_upload_preview

    @user_upload_preview.setter
    def user_upload_preview(self, user_upload_preview):
        """Sets the user_upload_preview of this CreateMaterialRequest.


        :param user_upload_preview: The user_upload_preview of this CreateMaterialRequest.  # noqa: E501
        :type: bool
        """

        self._user_upload_preview = user_upload_preview

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateMaterialRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateMaterialRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateMaterialRequest):
            return True

        return self.to_dict() != other.to_dict()
