# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class CreateMediaRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aspect_ratio': 'str',
        'description': 'str',
        'folder_id': 'int',
        'media_extension': 'str',
        'not_save_to_asset': 'bool',
        'resource_item': 'str',
        'resource_type': 'str',
        'tags': 'list[str]',
        'team_space_id': 'int',
        'title': 'str'
    }

    attribute_map = {
        'aspect_ratio': 'AspectRatio',
        'description': 'Description',
        'folder_id': 'FolderId',
        'media_extension': 'MediaExtension',
        'not_save_to_asset': 'NotSaveToAsset',
        'resource_item': 'ResourceItem',
        'resource_type': 'ResourceType',
        'tags': 'Tags',
        'team_space_id': 'TeamSpaceId',
        'title': 'Title'
    }

    def __init__(self, aspect_ratio=None, description=None, folder_id=None, media_extension=None, not_save_to_asset=None, resource_item=None, resource_type=None, tags=None, team_space_id=None, title=None, _configuration=None):  # noqa: E501
        """CreateMediaRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._aspect_ratio = None
        self._description = None
        self._folder_id = None
        self._media_extension = None
        self._not_save_to_asset = None
        self._resource_item = None
        self._resource_type = None
        self._tags = None
        self._team_space_id = None
        self._title = None
        self.discriminator = None

        if aspect_ratio is not None:
            self.aspect_ratio = aspect_ratio
        if description is not None:
            self.description = description
        if folder_id is not None:
            self.folder_id = folder_id
        if media_extension is not None:
            self.media_extension = media_extension
        if not_save_to_asset is not None:
            self.not_save_to_asset = not_save_to_asset
        if resource_item is not None:
            self.resource_item = resource_item
        if resource_type is not None:
            self.resource_type = resource_type
        if tags is not None:
            self.tags = tags
        if team_space_id is not None:
            self.team_space_id = team_space_id
        if title is not None:
            self.title = title

    @property
    def aspect_ratio(self):
        """Gets the aspect_ratio of this CreateMediaRequest.  # noqa: E501


        :return: The aspect_ratio of this CreateMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._aspect_ratio

    @aspect_ratio.setter
    def aspect_ratio(self, aspect_ratio):
        """Sets the aspect_ratio of this CreateMediaRequest.


        :param aspect_ratio: The aspect_ratio of this CreateMediaRequest.  # noqa: E501
        :type: str
        """

        self._aspect_ratio = aspect_ratio

    @property
    def description(self):
        """Gets the description of this CreateMediaRequest.  # noqa: E501


        :return: The description of this CreateMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateMediaRequest.


        :param description: The description of this CreateMediaRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def folder_id(self):
        """Gets the folder_id of this CreateMediaRequest.  # noqa: E501


        :return: The folder_id of this CreateMediaRequest.  # noqa: E501
        :rtype: int
        """
        return self._folder_id

    @folder_id.setter
    def folder_id(self, folder_id):
        """Sets the folder_id of this CreateMediaRequest.


        :param folder_id: The folder_id of this CreateMediaRequest.  # noqa: E501
        :type: int
        """

        self._folder_id = folder_id

    @property
    def media_extension(self):
        """Gets the media_extension of this CreateMediaRequest.  # noqa: E501


        :return: The media_extension of this CreateMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._media_extension

    @media_extension.setter
    def media_extension(self, media_extension):
        """Sets the media_extension of this CreateMediaRequest.


        :param media_extension: The media_extension of this CreateMediaRequest.  # noqa: E501
        :type: str
        """

        self._media_extension = media_extension

    @property
    def not_save_to_asset(self):
        """Gets the not_save_to_asset of this CreateMediaRequest.  # noqa: E501


        :return: The not_save_to_asset of this CreateMediaRequest.  # noqa: E501
        :rtype: bool
        """
        return self._not_save_to_asset

    @not_save_to_asset.setter
    def not_save_to_asset(self, not_save_to_asset):
        """Sets the not_save_to_asset of this CreateMediaRequest.


        :param not_save_to_asset: The not_save_to_asset of this CreateMediaRequest.  # noqa: E501
        :type: bool
        """

        self._not_save_to_asset = not_save_to_asset

    @property
    def resource_item(self):
        """Gets the resource_item of this CreateMediaRequest.  # noqa: E501


        :return: The resource_item of this CreateMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._resource_item

    @resource_item.setter
    def resource_item(self, resource_item):
        """Sets the resource_item of this CreateMediaRequest.


        :param resource_item: The resource_item of this CreateMediaRequest.  # noqa: E501
        :type: str
        """

        self._resource_item = resource_item

    @property
    def resource_type(self):
        """Gets the resource_type of this CreateMediaRequest.  # noqa: E501


        :return: The resource_type of this CreateMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this CreateMediaRequest.


        :param resource_type: The resource_type of this CreateMediaRequest.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def tags(self):
        """Gets the tags of this CreateMediaRequest.  # noqa: E501


        :return: The tags of this CreateMediaRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this CreateMediaRequest.


        :param tags: The tags of this CreateMediaRequest.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def team_space_id(self):
        """Gets the team_space_id of this CreateMediaRequest.  # noqa: E501


        :return: The team_space_id of this CreateMediaRequest.  # noqa: E501
        :rtype: int
        """
        return self._team_space_id

    @team_space_id.setter
    def team_space_id(self, team_space_id):
        """Sets the team_space_id of this CreateMediaRequest.


        :param team_space_id: The team_space_id of this CreateMediaRequest.  # noqa: E501
        :type: int
        """

        self._team_space_id = team_space_id

    @property
    def title(self):
        """Gets the title of this CreateMediaRequest.  # noqa: E501


        :return: The title of this CreateMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CreateMediaRequest.


        :param title: The title of this CreateMediaRequest.  # noqa: E501
        :type: str
        """

        self._title = title

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateMediaRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateMediaRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateMediaRequest):
            return True

        return self.to_dict() != other.to_dict()
