# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class CreateAvatarRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'product_image_id': 'str',
        'reference_image_id': 'str'
    }

    attribute_map = {
        'product_image_id': 'ProductImageId',
        'reference_image_id': 'ReferenceImageId'
    }

    def __init__(self, product_image_id=None, reference_image_id=None, _configuration=None):  # noqa: E501
        """CreateAvatarRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._product_image_id = None
        self._reference_image_id = None
        self.discriminator = None

        if product_image_id is not None:
            self.product_image_id = product_image_id
        if reference_image_id is not None:
            self.reference_image_id = reference_image_id

    @property
    def product_image_id(self):
        """Gets the product_image_id of this CreateAvatarRequest.  # noqa: E501


        :return: The product_image_id of this CreateAvatarRequest.  # noqa: E501
        :rtype: str
        """
        return self._product_image_id

    @product_image_id.setter
    def product_image_id(self, product_image_id):
        """Sets the product_image_id of this CreateAvatarRequest.


        :param product_image_id: The product_image_id of this CreateAvatarRequest.  # noqa: E501
        :type: str
        """

        self._product_image_id = product_image_id

    @property
    def reference_image_id(self):
        """Gets the reference_image_id of this CreateAvatarRequest.  # noqa: E501


        :return: The reference_image_id of this CreateAvatarRequest.  # noqa: E501
        :rtype: str
        """
        return self._reference_image_id

    @reference_image_id.setter
    def reference_image_id(self, reference_image_id):
        """Sets the reference_image_id of this CreateAvatarRequest.


        :param reference_image_id: The reference_image_id of this CreateAvatarRequest.  # noqa: E501
        :type: str
        """

        self._reference_image_id = reference_image_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateAvatarRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateAvatarRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateAvatarRequest):
            return True

        return self.to_dict() != other.to_dict()
