# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class CreateFilmRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aspect_ratio': 'str',
        'category_code': 'str',
        'client_extra_info': 'str',
        'description': 'str',
        'extra': 'str',
        'extra_str': 'str',
        'folder_id': 'int',
        'lang': 'str',
        'media_extension': 'str',
        'media_first_category': 'str',
        'origin_music_id': 'str',
        'panel_id': 'str',
        'params_definition': 'str',
        'preview_video': 'str',
        'provider': 'str',
        'provider_attach_info': 'str',
        'provider_media_id': 'str',
        'region': 'str',
        'resource_item': 'str',
        'source_from': 'str',
        'tags': 'list[str]',
        'team_space_id': 'int',
        'team_visibility': 'bool',
        'title': 'str'
    }

    attribute_map = {
        'aspect_ratio': 'AspectRatio',
        'category_code': 'CategoryCode',
        'client_extra_info': 'ClientExtraInfo',
        'description': 'Description',
        'extra': 'Extra',
        'extra_str': 'ExtraStr',
        'folder_id': 'FolderId',
        'lang': 'Lang',
        'media_extension': 'MediaExtension',
        'media_first_category': 'MediaFirstCategory',
        'origin_music_id': 'OriginMusicId',
        'panel_id': 'PanelId',
        'params_definition': 'ParamsDefinition',
        'preview_video': 'PreviewVideo',
        'provider': 'Provider',
        'provider_attach_info': 'ProviderAttachInfo',
        'provider_media_id': 'ProviderMediaId',
        'region': 'Region',
        'resource_item': 'ResourceItem',
        'source_from': 'SourceFrom',
        'tags': 'Tags',
        'team_space_id': 'TeamSpaceId',
        'team_visibility': 'TeamVisibility',
        'title': 'Title'
    }

    def __init__(self, aspect_ratio=None, category_code=None, client_extra_info=None, description=None, extra=None, extra_str=None, folder_id=None, lang=None, media_extension=None, media_first_category=None, origin_music_id=None, panel_id=None, params_definition=None, preview_video=None, provider=None, provider_attach_info=None, provider_media_id=None, region=None, resource_item=None, source_from=None, tags=None, team_space_id=None, team_visibility=None, title=None, _configuration=None):  # noqa: E501
        """CreateFilmRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._aspect_ratio = None
        self._category_code = None
        self._client_extra_info = None
        self._description = None
        self._extra = None
        self._extra_str = None
        self._folder_id = None
        self._lang = None
        self._media_extension = None
        self._media_first_category = None
        self._origin_music_id = None
        self._panel_id = None
        self._params_definition = None
        self._preview_video = None
        self._provider = None
        self._provider_attach_info = None
        self._provider_media_id = None
        self._region = None
        self._resource_item = None
        self._source_from = None
        self._tags = None
        self._team_space_id = None
        self._team_visibility = None
        self._title = None
        self.discriminator = None

        if aspect_ratio is not None:
            self.aspect_ratio = aspect_ratio
        if category_code is not None:
            self.category_code = category_code
        if client_extra_info is not None:
            self.client_extra_info = client_extra_info
        if description is not None:
            self.description = description
        if extra is not None:
            self.extra = extra
        if extra_str is not None:
            self.extra_str = extra_str
        if folder_id is not None:
            self.folder_id = folder_id
        if lang is not None:
            self.lang = lang
        if media_extension is not None:
            self.media_extension = media_extension
        if media_first_category is not None:
            self.media_first_category = media_first_category
        if origin_music_id is not None:
            self.origin_music_id = origin_music_id
        if panel_id is not None:
            self.panel_id = panel_id
        if params_definition is not None:
            self.params_definition = params_definition
        if preview_video is not None:
            self.preview_video = preview_video
        if provider is not None:
            self.provider = provider
        if provider_attach_info is not None:
            self.provider_attach_info = provider_attach_info
        if provider_media_id is not None:
            self.provider_media_id = provider_media_id
        if region is not None:
            self.region = region
        if resource_item is not None:
            self.resource_item = resource_item
        if source_from is not None:
            self.source_from = source_from
        if tags is not None:
            self.tags = tags
        if team_space_id is not None:
            self.team_space_id = team_space_id
        if team_visibility is not None:
            self.team_visibility = team_visibility
        if title is not None:
            self.title = title

    @property
    def aspect_ratio(self):
        """Gets the aspect_ratio of this CreateFilmRequest.  # noqa: E501


        :return: The aspect_ratio of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._aspect_ratio

    @aspect_ratio.setter
    def aspect_ratio(self, aspect_ratio):
        """Sets the aspect_ratio of this CreateFilmRequest.


        :param aspect_ratio: The aspect_ratio of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._aspect_ratio = aspect_ratio

    @property
    def category_code(self):
        """Gets the category_code of this CreateFilmRequest.  # noqa: E501


        :return: The category_code of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._category_code

    @category_code.setter
    def category_code(self, category_code):
        """Sets the category_code of this CreateFilmRequest.


        :param category_code: The category_code of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._category_code = category_code

    @property
    def client_extra_info(self):
        """Gets the client_extra_info of this CreateFilmRequest.  # noqa: E501


        :return: The client_extra_info of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_extra_info

    @client_extra_info.setter
    def client_extra_info(self, client_extra_info):
        """Sets the client_extra_info of this CreateFilmRequest.


        :param client_extra_info: The client_extra_info of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._client_extra_info = client_extra_info

    @property
    def description(self):
        """Gets the description of this CreateFilmRequest.  # noqa: E501


        :return: The description of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateFilmRequest.


        :param description: The description of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def extra(self):
        """Gets the extra of this CreateFilmRequest.  # noqa: E501


        :return: The extra of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """Sets the extra of this CreateFilmRequest.


        :param extra: The extra of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._extra = extra

    @property
    def extra_str(self):
        """Gets the extra_str of this CreateFilmRequest.  # noqa: E501


        :return: The extra_str of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._extra_str

    @extra_str.setter
    def extra_str(self, extra_str):
        """Sets the extra_str of this CreateFilmRequest.


        :param extra_str: The extra_str of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._extra_str = extra_str

    @property
    def folder_id(self):
        """Gets the folder_id of this CreateFilmRequest.  # noqa: E501


        :return: The folder_id of this CreateFilmRequest.  # noqa: E501
        :rtype: int
        """
        return self._folder_id

    @folder_id.setter
    def folder_id(self, folder_id):
        """Sets the folder_id of this CreateFilmRequest.


        :param folder_id: The folder_id of this CreateFilmRequest.  # noqa: E501
        :type: int
        """

        self._folder_id = folder_id

    @property
    def lang(self):
        """Gets the lang of this CreateFilmRequest.  # noqa: E501


        :return: The lang of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this CreateFilmRequest.


        :param lang: The lang of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._lang = lang

    @property
    def media_extension(self):
        """Gets the media_extension of this CreateFilmRequest.  # noqa: E501


        :return: The media_extension of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._media_extension

    @media_extension.setter
    def media_extension(self, media_extension):
        """Sets the media_extension of this CreateFilmRequest.


        :param media_extension: The media_extension of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._media_extension = media_extension

    @property
    def media_first_category(self):
        """Gets the media_first_category of this CreateFilmRequest.  # noqa: E501


        :return: The media_first_category of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._media_first_category

    @media_first_category.setter
    def media_first_category(self, media_first_category):
        """Sets the media_first_category of this CreateFilmRequest.


        :param media_first_category: The media_first_category of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._media_first_category = media_first_category

    @property
    def origin_music_id(self):
        """Gets the origin_music_id of this CreateFilmRequest.  # noqa: E501


        :return: The origin_music_id of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._origin_music_id

    @origin_music_id.setter
    def origin_music_id(self, origin_music_id):
        """Sets the origin_music_id of this CreateFilmRequest.


        :param origin_music_id: The origin_music_id of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._origin_music_id = origin_music_id

    @property
    def panel_id(self):
        """Gets the panel_id of this CreateFilmRequest.  # noqa: E501


        :return: The panel_id of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._panel_id

    @panel_id.setter
    def panel_id(self, panel_id):
        """Sets the panel_id of this CreateFilmRequest.


        :param panel_id: The panel_id of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._panel_id = panel_id

    @property
    def params_definition(self):
        """Gets the params_definition of this CreateFilmRequest.  # noqa: E501


        :return: The params_definition of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._params_definition

    @params_definition.setter
    def params_definition(self, params_definition):
        """Sets the params_definition of this CreateFilmRequest.


        :param params_definition: The params_definition of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._params_definition = params_definition

    @property
    def preview_video(self):
        """Gets the preview_video of this CreateFilmRequest.  # noqa: E501


        :return: The preview_video of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._preview_video

    @preview_video.setter
    def preview_video(self, preview_video):
        """Sets the preview_video of this CreateFilmRequest.


        :param preview_video: The preview_video of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._preview_video = preview_video

    @property
    def provider(self):
        """Gets the provider of this CreateFilmRequest.  # noqa: E501


        :return: The provider of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this CreateFilmRequest.


        :param provider: The provider of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._provider = provider

    @property
    def provider_attach_info(self):
        """Gets the provider_attach_info of this CreateFilmRequest.  # noqa: E501


        :return: The provider_attach_info of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._provider_attach_info

    @provider_attach_info.setter
    def provider_attach_info(self, provider_attach_info):
        """Sets the provider_attach_info of this CreateFilmRequest.


        :param provider_attach_info: The provider_attach_info of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._provider_attach_info = provider_attach_info

    @property
    def provider_media_id(self):
        """Gets the provider_media_id of this CreateFilmRequest.  # noqa: E501


        :return: The provider_media_id of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._provider_media_id

    @provider_media_id.setter
    def provider_media_id(self, provider_media_id):
        """Sets the provider_media_id of this CreateFilmRequest.


        :param provider_media_id: The provider_media_id of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._provider_media_id = provider_media_id

    @property
    def region(self):
        """Gets the region of this CreateFilmRequest.  # noqa: E501


        :return: The region of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this CreateFilmRequest.


        :param region: The region of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._region = region

    @property
    def resource_item(self):
        """Gets the resource_item of this CreateFilmRequest.  # noqa: E501


        :return: The resource_item of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._resource_item

    @resource_item.setter
    def resource_item(self, resource_item):
        """Sets the resource_item of this CreateFilmRequest.


        :param resource_item: The resource_item of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._resource_item = resource_item

    @property
    def source_from(self):
        """Gets the source_from of this CreateFilmRequest.  # noqa: E501


        :return: The source_from of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._source_from

    @source_from.setter
    def source_from(self, source_from):
        """Sets the source_from of this CreateFilmRequest.


        :param source_from: The source_from of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._source_from = source_from

    @property
    def tags(self):
        """Gets the tags of this CreateFilmRequest.  # noqa: E501


        :return: The tags of this CreateFilmRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this CreateFilmRequest.


        :param tags: The tags of this CreateFilmRequest.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def team_space_id(self):
        """Gets the team_space_id of this CreateFilmRequest.  # noqa: E501


        :return: The team_space_id of this CreateFilmRequest.  # noqa: E501
        :rtype: int
        """
        return self._team_space_id

    @team_space_id.setter
    def team_space_id(self, team_space_id):
        """Sets the team_space_id of this CreateFilmRequest.


        :param team_space_id: The team_space_id of this CreateFilmRequest.  # noqa: E501
        :type: int
        """

        self._team_space_id = team_space_id

    @property
    def team_visibility(self):
        """Gets the team_visibility of this CreateFilmRequest.  # noqa: E501


        :return: The team_visibility of this CreateFilmRequest.  # noqa: E501
        :rtype: bool
        """
        return self._team_visibility

    @team_visibility.setter
    def team_visibility(self, team_visibility):
        """Sets the team_visibility of this CreateFilmRequest.


        :param team_visibility: The team_visibility of this CreateFilmRequest.  # noqa: E501
        :type: bool
        """

        self._team_visibility = team_visibility

    @property
    def title(self):
        """Gets the title of this CreateFilmRequest.  # noqa: E501


        :return: The title of this CreateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CreateFilmRequest.


        :param title: The title of this CreateFilmRequest.  # noqa: E501
        :type: str
        """

        self._title = title

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateFilmRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateFilmRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateFilmRequest):
            return True

        return self.to_dict() != other.to_dict()
