# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class CreateAiTemplateTaskRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'muse_list': 'list[str]',
        'resolution': 'str',
        'server_id': 'str',
        'task_name': 'str',
        'template_id': 'str'
    }

    attribute_map = {
        'muse_list': 'MuseList',
        'resolution': 'Resolution',
        'server_id': 'ServerId',
        'task_name': 'TaskName',
        'template_id': 'TemplateId'
    }

    def __init__(self, muse_list=None, resolution=None, server_id=None, task_name=None, template_id=None, _configuration=None):  # noqa: E501
        """CreateAiTemplateTaskRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._muse_list = None
        self._resolution = None
        self._server_id = None
        self._task_name = None
        self._template_id = None
        self.discriminator = None

        if muse_list is not None:
            self.muse_list = muse_list
        if resolution is not None:
            self.resolution = resolution
        if server_id is not None:
            self.server_id = server_id
        if task_name is not None:
            self.task_name = task_name
        if template_id is not None:
            self.template_id = template_id

    @property
    def muse_list(self):
        """Gets the muse_list of this CreateAiTemplateTaskRequest.  # noqa: E501


        :return: The muse_list of this CreateAiTemplateTaskRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._muse_list

    @muse_list.setter
    def muse_list(self, muse_list):
        """Sets the muse_list of this CreateAiTemplateTaskRequest.


        :param muse_list: The muse_list of this CreateAiTemplateTaskRequest.  # noqa: E501
        :type: list[str]
        """

        self._muse_list = muse_list

    @property
    def resolution(self):
        """Gets the resolution of this CreateAiTemplateTaskRequest.  # noqa: E501


        :return: The resolution of this CreateAiTemplateTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._resolution

    @resolution.setter
    def resolution(self, resolution):
        """Sets the resolution of this CreateAiTemplateTaskRequest.


        :param resolution: The resolution of this CreateAiTemplateTaskRequest.  # noqa: E501
        :type: str
        """

        self._resolution = resolution

    @property
    def server_id(self):
        """Gets the server_id of this CreateAiTemplateTaskRequest.  # noqa: E501


        :return: The server_id of this CreateAiTemplateTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._server_id

    @server_id.setter
    def server_id(self, server_id):
        """Sets the server_id of this CreateAiTemplateTaskRequest.


        :param server_id: The server_id of this CreateAiTemplateTaskRequest.  # noqa: E501
        :type: str
        """

        self._server_id = server_id

    @property
    def task_name(self):
        """Gets the task_name of this CreateAiTemplateTaskRequest.  # noqa: E501


        :return: The task_name of this CreateAiTemplateTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_name

    @task_name.setter
    def task_name(self, task_name):
        """Sets the task_name of this CreateAiTemplateTaskRequest.


        :param task_name: The task_name of this CreateAiTemplateTaskRequest.  # noqa: E501
        :type: str
        """

        self._task_name = task_name

    @property
    def template_id(self):
        """Gets the template_id of this CreateAiTemplateTaskRequest.  # noqa: E501


        :return: The template_id of this CreateAiTemplateTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._template_id

    @template_id.setter
    def template_id(self, template_id):
        """Sets the template_id of this CreateAiTemplateTaskRequest.


        :param template_id: The template_id of this CreateAiTemplateTaskRequest.  # noqa: E501
        :type: str
        """

        self._template_id = template_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateAiTemplateTaskRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateAiTemplateTaskRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateAiTemplateTaskRequest):
            return True

        return self.to_dict() != other.to_dict()
