# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class CreateAuthUrlResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auth_url': 'str',
        'expire_at_ms': 'int',
        'state': 'str'
    }

    attribute_map = {
        'auth_url': 'AuthUrl',
        'expire_at_ms': 'ExpireAtMs',
        'state': 'State'
    }

    def __init__(self, auth_url=None, expire_at_ms=None, state=None, _configuration=None):  # noqa: E501
        """CreateAuthUrlResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._auth_url = None
        self._expire_at_ms = None
        self._state = None
        self.discriminator = None

        if auth_url is not None:
            self.auth_url = auth_url
        if expire_at_ms is not None:
            self.expire_at_ms = expire_at_ms
        if state is not None:
            self.state = state

    @property
    def auth_url(self):
        """Gets the auth_url of this CreateAuthUrlResponse.  # noqa: E501


        :return: The auth_url of this CreateAuthUrlResponse.  # noqa: E501
        :rtype: str
        """
        return self._auth_url

    @auth_url.setter
    def auth_url(self, auth_url):
        """Sets the auth_url of this CreateAuthUrlResponse.


        :param auth_url: The auth_url of this CreateAuthUrlResponse.  # noqa: E501
        :type: str
        """

        self._auth_url = auth_url

    @property
    def expire_at_ms(self):
        """Gets the expire_at_ms of this CreateAuthUrlResponse.  # noqa: E501


        :return: The expire_at_ms of this CreateAuthUrlResponse.  # noqa: E501
        :rtype: int
        """
        return self._expire_at_ms

    @expire_at_ms.setter
    def expire_at_ms(self, expire_at_ms):
        """Sets the expire_at_ms of this CreateAuthUrlResponse.


        :param expire_at_ms: The expire_at_ms of this CreateAuthUrlResponse.  # noqa: E501
        :type: int
        """

        self._expire_at_ms = expire_at_ms

    @property
    def state(self):
        """Gets the state of this CreateAuthUrlResponse.  # noqa: E501


        :return: The state of this CreateAuthUrlResponse.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this CreateAuthUrlResponse.


        :param state: The state of this CreateAuthUrlResponse.  # noqa: E501
        :type: str
        """

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateAuthUrlResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateAuthUrlResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateAuthUrlResponse):
            return True

        return self.to_dict() != other.to_dict()
