# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class CreateItemRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'buy_channel': 'str',
        'combo_start_dt': 'int',
        'enter_from': 'str',
        'id': 'str',
        'is_invited_by_partner': 'int'
    }

    attribute_map = {
        'buy_channel': 'BuyChannel',
        'combo_start_dt': 'ComboStartDt',
        'enter_from': 'EnterFrom',
        'id': 'Id',
        'is_invited_by_partner': 'IsInvitedByPartner'
    }

    def __init__(self, buy_channel=None, combo_start_dt=None, enter_from=None, id=None, is_invited_by_partner=None, _configuration=None):  # noqa: E501
        """CreateItemRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._buy_channel = None
        self._combo_start_dt = None
        self._enter_from = None
        self._id = None
        self._is_invited_by_partner = None
        self.discriminator = None

        if buy_channel is not None:
            self.buy_channel = buy_channel
        if combo_start_dt is not None:
            self.combo_start_dt = combo_start_dt
        if enter_from is not None:
            self.enter_from = enter_from
        if id is not None:
            self.id = id
        if is_invited_by_partner is not None:
            self.is_invited_by_partner = is_invited_by_partner

    @property
    def buy_channel(self):
        """Gets the buy_channel of this CreateItemRequest.  # noqa: E501


        :return: The buy_channel of this CreateItemRequest.  # noqa: E501
        :rtype: str
        """
        return self._buy_channel

    @buy_channel.setter
    def buy_channel(self, buy_channel):
        """Sets the buy_channel of this CreateItemRequest.


        :param buy_channel: The buy_channel of this CreateItemRequest.  # noqa: E501
        :type: str
        """

        self._buy_channel = buy_channel

    @property
    def combo_start_dt(self):
        """Gets the combo_start_dt of this CreateItemRequest.  # noqa: E501


        :return: The combo_start_dt of this CreateItemRequest.  # noqa: E501
        :rtype: int
        """
        return self._combo_start_dt

    @combo_start_dt.setter
    def combo_start_dt(self, combo_start_dt):
        """Sets the combo_start_dt of this CreateItemRequest.


        :param combo_start_dt: The combo_start_dt of this CreateItemRequest.  # noqa: E501
        :type: int
        """

        self._combo_start_dt = combo_start_dt

    @property
    def enter_from(self):
        """Gets the enter_from of this CreateItemRequest.  # noqa: E501


        :return: The enter_from of this CreateItemRequest.  # noqa: E501
        :rtype: str
        """
        return self._enter_from

    @enter_from.setter
    def enter_from(self, enter_from):
        """Sets the enter_from of this CreateItemRequest.


        :param enter_from: The enter_from of this CreateItemRequest.  # noqa: E501
        :type: str
        """

        self._enter_from = enter_from

    @property
    def id(self):
        """Gets the id of this CreateItemRequest.  # noqa: E501


        :return: The id of this CreateItemRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CreateItemRequest.


        :param id: The id of this CreateItemRequest.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def is_invited_by_partner(self):
        """Gets the is_invited_by_partner of this CreateItemRequest.  # noqa: E501


        :return: The is_invited_by_partner of this CreateItemRequest.  # noqa: E501
        :rtype: int
        """
        return self._is_invited_by_partner

    @is_invited_by_partner.setter
    def is_invited_by_partner(self, is_invited_by_partner):
        """Sets the is_invited_by_partner of this CreateItemRequest.


        :param is_invited_by_partner: The is_invited_by_partner of this CreateItemRequest.  # noqa: E501
        :type: int
        """

        self._is_invited_by_partner = is_invited_by_partner

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateItemRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateItemRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateItemRequest):
            return True

        return self.to_dict() != other.to_dict()
