# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class DownloadAssetResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'download_url': 'str',
        'processing_task_id': 'str'
    }

    attribute_map = {
        'download_url': 'DownloadUrl',
        'processing_task_id': 'ProcessingTaskId'
    }

    def __init__(self, download_url=None, processing_task_id=None, _configuration=None):  # noqa: E501
        """DownloadAssetResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._download_url = None
        self._processing_task_id = None
        self.discriminator = None

        if download_url is not None:
            self.download_url = download_url
        if processing_task_id is not None:
            self.processing_task_id = processing_task_id

    @property
    def download_url(self):
        """Gets the download_url of this DownloadAssetResponse.  # noqa: E501


        :return: The download_url of this DownloadAssetResponse.  # noqa: E501
        :rtype: str
        """
        return self._download_url

    @download_url.setter
    def download_url(self, download_url):
        """Sets the download_url of this DownloadAssetResponse.


        :param download_url: The download_url of this DownloadAssetResponse.  # noqa: E501
        :type: str
        """

        self._download_url = download_url

    @property
    def processing_task_id(self):
        """Gets the processing_task_id of this DownloadAssetResponse.  # noqa: E501


        :return: The processing_task_id of this DownloadAssetResponse.  # noqa: E501
        :rtype: str
        """
        return self._processing_task_id

    @processing_task_id.setter
    def processing_task_id(self, processing_task_id):
        """Sets the processing_task_id of this DownloadAssetResponse.


        :param processing_task_id: The processing_task_id of this DownloadAssetResponse.  # noqa: E501
        :type: str
        """

        self._processing_task_id = processing_task_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DownloadAssetResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DownloadAssetResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DownloadAssetResponse):
            return True

        return self.to_dict() != other.to_dict()
