# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class ExportEditorVideoRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'crf': 'int',
        'draft_id': 'str',
        'duration': 'int',
        'fps': 'int',
        'height': 'int',
        'watermark': 'bool',
        'width': 'int'
    }

    attribute_map = {
        'crf': 'Crf',
        'draft_id': 'DraftId',
        'duration': 'Duration',
        'fps': 'Fps',
        'height': 'Height',
        'watermark': 'Watermark',
        'width': 'Width'
    }

    def __init__(self, crf=None, draft_id=None, duration=None, fps=None, height=None, watermark=None, width=None, _configuration=None):  # noqa: E501
        """ExportEditorVideoRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._crf = None
        self._draft_id = None
        self._duration = None
        self._fps = None
        self._height = None
        self._watermark = None
        self._width = None
        self.discriminator = None

        if crf is not None:
            self.crf = crf
        if draft_id is not None:
            self.draft_id = draft_id
        if duration is not None:
            self.duration = duration
        if fps is not None:
            self.fps = fps
        if height is not None:
            self.height = height
        if watermark is not None:
            self.watermark = watermark
        if width is not None:
            self.width = width

    @property
    def crf(self):
        """Gets the crf of this ExportEditorVideoRequest.  # noqa: E501


        :return: The crf of this ExportEditorVideoRequest.  # noqa: E501
        :rtype: int
        """
        return self._crf

    @crf.setter
    def crf(self, crf):
        """Sets the crf of this ExportEditorVideoRequest.


        :param crf: The crf of this ExportEditorVideoRequest.  # noqa: E501
        :type: int
        """

        self._crf = crf

    @property
    def draft_id(self):
        """Gets the draft_id of this ExportEditorVideoRequest.  # noqa: E501


        :return: The draft_id of this ExportEditorVideoRequest.  # noqa: E501
        :rtype: str
        """
        return self._draft_id

    @draft_id.setter
    def draft_id(self, draft_id):
        """Sets the draft_id of this ExportEditorVideoRequest.


        :param draft_id: The draft_id of this ExportEditorVideoRequest.  # noqa: E501
        :type: str
        """

        self._draft_id = draft_id

    @property
    def duration(self):
        """Gets the duration of this ExportEditorVideoRequest.  # noqa: E501


        :return: The duration of this ExportEditorVideoRequest.  # noqa: E501
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this ExportEditorVideoRequest.


        :param duration: The duration of this ExportEditorVideoRequest.  # noqa: E501
        :type: int
        """

        self._duration = duration

    @property
    def fps(self):
        """Gets the fps of this ExportEditorVideoRequest.  # noqa: E501


        :return: The fps of this ExportEditorVideoRequest.  # noqa: E501
        :rtype: int
        """
        return self._fps

    @fps.setter
    def fps(self, fps):
        """Sets the fps of this ExportEditorVideoRequest.


        :param fps: The fps of this ExportEditorVideoRequest.  # noqa: E501
        :type: int
        """

        self._fps = fps

    @property
    def height(self):
        """Gets the height of this ExportEditorVideoRequest.  # noqa: E501


        :return: The height of this ExportEditorVideoRequest.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this ExportEditorVideoRequest.


        :param height: The height of this ExportEditorVideoRequest.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def watermark(self):
        """Gets the watermark of this ExportEditorVideoRequest.  # noqa: E501


        :return: The watermark of this ExportEditorVideoRequest.  # noqa: E501
        :rtype: bool
        """
        return self._watermark

    @watermark.setter
    def watermark(self, watermark):
        """Sets the watermark of this ExportEditorVideoRequest.


        :param watermark: The watermark of this ExportEditorVideoRequest.  # noqa: E501
        :type: bool
        """

        self._watermark = watermark

    @property
    def width(self):
        """Gets the width of this ExportEditorVideoRequest.  # noqa: E501


        :return: The width of this ExportEditorVideoRequest.  # noqa: E501
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this ExportEditorVideoRequest.


        :param width: The width of this ExportEditorVideoRequest.  # noqa: E501
        :type: int
        """

        self._width = width

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExportEditorVideoRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExportEditorVideoRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ExportEditorVideoRequest):
            return True

        return self.to_dict() != other.to_dict()
