# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class GenTemplateScriptRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'block_id': 'str',
        'key': 'str',
        'river_protocol': 'str'
    }

    attribute_map = {
        'block_id': 'BlockId',
        'key': 'Key',
        'river_protocol': 'RiverProtocol'
    }

    def __init__(self, block_id=None, key=None, river_protocol=None, _configuration=None):  # noqa: E501
        """GenTemplateScriptRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._block_id = None
        self._key = None
        self._river_protocol = None
        self.discriminator = None

        if block_id is not None:
            self.block_id = block_id
        if key is not None:
            self.key = key
        if river_protocol is not None:
            self.river_protocol = river_protocol

    @property
    def block_id(self):
        """Gets the block_id of this GenTemplateScriptRequest.  # noqa: E501


        :return: The block_id of this GenTemplateScriptRequest.  # noqa: E501
        :rtype: str
        """
        return self._block_id

    @block_id.setter
    def block_id(self, block_id):
        """Sets the block_id of this GenTemplateScriptRequest.


        :param block_id: The block_id of this GenTemplateScriptRequest.  # noqa: E501
        :type: str
        """

        self._block_id = block_id

    @property
    def key(self):
        """Gets the key of this GenTemplateScriptRequest.  # noqa: E501


        :return: The key of this GenTemplateScriptRequest.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this GenTemplateScriptRequest.


        :param key: The key of this GenTemplateScriptRequest.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def river_protocol(self):
        """Gets the river_protocol of this GenTemplateScriptRequest.  # noqa: E501


        :return: The river_protocol of this GenTemplateScriptRequest.  # noqa: E501
        :rtype: str
        """
        return self._river_protocol

    @river_protocol.setter
    def river_protocol(self, river_protocol):
        """Sets the river_protocol of this GenTemplateScriptRequest.


        :param river_protocol: The river_protocol of this GenTemplateScriptRequest.  # noqa: E501
        :type: str
        """

        self._river_protocol = river_protocol

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenTemplateScriptRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenTemplateScriptRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GenTemplateScriptRequest):
            return True

        return self.to_dict() != other.to_dict()
