# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class GenProductStoryboardVideoResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'new_blocks': 'list[str]',
        'task_id': 'str',
        'update_blocks': 'list[str]'
    }

    attribute_map = {
        'new_blocks': 'NewBlocks',
        'task_id': 'TaskId',
        'update_blocks': 'UpdateBlocks'
    }

    def __init__(self, new_blocks=None, task_id=None, update_blocks=None, _configuration=None):  # noqa: E501
        """GenProductStoryboardVideoResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._new_blocks = None
        self._task_id = None
        self._update_blocks = None
        self.discriminator = None

        if new_blocks is not None:
            self.new_blocks = new_blocks
        if task_id is not None:
            self.task_id = task_id
        if update_blocks is not None:
            self.update_blocks = update_blocks

    @property
    def new_blocks(self):
        """Gets the new_blocks of this GenProductStoryboardVideoResponse.  # noqa: E501


        :return: The new_blocks of this GenProductStoryboardVideoResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._new_blocks

    @new_blocks.setter
    def new_blocks(self, new_blocks):
        """Sets the new_blocks of this GenProductStoryboardVideoResponse.


        :param new_blocks: The new_blocks of this GenProductStoryboardVideoResponse.  # noqa: E501
        :type: list[str]
        """

        self._new_blocks = new_blocks

    @property
    def task_id(self):
        """Gets the task_id of this GenProductStoryboardVideoResponse.  # noqa: E501


        :return: The task_id of this GenProductStoryboardVideoResponse.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this GenProductStoryboardVideoResponse.


        :param task_id: The task_id of this GenProductStoryboardVideoResponse.  # noqa: E501
        :type: str
        """

        self._task_id = task_id

    @property
    def update_blocks(self):
        """Gets the update_blocks of this GenProductStoryboardVideoResponse.  # noqa: E501


        :return: The update_blocks of this GenProductStoryboardVideoResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._update_blocks

    @update_blocks.setter
    def update_blocks(self, update_blocks):
        """Sets the update_blocks of this GenProductStoryboardVideoResponse.


        :param update_blocks: The update_blocks of this GenProductStoryboardVideoResponse.  # noqa: E501
        :type: list[str]
        """

        self._update_blocks = update_blocks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenProductStoryboardVideoResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenProductStoryboardVideoResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GenProductStoryboardVideoResponse):
            return True

        return self.to_dict() != other.to_dict()
