# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class GetMaterialTranscodingListRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field_infos': 'list[str]',
        'must_not_field_infos': 'list[str]',
        'page': 'int',
        'perpage': 'int',
        'should_field_infos': 'list[str]',
        'sort_name': 'str',
        'sort_params': 'list[str]',
        'sort_reg': 'int',
        'user_data': 'int'
    }

    attribute_map = {
        'field_infos': 'FieldInfos',
        'must_not_field_infos': 'MustNotFieldInfos',
        'page': 'Page',
        'perpage': 'Perpage',
        'should_field_infos': 'ShouldFieldInfos',
        'sort_name': 'SortName',
        'sort_params': 'SortParams',
        'sort_reg': 'SortReg',
        'user_data': 'UserData'
    }

    def __init__(self, field_infos=None, must_not_field_infos=None, page=None, perpage=None, should_field_infos=None, sort_name=None, sort_params=None, sort_reg=None, user_data=None, _configuration=None):  # noqa: E501
        """GetMaterialTranscodingListRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._field_infos = None
        self._must_not_field_infos = None
        self._page = None
        self._perpage = None
        self._should_field_infos = None
        self._sort_name = None
        self._sort_params = None
        self._sort_reg = None
        self._user_data = None
        self.discriminator = None

        if field_infos is not None:
            self.field_infos = field_infos
        if must_not_field_infos is not None:
            self.must_not_field_infos = must_not_field_infos
        if page is not None:
            self.page = page
        if perpage is not None:
            self.perpage = perpage
        if should_field_infos is not None:
            self.should_field_infos = should_field_infos
        if sort_name is not None:
            self.sort_name = sort_name
        if sort_params is not None:
            self.sort_params = sort_params
        if sort_reg is not None:
            self.sort_reg = sort_reg
        if user_data is not None:
            self.user_data = user_data

    @property
    def field_infos(self):
        """Gets the field_infos of this GetMaterialTranscodingListRequest.  # noqa: E501


        :return: The field_infos of this GetMaterialTranscodingListRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._field_infos

    @field_infos.setter
    def field_infos(self, field_infos):
        """Sets the field_infos of this GetMaterialTranscodingListRequest.


        :param field_infos: The field_infos of this GetMaterialTranscodingListRequest.  # noqa: E501
        :type: list[str]
        """

        self._field_infos = field_infos

    @property
    def must_not_field_infos(self):
        """Gets the must_not_field_infos of this GetMaterialTranscodingListRequest.  # noqa: E501


        :return: The must_not_field_infos of this GetMaterialTranscodingListRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._must_not_field_infos

    @must_not_field_infos.setter
    def must_not_field_infos(self, must_not_field_infos):
        """Sets the must_not_field_infos of this GetMaterialTranscodingListRequest.


        :param must_not_field_infos: The must_not_field_infos of this GetMaterialTranscodingListRequest.  # noqa: E501
        :type: list[str]
        """

        self._must_not_field_infos = must_not_field_infos

    @property
    def page(self):
        """Gets the page of this GetMaterialTranscodingListRequest.  # noqa: E501


        :return: The page of this GetMaterialTranscodingListRequest.  # noqa: E501
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this GetMaterialTranscodingListRequest.


        :param page: The page of this GetMaterialTranscodingListRequest.  # noqa: E501
        :type: int
        """

        self._page = page

    @property
    def perpage(self):
        """Gets the perpage of this GetMaterialTranscodingListRequest.  # noqa: E501


        :return: The perpage of this GetMaterialTranscodingListRequest.  # noqa: E501
        :rtype: int
        """
        return self._perpage

    @perpage.setter
    def perpage(self, perpage):
        """Sets the perpage of this GetMaterialTranscodingListRequest.


        :param perpage: The perpage of this GetMaterialTranscodingListRequest.  # noqa: E501
        :type: int
        """

        self._perpage = perpage

    @property
    def should_field_infos(self):
        """Gets the should_field_infos of this GetMaterialTranscodingListRequest.  # noqa: E501


        :return: The should_field_infos of this GetMaterialTranscodingListRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._should_field_infos

    @should_field_infos.setter
    def should_field_infos(self, should_field_infos):
        """Sets the should_field_infos of this GetMaterialTranscodingListRequest.


        :param should_field_infos: The should_field_infos of this GetMaterialTranscodingListRequest.  # noqa: E501
        :type: list[str]
        """

        self._should_field_infos = should_field_infos

    @property
    def sort_name(self):
        """Gets the sort_name of this GetMaterialTranscodingListRequest.  # noqa: E501


        :return: The sort_name of this GetMaterialTranscodingListRequest.  # noqa: E501
        :rtype: str
        """
        return self._sort_name

    @sort_name.setter
    def sort_name(self, sort_name):
        """Sets the sort_name of this GetMaterialTranscodingListRequest.


        :param sort_name: The sort_name of this GetMaterialTranscodingListRequest.  # noqa: E501
        :type: str
        """

        self._sort_name = sort_name

    @property
    def sort_params(self):
        """Gets the sort_params of this GetMaterialTranscodingListRequest.  # noqa: E501


        :return: The sort_params of this GetMaterialTranscodingListRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._sort_params

    @sort_params.setter
    def sort_params(self, sort_params):
        """Sets the sort_params of this GetMaterialTranscodingListRequest.


        :param sort_params: The sort_params of this GetMaterialTranscodingListRequest.  # noqa: E501
        :type: list[str]
        """

        self._sort_params = sort_params

    @property
    def sort_reg(self):
        """Gets the sort_reg of this GetMaterialTranscodingListRequest.  # noqa: E501


        :return: The sort_reg of this GetMaterialTranscodingListRequest.  # noqa: E501
        :rtype: int
        """
        return self._sort_reg

    @sort_reg.setter
    def sort_reg(self, sort_reg):
        """Sets the sort_reg of this GetMaterialTranscodingListRequest.


        :param sort_reg: The sort_reg of this GetMaterialTranscodingListRequest.  # noqa: E501
        :type: int
        """

        self._sort_reg = sort_reg

    @property
    def user_data(self):
        """Gets the user_data of this GetMaterialTranscodingListRequest.  # noqa: E501


        :return: The user_data of this GetMaterialTranscodingListRequest.  # noqa: E501
        :rtype: int
        """
        return self._user_data

    @user_data.setter
    def user_data(self, user_data):
        """Sets the user_data of this GetMaterialTranscodingListRequest.


        :param user_data: The user_data of this GetMaterialTranscodingListRequest.  # noqa: E501
        :type: int
        """

        self._user_data = user_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetMaterialTranscodingListRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetMaterialTranscodingListRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetMaterialTranscodingListRequest):
            return True

        return self.to_dict() != other.to_dict()
