# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class GetMaterialTranscodingListResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'medias': 'list[str]',
        'total': 'int'
    }

    attribute_map = {
        'medias': 'Medias',
        'total': 'Total'
    }

    def __init__(self, medias=None, total=None, _configuration=None):  # noqa: E501
        """GetMaterialTranscodingListResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._medias = None
        self._total = None
        self.discriminator = None

        if medias is not None:
            self.medias = medias
        if total is not None:
            self.total = total

    @property
    def medias(self):
        """Gets the medias of this GetMaterialTranscodingListResponse.  # noqa: E501


        :return: The medias of this GetMaterialTranscodingListResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._medias

    @medias.setter
    def medias(self, medias):
        """Sets the medias of this GetMaterialTranscodingListResponse.


        :param medias: The medias of this GetMaterialTranscodingListResponse.  # noqa: E501
        :type: list[str]
        """

        self._medias = medias

    @property
    def total(self):
        """Gets the total of this GetMaterialTranscodingListResponse.  # noqa: E501


        :return: The total of this GetMaterialTranscodingListResponse.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this GetMaterialTranscodingListResponse.


        :param total: The total of this GetMaterialTranscodingListResponse.  # noqa: E501
        :type: int
        """

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetMaterialTranscodingListResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetMaterialTranscodingListResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetMaterialTranscodingListResponse):
            return True

        return self.to_dict() != other.to_dict()
