# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class GetTaskItemResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'int',
        'create_dt': 'int',
        'duration': 'str',
        'expire_dt': 'int',
        'extra': 'str',
        'fail_reason': 'str',
        'id': 'str',
        'name': 'str',
        'progress': 'int',
        'result': 'str',
        'runtime_params': 'str',
        'static_params': 'str',
        'status': 'int',
        'status_desc': 'str',
        'sub_status': 'int',
        'sys_id': 'str',
        'tmpl_id': 'str',
        'update_dt': 'int'
    }

    attribute_map = {
        'code': 'Code',
        'create_dt': 'CreateDt',
        'duration': 'Duration',
        'expire_dt': 'ExpireDt',
        'extra': 'Extra',
        'fail_reason': 'FailReason',
        'id': 'Id',
        'name': 'Name',
        'progress': 'Progress',
        'result': 'Result',
        'runtime_params': 'RuntimeParams',
        'static_params': 'StaticParams',
        'status': 'Status',
        'status_desc': 'StatusDesc',
        'sub_status': 'SubStatus',
        'sys_id': 'SysId',
        'tmpl_id': 'TmplId',
        'update_dt': 'UpdateDt'
    }

    def __init__(self, code=None, create_dt=None, duration=None, expire_dt=None, extra=None, fail_reason=None, id=None, name=None, progress=None, result=None, runtime_params=None, static_params=None, status=None, status_desc=None, sub_status=None, sys_id=None, tmpl_id=None, update_dt=None, _configuration=None):  # noqa: E501
        """GetTaskItemResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._code = None
        self._create_dt = None
        self._duration = None
        self._expire_dt = None
        self._extra = None
        self._fail_reason = None
        self._id = None
        self._name = None
        self._progress = None
        self._result = None
        self._runtime_params = None
        self._static_params = None
        self._status = None
        self._status_desc = None
        self._sub_status = None
        self._sys_id = None
        self._tmpl_id = None
        self._update_dt = None
        self.discriminator = None

        if code is not None:
            self.code = code
        if create_dt is not None:
            self.create_dt = create_dt
        if duration is not None:
            self.duration = duration
        if expire_dt is not None:
            self.expire_dt = expire_dt
        if extra is not None:
            self.extra = extra
        if fail_reason is not None:
            self.fail_reason = fail_reason
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if progress is not None:
            self.progress = progress
        if result is not None:
            self.result = result
        if runtime_params is not None:
            self.runtime_params = runtime_params
        if static_params is not None:
            self.static_params = static_params
        if status is not None:
            self.status = status
        if status_desc is not None:
            self.status_desc = status_desc
        if sub_status is not None:
            self.sub_status = sub_status
        if sys_id is not None:
            self.sys_id = sys_id
        if tmpl_id is not None:
            self.tmpl_id = tmpl_id
        if update_dt is not None:
            self.update_dt = update_dt

    @property
    def code(self):
        """Gets the code of this GetTaskItemResponse.  # noqa: E501


        :return: The code of this GetTaskItemResponse.  # noqa: E501
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this GetTaskItemResponse.


        :param code: The code of this GetTaskItemResponse.  # noqa: E501
        :type: int
        """

        self._code = code

    @property
    def create_dt(self):
        """Gets the create_dt of this GetTaskItemResponse.  # noqa: E501


        :return: The create_dt of this GetTaskItemResponse.  # noqa: E501
        :rtype: int
        """
        return self._create_dt

    @create_dt.setter
    def create_dt(self, create_dt):
        """Sets the create_dt of this GetTaskItemResponse.


        :param create_dt: The create_dt of this GetTaskItemResponse.  # noqa: E501
        :type: int
        """

        self._create_dt = create_dt

    @property
    def duration(self):
        """Gets the duration of this GetTaskItemResponse.  # noqa: E501


        :return: The duration of this GetTaskItemResponse.  # noqa: E501
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this GetTaskItemResponse.


        :param duration: The duration of this GetTaskItemResponse.  # noqa: E501
        :type: str
        """

        self._duration = duration

    @property
    def expire_dt(self):
        """Gets the expire_dt of this GetTaskItemResponse.  # noqa: E501


        :return: The expire_dt of this GetTaskItemResponse.  # noqa: E501
        :rtype: int
        """
        return self._expire_dt

    @expire_dt.setter
    def expire_dt(self, expire_dt):
        """Sets the expire_dt of this GetTaskItemResponse.


        :param expire_dt: The expire_dt of this GetTaskItemResponse.  # noqa: E501
        :type: int
        """

        self._expire_dt = expire_dt

    @property
    def extra(self):
        """Gets the extra of this GetTaskItemResponse.  # noqa: E501


        :return: The extra of this GetTaskItemResponse.  # noqa: E501
        :rtype: str
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """Sets the extra of this GetTaskItemResponse.


        :param extra: The extra of this GetTaskItemResponse.  # noqa: E501
        :type: str
        """

        self._extra = extra

    @property
    def fail_reason(self):
        """Gets the fail_reason of this GetTaskItemResponse.  # noqa: E501


        :return: The fail_reason of this GetTaskItemResponse.  # noqa: E501
        :rtype: str
        """
        return self._fail_reason

    @fail_reason.setter
    def fail_reason(self, fail_reason):
        """Sets the fail_reason of this GetTaskItemResponse.


        :param fail_reason: The fail_reason of this GetTaskItemResponse.  # noqa: E501
        :type: str
        """

        self._fail_reason = fail_reason

    @property
    def id(self):
        """Gets the id of this GetTaskItemResponse.  # noqa: E501


        :return: The id of this GetTaskItemResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetTaskItemResponse.


        :param id: The id of this GetTaskItemResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this GetTaskItemResponse.  # noqa: E501


        :return: The name of this GetTaskItemResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GetTaskItemResponse.


        :param name: The name of this GetTaskItemResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def progress(self):
        """Gets the progress of this GetTaskItemResponse.  # noqa: E501


        :return: The progress of this GetTaskItemResponse.  # noqa: E501
        :rtype: int
        """
        return self._progress

    @progress.setter
    def progress(self, progress):
        """Sets the progress of this GetTaskItemResponse.


        :param progress: The progress of this GetTaskItemResponse.  # noqa: E501
        :type: int
        """

        self._progress = progress

    @property
    def result(self):
        """Gets the result of this GetTaskItemResponse.  # noqa: E501


        :return: The result of this GetTaskItemResponse.  # noqa: E501
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this GetTaskItemResponse.


        :param result: The result of this GetTaskItemResponse.  # noqa: E501
        :type: str
        """

        self._result = result

    @property
    def runtime_params(self):
        """Gets the runtime_params of this GetTaskItemResponse.  # noqa: E501


        :return: The runtime_params of this GetTaskItemResponse.  # noqa: E501
        :rtype: str
        """
        return self._runtime_params

    @runtime_params.setter
    def runtime_params(self, runtime_params):
        """Sets the runtime_params of this GetTaskItemResponse.


        :param runtime_params: The runtime_params of this GetTaskItemResponse.  # noqa: E501
        :type: str
        """

        self._runtime_params = runtime_params

    @property
    def static_params(self):
        """Gets the static_params of this GetTaskItemResponse.  # noqa: E501


        :return: The static_params of this GetTaskItemResponse.  # noqa: E501
        :rtype: str
        """
        return self._static_params

    @static_params.setter
    def static_params(self, static_params):
        """Sets the static_params of this GetTaskItemResponse.


        :param static_params: The static_params of this GetTaskItemResponse.  # noqa: E501
        :type: str
        """

        self._static_params = static_params

    @property
    def status(self):
        """Gets the status of this GetTaskItemResponse.  # noqa: E501


        :return: The status of this GetTaskItemResponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this GetTaskItemResponse.


        :param status: The status of this GetTaskItemResponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def status_desc(self):
        """Gets the status_desc of this GetTaskItemResponse.  # noqa: E501


        :return: The status_desc of this GetTaskItemResponse.  # noqa: E501
        :rtype: str
        """
        return self._status_desc

    @status_desc.setter
    def status_desc(self, status_desc):
        """Sets the status_desc of this GetTaskItemResponse.


        :param status_desc: The status_desc of this GetTaskItemResponse.  # noqa: E501
        :type: str
        """

        self._status_desc = status_desc

    @property
    def sub_status(self):
        """Gets the sub_status of this GetTaskItemResponse.  # noqa: E501


        :return: The sub_status of this GetTaskItemResponse.  # noqa: E501
        :rtype: int
        """
        return self._sub_status

    @sub_status.setter
    def sub_status(self, sub_status):
        """Sets the sub_status of this GetTaskItemResponse.


        :param sub_status: The sub_status of this GetTaskItemResponse.  # noqa: E501
        :type: int
        """

        self._sub_status = sub_status

    @property
    def sys_id(self):
        """Gets the sys_id of this GetTaskItemResponse.  # noqa: E501


        :return: The sys_id of this GetTaskItemResponse.  # noqa: E501
        :rtype: str
        """
        return self._sys_id

    @sys_id.setter
    def sys_id(self, sys_id):
        """Sets the sys_id of this GetTaskItemResponse.


        :param sys_id: The sys_id of this GetTaskItemResponse.  # noqa: E501
        :type: str
        """

        self._sys_id = sys_id

    @property
    def tmpl_id(self):
        """Gets the tmpl_id of this GetTaskItemResponse.  # noqa: E501


        :return: The tmpl_id of this GetTaskItemResponse.  # noqa: E501
        :rtype: str
        """
        return self._tmpl_id

    @tmpl_id.setter
    def tmpl_id(self, tmpl_id):
        """Sets the tmpl_id of this GetTaskItemResponse.


        :param tmpl_id: The tmpl_id of this GetTaskItemResponse.  # noqa: E501
        :type: str
        """

        self._tmpl_id = tmpl_id

    @property
    def update_dt(self):
        """Gets the update_dt of this GetTaskItemResponse.  # noqa: E501


        :return: The update_dt of this GetTaskItemResponse.  # noqa: E501
        :rtype: int
        """
        return self._update_dt

    @update_dt.setter
    def update_dt(self, update_dt):
        """Sets the update_dt of this GetTaskItemResponse.


        :param update_dt: The update_dt of this GetTaskItemResponse.  # noqa: E501
        :type: int
        """

        self._update_dt = update_dt

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetTaskItemResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetTaskItemResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetTaskItemResponse):
            return True

        return self.to_dict() != other.to_dict()
