# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class GetHomeBootstrap2Response(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'combo_status': 'str',
        'has_instance': 'bool',
        'notify_message': 'str',
        'options': 'str',
        'user': 'str',
        'watermark_notified': 'bool'
    }

    attribute_map = {
        'combo_status': 'ComboStatus',
        'has_instance': 'HasInstance',
        'notify_message': 'NotifyMessage',
        'options': 'Options',
        'user': 'User',
        'watermark_notified': 'WatermarkNotified'
    }

    def __init__(self, combo_status=None, has_instance=None, notify_message=None, options=None, user=None, watermark_notified=None, _configuration=None):  # noqa: E501
        """GetHomeBootstrap2Response - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._combo_status = None
        self._has_instance = None
        self._notify_message = None
        self._options = None
        self._user = None
        self._watermark_notified = None
        self.discriminator = None

        if combo_status is not None:
            self.combo_status = combo_status
        if has_instance is not None:
            self.has_instance = has_instance
        if notify_message is not None:
            self.notify_message = notify_message
        if options is not None:
            self.options = options
        if user is not None:
            self.user = user
        if watermark_notified is not None:
            self.watermark_notified = watermark_notified

    @property
    def combo_status(self):
        """Gets the combo_status of this GetHomeBootstrap2Response.  # noqa: E501


        :return: The combo_status of this GetHomeBootstrap2Response.  # noqa: E501
        :rtype: str
        """
        return self._combo_status

    @combo_status.setter
    def combo_status(self, combo_status):
        """Sets the combo_status of this GetHomeBootstrap2Response.


        :param combo_status: The combo_status of this GetHomeBootstrap2Response.  # noqa: E501
        :type: str
        """

        self._combo_status = combo_status

    @property
    def has_instance(self):
        """Gets the has_instance of this GetHomeBootstrap2Response.  # noqa: E501


        :return: The has_instance of this GetHomeBootstrap2Response.  # noqa: E501
        :rtype: bool
        """
        return self._has_instance

    @has_instance.setter
    def has_instance(self, has_instance):
        """Sets the has_instance of this GetHomeBootstrap2Response.


        :param has_instance: The has_instance of this GetHomeBootstrap2Response.  # noqa: E501
        :type: bool
        """

        self._has_instance = has_instance

    @property
    def notify_message(self):
        """Gets the notify_message of this GetHomeBootstrap2Response.  # noqa: E501


        :return: The notify_message of this GetHomeBootstrap2Response.  # noqa: E501
        :rtype: str
        """
        return self._notify_message

    @notify_message.setter
    def notify_message(self, notify_message):
        """Sets the notify_message of this GetHomeBootstrap2Response.


        :param notify_message: The notify_message of this GetHomeBootstrap2Response.  # noqa: E501
        :type: str
        """

        self._notify_message = notify_message

    @property
    def options(self):
        """Gets the options of this GetHomeBootstrap2Response.  # noqa: E501


        :return: The options of this GetHomeBootstrap2Response.  # noqa: E501
        :rtype: str
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this GetHomeBootstrap2Response.


        :param options: The options of this GetHomeBootstrap2Response.  # noqa: E501
        :type: str
        """

        self._options = options

    @property
    def user(self):
        """Gets the user of this GetHomeBootstrap2Response.  # noqa: E501


        :return: The user of this GetHomeBootstrap2Response.  # noqa: E501
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this GetHomeBootstrap2Response.


        :param user: The user of this GetHomeBootstrap2Response.  # noqa: E501
        :type: str
        """

        self._user = user

    @property
    def watermark_notified(self):
        """Gets the watermark_notified of this GetHomeBootstrap2Response.  # noqa: E501


        :return: The watermark_notified of this GetHomeBootstrap2Response.  # noqa: E501
        :rtype: bool
        """
        return self._watermark_notified

    @watermark_notified.setter
    def watermark_notified(self, watermark_notified):
        """Sets the watermark_notified of this GetHomeBootstrap2Response.


        :param watermark_notified: The watermark_notified of this GetHomeBootstrap2Response.  # noqa: E501
        :type: bool
        """

        self._watermark_notified = watermark_notified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetHomeBootstrap2Response, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetHomeBootstrap2Response):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetHomeBootstrap2Response):
            return True

        return self.to_dict() != other.to_dict()
