# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class GetMaterialDetailRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'extra': 'str',
        'fetch_internal_domain': 'bool',
        'media_ids': 'list[str]',
        'need_allocated_user_list': 'bool',
        'user_defined_category_type': 'int'
    }

    attribute_map = {
        'extra': 'Extra',
        'fetch_internal_domain': 'FetchInternalDomain',
        'media_ids': 'MediaIds',
        'need_allocated_user_list': 'NeedAllocatedUserList',
        'user_defined_category_type': 'UserDefinedCategoryType'
    }

    def __init__(self, extra=None, fetch_internal_domain=None, media_ids=None, need_allocated_user_list=None, user_defined_category_type=None, _configuration=None):  # noqa: E501
        """GetMaterialDetailRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._extra = None
        self._fetch_internal_domain = None
        self._media_ids = None
        self._need_allocated_user_list = None
        self._user_defined_category_type = None
        self.discriminator = None

        if extra is not None:
            self.extra = extra
        if fetch_internal_domain is not None:
            self.fetch_internal_domain = fetch_internal_domain
        if media_ids is not None:
            self.media_ids = media_ids
        if need_allocated_user_list is not None:
            self.need_allocated_user_list = need_allocated_user_list
        if user_defined_category_type is not None:
            self.user_defined_category_type = user_defined_category_type

    @property
    def extra(self):
        """Gets the extra of this GetMaterialDetailRequest.  # noqa: E501


        :return: The extra of this GetMaterialDetailRequest.  # noqa: E501
        :rtype: str
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """Sets the extra of this GetMaterialDetailRequest.


        :param extra: The extra of this GetMaterialDetailRequest.  # noqa: E501
        :type: str
        """

        self._extra = extra

    @property
    def fetch_internal_domain(self):
        """Gets the fetch_internal_domain of this GetMaterialDetailRequest.  # noqa: E501


        :return: The fetch_internal_domain of this GetMaterialDetailRequest.  # noqa: E501
        :rtype: bool
        """
        return self._fetch_internal_domain

    @fetch_internal_domain.setter
    def fetch_internal_domain(self, fetch_internal_domain):
        """Sets the fetch_internal_domain of this GetMaterialDetailRequest.


        :param fetch_internal_domain: The fetch_internal_domain of this GetMaterialDetailRequest.  # noqa: E501
        :type: bool
        """

        self._fetch_internal_domain = fetch_internal_domain

    @property
    def media_ids(self):
        """Gets the media_ids of this GetMaterialDetailRequest.  # noqa: E501


        :return: The media_ids of this GetMaterialDetailRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._media_ids

    @media_ids.setter
    def media_ids(self, media_ids):
        """Sets the media_ids of this GetMaterialDetailRequest.


        :param media_ids: The media_ids of this GetMaterialDetailRequest.  # noqa: E501
        :type: list[str]
        """

        self._media_ids = media_ids

    @property
    def need_allocated_user_list(self):
        """Gets the need_allocated_user_list of this GetMaterialDetailRequest.  # noqa: E501


        :return: The need_allocated_user_list of this GetMaterialDetailRequest.  # noqa: E501
        :rtype: bool
        """
        return self._need_allocated_user_list

    @need_allocated_user_list.setter
    def need_allocated_user_list(self, need_allocated_user_list):
        """Sets the need_allocated_user_list of this GetMaterialDetailRequest.


        :param need_allocated_user_list: The need_allocated_user_list of this GetMaterialDetailRequest.  # noqa: E501
        :type: bool
        """

        self._need_allocated_user_list = need_allocated_user_list

    @property
    def user_defined_category_type(self):
        """Gets the user_defined_category_type of this GetMaterialDetailRequest.  # noqa: E501


        :return: The user_defined_category_type of this GetMaterialDetailRequest.  # noqa: E501
        :rtype: int
        """
        return self._user_defined_category_type

    @user_defined_category_type.setter
    def user_defined_category_type(self, user_defined_category_type):
        """Sets the user_defined_category_type of this GetMaterialDetailRequest.


        :param user_defined_category_type: The user_defined_category_type of this GetMaterialDetailRequest.  # noqa: E501
        :type: int
        """

        self._user_defined_category_type = user_defined_category_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetMaterialDetailRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetMaterialDetailRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetMaterialDetailRequest):
            return True

        return self.to_dict() != other.to_dict()
