# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class GetCategoryDetailRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'biz_id': 'str',
        'category_code': 'str',
        'lang': 'str',
        'panel_id': 'str'
    }

    attribute_map = {
        'biz_id': 'BizId',
        'category_code': 'CategoryCode',
        'lang': 'Lang',
        'panel_id': 'PanelId'
    }

    def __init__(self, biz_id=None, category_code=None, lang=None, panel_id=None, _configuration=None):  # noqa: E501
        """GetCategoryDetailRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._biz_id = None
        self._category_code = None
        self._lang = None
        self._panel_id = None
        self.discriminator = None

        if biz_id is not None:
            self.biz_id = biz_id
        if category_code is not None:
            self.category_code = category_code
        if lang is not None:
            self.lang = lang
        if panel_id is not None:
            self.panel_id = panel_id

    @property
    def biz_id(self):
        """Gets the biz_id of this GetCategoryDetailRequest.  # noqa: E501


        :return: The biz_id of this GetCategoryDetailRequest.  # noqa: E501
        :rtype: str
        """
        return self._biz_id

    @biz_id.setter
    def biz_id(self, biz_id):
        """Sets the biz_id of this GetCategoryDetailRequest.


        :param biz_id: The biz_id of this GetCategoryDetailRequest.  # noqa: E501
        :type: str
        """

        self._biz_id = biz_id

    @property
    def category_code(self):
        """Gets the category_code of this GetCategoryDetailRequest.  # noqa: E501


        :return: The category_code of this GetCategoryDetailRequest.  # noqa: E501
        :rtype: str
        """
        return self._category_code

    @category_code.setter
    def category_code(self, category_code):
        """Sets the category_code of this GetCategoryDetailRequest.


        :param category_code: The category_code of this GetCategoryDetailRequest.  # noqa: E501
        :type: str
        """

        self._category_code = category_code

    @property
    def lang(self):
        """Gets the lang of this GetCategoryDetailRequest.  # noqa: E501


        :return: The lang of this GetCategoryDetailRequest.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this GetCategoryDetailRequest.


        :param lang: The lang of this GetCategoryDetailRequest.  # noqa: E501
        :type: str
        """

        self._lang = lang

    @property
    def panel_id(self):
        """Gets the panel_id of this GetCategoryDetailRequest.  # noqa: E501


        :return: The panel_id of this GetCategoryDetailRequest.  # noqa: E501
        :rtype: str
        """
        return self._panel_id

    @panel_id.setter
    def panel_id(self, panel_id):
        """Sets the panel_id of this GetCategoryDetailRequest.


        :param panel_id: The panel_id of this GetCategoryDetailRequest.  # noqa: E501
        :type: str
        """

        self._panel_id = panel_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetCategoryDetailRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetCategoryDetailRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetCategoryDetailRequest):
            return True

        return self.to_dict() != other.to_dict()
