# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class GetVoiceRecommendationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'age_group_filter': 'list[str]',
        'avatar_id': 'str',
        'composition_id': 'str',
        'gender_filter': 'list[str]',
        'language_filter': 'list[str]'
    }

    attribute_map = {
        'age_group_filter': 'AgeGroupFilter',
        'avatar_id': 'AvatarId',
        'composition_id': 'CompositionId',
        'gender_filter': 'GenderFilter',
        'language_filter': 'LanguageFilter'
    }

    def __init__(self, age_group_filter=None, avatar_id=None, composition_id=None, gender_filter=None, language_filter=None, _configuration=None):  # noqa: E501
        """GetVoiceRecommendationRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._age_group_filter = None
        self._avatar_id = None
        self._composition_id = None
        self._gender_filter = None
        self._language_filter = None
        self.discriminator = None

        if age_group_filter is not None:
            self.age_group_filter = age_group_filter
        if avatar_id is not None:
            self.avatar_id = avatar_id
        if composition_id is not None:
            self.composition_id = composition_id
        if gender_filter is not None:
            self.gender_filter = gender_filter
        if language_filter is not None:
            self.language_filter = language_filter

    @property
    def age_group_filter(self):
        """Gets the age_group_filter of this GetVoiceRecommendationRequest.  # noqa: E501


        :return: The age_group_filter of this GetVoiceRecommendationRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._age_group_filter

    @age_group_filter.setter
    def age_group_filter(self, age_group_filter):
        """Sets the age_group_filter of this GetVoiceRecommendationRequest.


        :param age_group_filter: The age_group_filter of this GetVoiceRecommendationRequest.  # noqa: E501
        :type: list[str]
        """

        self._age_group_filter = age_group_filter

    @property
    def avatar_id(self):
        """Gets the avatar_id of this GetVoiceRecommendationRequest.  # noqa: E501


        :return: The avatar_id of this GetVoiceRecommendationRequest.  # noqa: E501
        :rtype: str
        """
        return self._avatar_id

    @avatar_id.setter
    def avatar_id(self, avatar_id):
        """Sets the avatar_id of this GetVoiceRecommendationRequest.


        :param avatar_id: The avatar_id of this GetVoiceRecommendationRequest.  # noqa: E501
        :type: str
        """

        self._avatar_id = avatar_id

    @property
    def composition_id(self):
        """Gets the composition_id of this GetVoiceRecommendationRequest.  # noqa: E501


        :return: The composition_id of this GetVoiceRecommendationRequest.  # noqa: E501
        :rtype: str
        """
        return self._composition_id

    @composition_id.setter
    def composition_id(self, composition_id):
        """Sets the composition_id of this GetVoiceRecommendationRequest.


        :param composition_id: The composition_id of this GetVoiceRecommendationRequest.  # noqa: E501
        :type: str
        """

        self._composition_id = composition_id

    @property
    def gender_filter(self):
        """Gets the gender_filter of this GetVoiceRecommendationRequest.  # noqa: E501


        :return: The gender_filter of this GetVoiceRecommendationRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._gender_filter

    @gender_filter.setter
    def gender_filter(self, gender_filter):
        """Sets the gender_filter of this GetVoiceRecommendationRequest.


        :param gender_filter: The gender_filter of this GetVoiceRecommendationRequest.  # noqa: E501
        :type: list[str]
        """

        self._gender_filter = gender_filter

    @property
    def language_filter(self):
        """Gets the language_filter of this GetVoiceRecommendationRequest.  # noqa: E501


        :return: The language_filter of this GetVoiceRecommendationRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._language_filter

    @language_filter.setter
    def language_filter(self, language_filter):
        """Sets the language_filter of this GetVoiceRecommendationRequest.


        :param language_filter: The language_filter of this GetVoiceRecommendationRequest.  # noqa: E501
        :type: list[str]
        """

        self._language_filter = language_filter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetVoiceRecommendationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetVoiceRecommendationRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetVoiceRecommendationRequest):
            return True

        return self.to_dict() != other.to_dict()
