# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class GetMetaListRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'filter_free': 'int',
        'is_public': 'int',
        'muse_utm_content': 'str',
        'preorder_meta_type': 'int'
    }

    attribute_map = {
        'filter_free': 'FilterFree',
        'is_public': 'IsPublic',
        'muse_utm_content': 'MuseUtmContent',
        'preorder_meta_type': 'PreorderMetaType'
    }

    def __init__(self, filter_free=None, is_public=None, muse_utm_content=None, preorder_meta_type=None, _configuration=None):  # noqa: E501
        """GetMetaListRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._filter_free = None
        self._is_public = None
        self._muse_utm_content = None
        self._preorder_meta_type = None
        self.discriminator = None

        if filter_free is not None:
            self.filter_free = filter_free
        if is_public is not None:
            self.is_public = is_public
        if muse_utm_content is not None:
            self.muse_utm_content = muse_utm_content
        if preorder_meta_type is not None:
            self.preorder_meta_type = preorder_meta_type

    @property
    def filter_free(self):
        """Gets the filter_free of this GetMetaListRequest.  # noqa: E501


        :return: The filter_free of this GetMetaListRequest.  # noqa: E501
        :rtype: int
        """
        return self._filter_free

    @filter_free.setter
    def filter_free(self, filter_free):
        """Sets the filter_free of this GetMetaListRequest.


        :param filter_free: The filter_free of this GetMetaListRequest.  # noqa: E501
        :type: int
        """

        self._filter_free = filter_free

    @property
    def is_public(self):
        """Gets the is_public of this GetMetaListRequest.  # noqa: E501


        :return: The is_public of this GetMetaListRequest.  # noqa: E501
        :rtype: int
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public):
        """Sets the is_public of this GetMetaListRequest.


        :param is_public: The is_public of this GetMetaListRequest.  # noqa: E501
        :type: int
        """

        self._is_public = is_public

    @property
    def muse_utm_content(self):
        """Gets the muse_utm_content of this GetMetaListRequest.  # noqa: E501


        :return: The muse_utm_content of this GetMetaListRequest.  # noqa: E501
        :rtype: str
        """
        return self._muse_utm_content

    @muse_utm_content.setter
    def muse_utm_content(self, muse_utm_content):
        """Sets the muse_utm_content of this GetMetaListRequest.


        :param muse_utm_content: The muse_utm_content of this GetMetaListRequest.  # noqa: E501
        :type: str
        """

        self._muse_utm_content = muse_utm_content

    @property
    def preorder_meta_type(self):
        """Gets the preorder_meta_type of this GetMetaListRequest.  # noqa: E501


        :return: The preorder_meta_type of this GetMetaListRequest.  # noqa: E501
        :rtype: int
        """
        return self._preorder_meta_type

    @preorder_meta_type.setter
    def preorder_meta_type(self, preorder_meta_type):
        """Sets the preorder_meta_type of this GetMetaListRequest.


        :param preorder_meta_type: The preorder_meta_type of this GetMetaListRequest.  # noqa: E501
        :type: int
        """

        self._preorder_meta_type = preorder_meta_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetMetaListRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetMetaListRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetMetaListRequest):
            return True

        return self.to_dict() != other.to_dict()
