# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class GetCompositionResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'composition_param': 'str',
        'content': 'str',
        'create_time': 'int',
        'running_task_ids': 'list[str]',
        'update_export_videos': 'str',
        'update_time': 'int'
    }

    attribute_map = {
        'composition_param': 'CompositionParam',
        'content': 'Content',
        'create_time': 'CreateTime',
        'running_task_ids': 'RunningTaskIds',
        'update_export_videos': 'UpdateExportVideos',
        'update_time': 'UpdateTime'
    }

    def __init__(self, composition_param=None, content=None, create_time=None, running_task_ids=None, update_export_videos=None, update_time=None, _configuration=None):  # noqa: E501
        """GetCompositionResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._composition_param = None
        self._content = None
        self._create_time = None
        self._running_task_ids = None
        self._update_export_videos = None
        self._update_time = None
        self.discriminator = None

        if composition_param is not None:
            self.composition_param = composition_param
        if content is not None:
            self.content = content
        if create_time is not None:
            self.create_time = create_time
        if running_task_ids is not None:
            self.running_task_ids = running_task_ids
        if update_export_videos is not None:
            self.update_export_videos = update_export_videos
        if update_time is not None:
            self.update_time = update_time

    @property
    def composition_param(self):
        """Gets the composition_param of this GetCompositionResponse.  # noqa: E501


        :return: The composition_param of this GetCompositionResponse.  # noqa: E501
        :rtype: str
        """
        return self._composition_param

    @composition_param.setter
    def composition_param(self, composition_param):
        """Sets the composition_param of this GetCompositionResponse.


        :param composition_param: The composition_param of this GetCompositionResponse.  # noqa: E501
        :type: str
        """

        self._composition_param = composition_param

    @property
    def content(self):
        """Gets the content of this GetCompositionResponse.  # noqa: E501


        :return: The content of this GetCompositionResponse.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this GetCompositionResponse.


        :param content: The content of this GetCompositionResponse.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def create_time(self):
        """Gets the create_time of this GetCompositionResponse.  # noqa: E501


        :return: The create_time of this GetCompositionResponse.  # noqa: E501
        :rtype: int
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this GetCompositionResponse.


        :param create_time: The create_time of this GetCompositionResponse.  # noqa: E501
        :type: int
        """

        self._create_time = create_time

    @property
    def running_task_ids(self):
        """Gets the running_task_ids of this GetCompositionResponse.  # noqa: E501


        :return: The running_task_ids of this GetCompositionResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._running_task_ids

    @running_task_ids.setter
    def running_task_ids(self, running_task_ids):
        """Sets the running_task_ids of this GetCompositionResponse.


        :param running_task_ids: The running_task_ids of this GetCompositionResponse.  # noqa: E501
        :type: list[str]
        """

        self._running_task_ids = running_task_ids

    @property
    def update_export_videos(self):
        """Gets the update_export_videos of this GetCompositionResponse.  # noqa: E501


        :return: The update_export_videos of this GetCompositionResponse.  # noqa: E501
        :rtype: str
        """
        return self._update_export_videos

    @update_export_videos.setter
    def update_export_videos(self, update_export_videos):
        """Sets the update_export_videos of this GetCompositionResponse.


        :param update_export_videos: The update_export_videos of this GetCompositionResponse.  # noqa: E501
        :type: str
        """

        self._update_export_videos = update_export_videos

    @property
    def update_time(self):
        """Gets the update_time of this GetCompositionResponse.  # noqa: E501


        :return: The update_time of this GetCompositionResponse.  # noqa: E501
        :rtype: int
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this GetCompositionResponse.


        :param update_time: The update_time of this GetCompositionResponse.  # noqa: E501
        :type: int
        """

        self._update_time = update_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetCompositionResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetCompositionResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetCompositionResponse):
            return True

        return self.to_dict() != other.to_dict()
