# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class GetComboBalanceResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'balance_items': 'list[str]',
        'combo_with_balance_items': 'list[str]'
    }

    attribute_map = {
        'balance_items': 'BalanceItems',
        'combo_with_balance_items': 'ComboWithBalanceItems'
    }

    def __init__(self, balance_items=None, combo_with_balance_items=None, _configuration=None):  # noqa: E501
        """GetComboBalanceResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._balance_items = None
        self._combo_with_balance_items = None
        self.discriminator = None

        if balance_items is not None:
            self.balance_items = balance_items
        if combo_with_balance_items is not None:
            self.combo_with_balance_items = combo_with_balance_items

    @property
    def balance_items(self):
        """Gets the balance_items of this GetComboBalanceResponse.  # noqa: E501


        :return: The balance_items of this GetComboBalanceResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._balance_items

    @balance_items.setter
    def balance_items(self, balance_items):
        """Sets the balance_items of this GetComboBalanceResponse.


        :param balance_items: The balance_items of this GetComboBalanceResponse.  # noqa: E501
        :type: list[str]
        """

        self._balance_items = balance_items

    @property
    def combo_with_balance_items(self):
        """Gets the combo_with_balance_items of this GetComboBalanceResponse.  # noqa: E501


        :return: The combo_with_balance_items of this GetComboBalanceResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._combo_with_balance_items

    @combo_with_balance_items.setter
    def combo_with_balance_items(self, combo_with_balance_items):
        """Sets the combo_with_balance_items of this GetComboBalanceResponse.


        :param combo_with_balance_items: The combo_with_balance_items of this GetComboBalanceResponse.  # noqa: E501
        :type: list[str]
        """

        self._combo_with_balance_items = combo_with_balance_items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetComboBalanceResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetComboBalanceResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetComboBalanceResponse):
            return True

        return self.to_dict() != other.to_dict()
