# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class HandleOAuthCallbackRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'redirect_url': 'str',
        'state': 'str'
    }

    attribute_map = {
        'code': 'Code',
        'redirect_url': 'RedirectUrl',
        'state': 'State'
    }

    def __init__(self, code=None, redirect_url=None, state=None, _configuration=None):  # noqa: E501
        """HandleOAuthCallbackRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._code = None
        self._redirect_url = None
        self._state = None
        self.discriminator = None

        self.code = code
        if redirect_url is not None:
            self.redirect_url = redirect_url
        self.state = state

    @property
    def code(self):
        """Gets the code of this HandleOAuthCallbackRequest.  # noqa: E501


        :return: The code of this HandleOAuthCallbackRequest.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this HandleOAuthCallbackRequest.


        :param code: The code of this HandleOAuthCallbackRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def redirect_url(self):
        """Gets the redirect_url of this HandleOAuthCallbackRequest.  # noqa: E501


        :return: The redirect_url of this HandleOAuthCallbackRequest.  # noqa: E501
        :rtype: str
        """
        return self._redirect_url

    @redirect_url.setter
    def redirect_url(self, redirect_url):
        """Sets the redirect_url of this HandleOAuthCallbackRequest.


        :param redirect_url: The redirect_url of this HandleOAuthCallbackRequest.  # noqa: E501
        :type: str
        """

        self._redirect_url = redirect_url

    @property
    def state(self):
        """Gets the state of this HandleOAuthCallbackRequest.  # noqa: E501


        :return: The state of this HandleOAuthCallbackRequest.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this HandleOAuthCallbackRequest.


        :param state: The state of this HandleOAuthCallbackRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HandleOAuthCallbackRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HandleOAuthCallbackRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HandleOAuthCallbackRequest):
            return True

        return self.to_dict() != other.to_dict()
