# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class ListComboRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel': 'str',
        'combo_type': 'int'
    }

    attribute_map = {
        'channel': 'Channel',
        'combo_type': 'ComboType'
    }

    def __init__(self, channel=None, combo_type=None, _configuration=None):  # noqa: E501
        """ListComboRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._channel = None
        self._combo_type = None
        self.discriminator = None

        if channel is not None:
            self.channel = channel
        if combo_type is not None:
            self.combo_type = combo_type

    @property
    def channel(self):
        """Gets the channel of this ListComboRequest.  # noqa: E501


        :return: The channel of this ListComboRequest.  # noqa: E501
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this ListComboRequest.


        :param channel: The channel of this ListComboRequest.  # noqa: E501
        :type: str
        """

        self._channel = channel

    @property
    def combo_type(self):
        """Gets the combo_type of this ListComboRequest.  # noqa: E501


        :return: The combo_type of this ListComboRequest.  # noqa: E501
        :rtype: int
        """
        return self._combo_type

    @combo_type.setter
    def combo_type(self, combo_type):
        """Sets the combo_type of this ListComboRequest.


        :param combo_type: The combo_type of this ListComboRequest.  # noqa: E501
        :type: int
        """

        self._combo_type = combo_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListComboRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListComboRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListComboRequest):
            return True

        return self.to_dict() != other.to_dict()
