# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class ListCreativePointLogsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'consumer_item_ids': 'list[int]',
        'from_ts': 'int',
        'operator_ids': 'list[str]',
        'page': 'int',
        'page_size': 'int',
        'to_ts': 'int'
    }

    attribute_map = {
        'consumer_item_ids': 'ConsumerItemIds',
        'from_ts': 'FromTs',
        'operator_ids': 'OperatorIds',
        'page': 'Page',
        'page_size': 'PageSize',
        'to_ts': 'ToTs'
    }

    def __init__(self, consumer_item_ids=None, from_ts=None, operator_ids=None, page=None, page_size=None, to_ts=None, _configuration=None):  # noqa: E501
        """ListCreativePointLogsRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._consumer_item_ids = None
        self._from_ts = None
        self._operator_ids = None
        self._page = None
        self._page_size = None
        self._to_ts = None
        self.discriminator = None

        if consumer_item_ids is not None:
            self.consumer_item_ids = consumer_item_ids
        if from_ts is not None:
            self.from_ts = from_ts
        if operator_ids is not None:
            self.operator_ids = operator_ids
        if page is not None:
            self.page = page
        if page_size is not None:
            self.page_size = page_size
        if to_ts is not None:
            self.to_ts = to_ts

    @property
    def consumer_item_ids(self):
        """Gets the consumer_item_ids of this ListCreativePointLogsRequest.  # noqa: E501


        :return: The consumer_item_ids of this ListCreativePointLogsRequest.  # noqa: E501
        :rtype: list[int]
        """
        return self._consumer_item_ids

    @consumer_item_ids.setter
    def consumer_item_ids(self, consumer_item_ids):
        """Sets the consumer_item_ids of this ListCreativePointLogsRequest.


        :param consumer_item_ids: The consumer_item_ids of this ListCreativePointLogsRequest.  # noqa: E501
        :type: list[int]
        """

        self._consumer_item_ids = consumer_item_ids

    @property
    def from_ts(self):
        """Gets the from_ts of this ListCreativePointLogsRequest.  # noqa: E501


        :return: The from_ts of this ListCreativePointLogsRequest.  # noqa: E501
        :rtype: int
        """
        return self._from_ts

    @from_ts.setter
    def from_ts(self, from_ts):
        """Sets the from_ts of this ListCreativePointLogsRequest.


        :param from_ts: The from_ts of this ListCreativePointLogsRequest.  # noqa: E501
        :type: int
        """

        self._from_ts = from_ts

    @property
    def operator_ids(self):
        """Gets the operator_ids of this ListCreativePointLogsRequest.  # noqa: E501


        :return: The operator_ids of this ListCreativePointLogsRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._operator_ids

    @operator_ids.setter
    def operator_ids(self, operator_ids):
        """Sets the operator_ids of this ListCreativePointLogsRequest.


        :param operator_ids: The operator_ids of this ListCreativePointLogsRequest.  # noqa: E501
        :type: list[str]
        """

        self._operator_ids = operator_ids

    @property
    def page(self):
        """Gets the page of this ListCreativePointLogsRequest.  # noqa: E501


        :return: The page of this ListCreativePointLogsRequest.  # noqa: E501
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this ListCreativePointLogsRequest.


        :param page: The page of this ListCreativePointLogsRequest.  # noqa: E501
        :type: int
        """

        self._page = page

    @property
    def page_size(self):
        """Gets the page_size of this ListCreativePointLogsRequest.  # noqa: E501


        :return: The page_size of this ListCreativePointLogsRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this ListCreativePointLogsRequest.


        :param page_size: The page_size of this ListCreativePointLogsRequest.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def to_ts(self):
        """Gets the to_ts of this ListCreativePointLogsRequest.  # noqa: E501


        :return: The to_ts of this ListCreativePointLogsRequest.  # noqa: E501
        :rtype: int
        """
        return self._to_ts

    @to_ts.setter
    def to_ts(self, to_ts):
        """Sets the to_ts of this ListCreativePointLogsRequest.


        :param to_ts: The to_ts of this ListCreativePointLogsRequest.  # noqa: E501
        :type: int
        """

        self._to_ts = to_ts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListCreativePointLogsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListCreativePointLogsRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListCreativePointLogsRequest):
            return True

        return self.to_dict() != other.to_dict()
