# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class ListAvatarRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_buildin': 'bool',
        'page_number': 'int',
        'page_size': 'int',
        'status_filter': 'list[str]'
    }

    attribute_map = {
        'is_buildin': 'IsBuildin',
        'page_number': 'PageNumber',
        'page_size': 'PageSize',
        'status_filter': 'StatusFilter'
    }

    def __init__(self, is_buildin=None, page_number=None, page_size=None, status_filter=None, _configuration=None):  # noqa: E501
        """ListAvatarRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._is_buildin = None
        self._page_number = None
        self._page_size = None
        self._status_filter = None
        self.discriminator = None

        if is_buildin is not None:
            self.is_buildin = is_buildin
        if page_number is not None:
            self.page_number = page_number
        if page_size is not None:
            self.page_size = page_size
        if status_filter is not None:
            self.status_filter = status_filter

    @property
    def is_buildin(self):
        """Gets the is_buildin of this ListAvatarRequest.  # noqa: E501


        :return: The is_buildin of this ListAvatarRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_buildin

    @is_buildin.setter
    def is_buildin(self, is_buildin):
        """Sets the is_buildin of this ListAvatarRequest.


        :param is_buildin: The is_buildin of this ListAvatarRequest.  # noqa: E501
        :type: bool
        """

        self._is_buildin = is_buildin

    @property
    def page_number(self):
        """Gets the page_number of this ListAvatarRequest.  # noqa: E501


        :return: The page_number of this ListAvatarRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number):
        """Sets the page_number of this ListAvatarRequest.


        :param page_number: The page_number of this ListAvatarRequest.  # noqa: E501
        :type: int
        """

        self._page_number = page_number

    @property
    def page_size(self):
        """Gets the page_size of this ListAvatarRequest.  # noqa: E501


        :return: The page_size of this ListAvatarRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this ListAvatarRequest.


        :param page_size: The page_size of this ListAvatarRequest.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def status_filter(self):
        """Gets the status_filter of this ListAvatarRequest.  # noqa: E501


        :return: The status_filter of this ListAvatarRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._status_filter

    @status_filter.setter
    def status_filter(self, status_filter):
        """Sets the status_filter of this ListAvatarRequest.


        :param status_filter: The status_filter of this ListAvatarRequest.  # noqa: E501
        :type: list[str]
        """

        self._status_filter = status_filter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListAvatarRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListAvatarRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListAvatarRequest):
            return True

        return self.to_dict() != other.to_dict()
