# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class ListAvatarVoiceRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'age_group_filter': 'list[str]',
        'gender_filter': 'list[str]',
        'language_filter': 'list[str]',
        'name_filter': 'str',
        'page_number': 'int',
        'page_size': 'int',
        'style_id_filter': 'list[str]'
    }

    attribute_map = {
        'age_group_filter': 'AgeGroupFilter',
        'gender_filter': 'GenderFilter',
        'language_filter': 'LanguageFilter',
        'name_filter': 'NameFilter',
        'page_number': 'PageNumber',
        'page_size': 'PageSize',
        'style_id_filter': 'StyleIdFilter'
    }

    def __init__(self, age_group_filter=None, gender_filter=None, language_filter=None, name_filter=None, page_number=None, page_size=None, style_id_filter=None, _configuration=None):  # noqa: E501
        """ListAvatarVoiceRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._age_group_filter = None
        self._gender_filter = None
        self._language_filter = None
        self._name_filter = None
        self._page_number = None
        self._page_size = None
        self._style_id_filter = None
        self.discriminator = None

        if age_group_filter is not None:
            self.age_group_filter = age_group_filter
        if gender_filter is not None:
            self.gender_filter = gender_filter
        if language_filter is not None:
            self.language_filter = language_filter
        if name_filter is not None:
            self.name_filter = name_filter
        if page_number is not None:
            self.page_number = page_number
        if page_size is not None:
            self.page_size = page_size
        if style_id_filter is not None:
            self.style_id_filter = style_id_filter

    @property
    def age_group_filter(self):
        """Gets the age_group_filter of this ListAvatarVoiceRequest.  # noqa: E501


        :return: The age_group_filter of this ListAvatarVoiceRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._age_group_filter

    @age_group_filter.setter
    def age_group_filter(self, age_group_filter):
        """Sets the age_group_filter of this ListAvatarVoiceRequest.


        :param age_group_filter: The age_group_filter of this ListAvatarVoiceRequest.  # noqa: E501
        :type: list[str]
        """

        self._age_group_filter = age_group_filter

    @property
    def gender_filter(self):
        """Gets the gender_filter of this ListAvatarVoiceRequest.  # noqa: E501


        :return: The gender_filter of this ListAvatarVoiceRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._gender_filter

    @gender_filter.setter
    def gender_filter(self, gender_filter):
        """Sets the gender_filter of this ListAvatarVoiceRequest.


        :param gender_filter: The gender_filter of this ListAvatarVoiceRequest.  # noqa: E501
        :type: list[str]
        """

        self._gender_filter = gender_filter

    @property
    def language_filter(self):
        """Gets the language_filter of this ListAvatarVoiceRequest.  # noqa: E501


        :return: The language_filter of this ListAvatarVoiceRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._language_filter

    @language_filter.setter
    def language_filter(self, language_filter):
        """Sets the language_filter of this ListAvatarVoiceRequest.


        :param language_filter: The language_filter of this ListAvatarVoiceRequest.  # noqa: E501
        :type: list[str]
        """

        self._language_filter = language_filter

    @property
    def name_filter(self):
        """Gets the name_filter of this ListAvatarVoiceRequest.  # noqa: E501


        :return: The name_filter of this ListAvatarVoiceRequest.  # noqa: E501
        :rtype: str
        """
        return self._name_filter

    @name_filter.setter
    def name_filter(self, name_filter):
        """Sets the name_filter of this ListAvatarVoiceRequest.


        :param name_filter: The name_filter of this ListAvatarVoiceRequest.  # noqa: E501
        :type: str
        """

        self._name_filter = name_filter

    @property
    def page_number(self):
        """Gets the page_number of this ListAvatarVoiceRequest.  # noqa: E501


        :return: The page_number of this ListAvatarVoiceRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number):
        """Sets the page_number of this ListAvatarVoiceRequest.


        :param page_number: The page_number of this ListAvatarVoiceRequest.  # noqa: E501
        :type: int
        """

        self._page_number = page_number

    @property
    def page_size(self):
        """Gets the page_size of this ListAvatarVoiceRequest.  # noqa: E501


        :return: The page_size of this ListAvatarVoiceRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this ListAvatarVoiceRequest.


        :param page_size: The page_size of this ListAvatarVoiceRequest.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def style_id_filter(self):
        """Gets the style_id_filter of this ListAvatarVoiceRequest.  # noqa: E501


        :return: The style_id_filter of this ListAvatarVoiceRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._style_id_filter

    @style_id_filter.setter
    def style_id_filter(self, style_id_filter):
        """Sets the style_id_filter of this ListAvatarVoiceRequest.


        :param style_id_filter: The style_id_filter of this ListAvatarVoiceRequest.  # noqa: E501
        :type: list[str]
        """

        self._style_id_filter = style_id_filter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListAvatarVoiceRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListAvatarVoiceRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListAvatarVoiceRequest):
            return True

        return self.to_dict() != other.to_dict()
