# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class SearchListMediaRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auto_del': 'int',
        'exclude_infos': 'list[str]',
        'extra': 'str',
        'fetch_internal_domain': 'bool',
        'field_infos': 'list[str]',
        'folder_id': 'str',
        'folder_type': 'int',
        'full_path': 'str',
        'item_renderer': 'str',
        'material_type': 'str',
        'need_count': 'int',
        'owner': 'str',
        'page': 'int',
        'perpage': 'int',
        'query': 'str',
        'sort_name': 'str',
        'sort_params': 'list[str]',
        'sort_reg': 'int',
        'special_id': 'str',
        'user_data': 'int'
    }

    attribute_map = {
        'auto_del': 'AutoDel',
        'exclude_infos': 'ExcludeInfos',
        'extra': 'Extra',
        'fetch_internal_domain': 'FetchInternalDomain',
        'field_infos': 'FieldInfos',
        'folder_id': 'FolderId',
        'folder_type': 'FolderType',
        'full_path': 'FullPath',
        'item_renderer': 'ItemRenderer',
        'material_type': 'MaterialType',
        'need_count': 'NeedCount',
        'owner': 'Owner',
        'page': 'Page',
        'perpage': 'Perpage',
        'query': 'Query',
        'sort_name': 'SortName',
        'sort_params': 'SortParams',
        'sort_reg': 'SortReg',
        'special_id': 'SpecialId',
        'user_data': 'UserData'
    }

    def __init__(self, auto_del=None, exclude_infos=None, extra=None, fetch_internal_domain=None, field_infos=None, folder_id=None, folder_type=None, full_path=None, item_renderer=None, material_type=None, need_count=None, owner=None, page=None, perpage=None, query=None, sort_name=None, sort_params=None, sort_reg=None, special_id=None, user_data=None, _configuration=None):  # noqa: E501
        """SearchListMediaRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._auto_del = None
        self._exclude_infos = None
        self._extra = None
        self._fetch_internal_domain = None
        self._field_infos = None
        self._folder_id = None
        self._folder_type = None
        self._full_path = None
        self._item_renderer = None
        self._material_type = None
        self._need_count = None
        self._owner = None
        self._page = None
        self._perpage = None
        self._query = None
        self._sort_name = None
        self._sort_params = None
        self._sort_reg = None
        self._special_id = None
        self._user_data = None
        self.discriminator = None

        if auto_del is not None:
            self.auto_del = auto_del
        if exclude_infos is not None:
            self.exclude_infos = exclude_infos
        if extra is not None:
            self.extra = extra
        if fetch_internal_domain is not None:
            self.fetch_internal_domain = fetch_internal_domain
        if field_infos is not None:
            self.field_infos = field_infos
        if folder_id is not None:
            self.folder_id = folder_id
        if folder_type is not None:
            self.folder_type = folder_type
        if full_path is not None:
            self.full_path = full_path
        if item_renderer is not None:
            self.item_renderer = item_renderer
        if material_type is not None:
            self.material_type = material_type
        if need_count is not None:
            self.need_count = need_count
        if owner is not None:
            self.owner = owner
        if page is not None:
            self.page = page
        if perpage is not None:
            self.perpage = perpage
        if query is not None:
            self.query = query
        if sort_name is not None:
            self.sort_name = sort_name
        if sort_params is not None:
            self.sort_params = sort_params
        if sort_reg is not None:
            self.sort_reg = sort_reg
        if special_id is not None:
            self.special_id = special_id
        if user_data is not None:
            self.user_data = user_data

    @property
    def auto_del(self):
        """Gets the auto_del of this SearchListMediaRequest.  # noqa: E501


        :return: The auto_del of this SearchListMediaRequest.  # noqa: E501
        :rtype: int
        """
        return self._auto_del

    @auto_del.setter
    def auto_del(self, auto_del):
        """Sets the auto_del of this SearchListMediaRequest.


        :param auto_del: The auto_del of this SearchListMediaRequest.  # noqa: E501
        :type: int
        """

        self._auto_del = auto_del

    @property
    def exclude_infos(self):
        """Gets the exclude_infos of this SearchListMediaRequest.  # noqa: E501


        :return: The exclude_infos of this SearchListMediaRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._exclude_infos

    @exclude_infos.setter
    def exclude_infos(self, exclude_infos):
        """Sets the exclude_infos of this SearchListMediaRequest.


        :param exclude_infos: The exclude_infos of this SearchListMediaRequest.  # noqa: E501
        :type: list[str]
        """

        self._exclude_infos = exclude_infos

    @property
    def extra(self):
        """Gets the extra of this SearchListMediaRequest.  # noqa: E501


        :return: The extra of this SearchListMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """Sets the extra of this SearchListMediaRequest.


        :param extra: The extra of this SearchListMediaRequest.  # noqa: E501
        :type: str
        """

        self._extra = extra

    @property
    def fetch_internal_domain(self):
        """Gets the fetch_internal_domain of this SearchListMediaRequest.  # noqa: E501


        :return: The fetch_internal_domain of this SearchListMediaRequest.  # noqa: E501
        :rtype: bool
        """
        return self._fetch_internal_domain

    @fetch_internal_domain.setter
    def fetch_internal_domain(self, fetch_internal_domain):
        """Sets the fetch_internal_domain of this SearchListMediaRequest.


        :param fetch_internal_domain: The fetch_internal_domain of this SearchListMediaRequest.  # noqa: E501
        :type: bool
        """

        self._fetch_internal_domain = fetch_internal_domain

    @property
    def field_infos(self):
        """Gets the field_infos of this SearchListMediaRequest.  # noqa: E501


        :return: The field_infos of this SearchListMediaRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._field_infos

    @field_infos.setter
    def field_infos(self, field_infos):
        """Sets the field_infos of this SearchListMediaRequest.


        :param field_infos: The field_infos of this SearchListMediaRequest.  # noqa: E501
        :type: list[str]
        """

        self._field_infos = field_infos

    @property
    def folder_id(self):
        """Gets the folder_id of this SearchListMediaRequest.  # noqa: E501


        :return: The folder_id of this SearchListMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._folder_id

    @folder_id.setter
    def folder_id(self, folder_id):
        """Sets the folder_id of this SearchListMediaRequest.


        :param folder_id: The folder_id of this SearchListMediaRequest.  # noqa: E501
        :type: str
        """

        self._folder_id = folder_id

    @property
    def folder_type(self):
        """Gets the folder_type of this SearchListMediaRequest.  # noqa: E501


        :return: The folder_type of this SearchListMediaRequest.  # noqa: E501
        :rtype: int
        """
        return self._folder_type

    @folder_type.setter
    def folder_type(self, folder_type):
        """Sets the folder_type of this SearchListMediaRequest.


        :param folder_type: The folder_type of this SearchListMediaRequest.  # noqa: E501
        :type: int
        """

        self._folder_type = folder_type

    @property
    def full_path(self):
        """Gets the full_path of this SearchListMediaRequest.  # noqa: E501


        :return: The full_path of this SearchListMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._full_path

    @full_path.setter
    def full_path(self, full_path):
        """Sets the full_path of this SearchListMediaRequest.


        :param full_path: The full_path of this SearchListMediaRequest.  # noqa: E501
        :type: str
        """

        self._full_path = full_path

    @property
    def item_renderer(self):
        """Gets the item_renderer of this SearchListMediaRequest.  # noqa: E501


        :return: The item_renderer of this SearchListMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._item_renderer

    @item_renderer.setter
    def item_renderer(self, item_renderer):
        """Sets the item_renderer of this SearchListMediaRequest.


        :param item_renderer: The item_renderer of this SearchListMediaRequest.  # noqa: E501
        :type: str
        """

        self._item_renderer = item_renderer

    @property
    def material_type(self):
        """Gets the material_type of this SearchListMediaRequest.  # noqa: E501


        :return: The material_type of this SearchListMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._material_type

    @material_type.setter
    def material_type(self, material_type):
        """Sets the material_type of this SearchListMediaRequest.


        :param material_type: The material_type of this SearchListMediaRequest.  # noqa: E501
        :type: str
        """

        self._material_type = material_type

    @property
    def need_count(self):
        """Gets the need_count of this SearchListMediaRequest.  # noqa: E501


        :return: The need_count of this SearchListMediaRequest.  # noqa: E501
        :rtype: int
        """
        return self._need_count

    @need_count.setter
    def need_count(self, need_count):
        """Sets the need_count of this SearchListMediaRequest.


        :param need_count: The need_count of this SearchListMediaRequest.  # noqa: E501
        :type: int
        """

        self._need_count = need_count

    @property
    def owner(self):
        """Gets the owner of this SearchListMediaRequest.  # noqa: E501


        :return: The owner of this SearchListMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this SearchListMediaRequest.


        :param owner: The owner of this SearchListMediaRequest.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def page(self):
        """Gets the page of this SearchListMediaRequest.  # noqa: E501


        :return: The page of this SearchListMediaRequest.  # noqa: E501
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this SearchListMediaRequest.


        :param page: The page of this SearchListMediaRequest.  # noqa: E501
        :type: int
        """

        self._page = page

    @property
    def perpage(self):
        """Gets the perpage of this SearchListMediaRequest.  # noqa: E501


        :return: The perpage of this SearchListMediaRequest.  # noqa: E501
        :rtype: int
        """
        return self._perpage

    @perpage.setter
    def perpage(self, perpage):
        """Sets the perpage of this SearchListMediaRequest.


        :param perpage: The perpage of this SearchListMediaRequest.  # noqa: E501
        :type: int
        """

        self._perpage = perpage

    @property
    def query(self):
        """Gets the query of this SearchListMediaRequest.  # noqa: E501


        :return: The query of this SearchListMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this SearchListMediaRequest.


        :param query: The query of this SearchListMediaRequest.  # noqa: E501
        :type: str
        """

        self._query = query

    @property
    def sort_name(self):
        """Gets the sort_name of this SearchListMediaRequest.  # noqa: E501


        :return: The sort_name of this SearchListMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._sort_name

    @sort_name.setter
    def sort_name(self, sort_name):
        """Sets the sort_name of this SearchListMediaRequest.


        :param sort_name: The sort_name of this SearchListMediaRequest.  # noqa: E501
        :type: str
        """

        self._sort_name = sort_name

    @property
    def sort_params(self):
        """Gets the sort_params of this SearchListMediaRequest.  # noqa: E501


        :return: The sort_params of this SearchListMediaRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._sort_params

    @sort_params.setter
    def sort_params(self, sort_params):
        """Sets the sort_params of this SearchListMediaRequest.


        :param sort_params: The sort_params of this SearchListMediaRequest.  # noqa: E501
        :type: list[str]
        """

        self._sort_params = sort_params

    @property
    def sort_reg(self):
        """Gets the sort_reg of this SearchListMediaRequest.  # noqa: E501


        :return: The sort_reg of this SearchListMediaRequest.  # noqa: E501
        :rtype: int
        """
        return self._sort_reg

    @sort_reg.setter
    def sort_reg(self, sort_reg):
        """Sets the sort_reg of this SearchListMediaRequest.


        :param sort_reg: The sort_reg of this SearchListMediaRequest.  # noqa: E501
        :type: int
        """

        self._sort_reg = sort_reg

    @property
    def special_id(self):
        """Gets the special_id of this SearchListMediaRequest.  # noqa: E501


        :return: The special_id of this SearchListMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._special_id

    @special_id.setter
    def special_id(self, special_id):
        """Sets the special_id of this SearchListMediaRequest.


        :param special_id: The special_id of this SearchListMediaRequest.  # noqa: E501
        :type: str
        """

        self._special_id = special_id

    @property
    def user_data(self):
        """Gets the user_data of this SearchListMediaRequest.  # noqa: E501


        :return: The user_data of this SearchListMediaRequest.  # noqa: E501
        :rtype: int
        """
        return self._user_data

    @user_data.setter
    def user_data(self, user_data):
        """Sets the user_data of this SearchListMediaRequest.


        :param user_data: The user_data of this SearchListMediaRequest.  # noqa: E501
        :type: int
        """

        self._user_data = user_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchListMediaRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchListMediaRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SearchListMediaRequest):
            return True

        return self.to_dict() != other.to_dict()
