# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class SearchAssetRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auto_del': 'int',
        'exclude_infos': 'list[str]',
        'extra': 'str',
        'fetch_internal_domain': 'bool',
        'field_infos': 'list[str]',
        'full_path': 'str',
        'material_type': 'str',
        'need_count': 'int',
        'owner': 'str',
        'page_number': 'int',
        'page_size': 'int',
        'query': 'str',
        'sort_name': 'str',
        'sort_params': 'list[str]',
        'sort_reg': 'int'
    }

    attribute_map = {
        'auto_del': 'AutoDel',
        'exclude_infos': 'ExcludeInfos',
        'extra': 'Extra',
        'fetch_internal_domain': 'FetchInternalDomain',
        'field_infos': 'FieldInfos',
        'full_path': 'FullPath',
        'material_type': 'MaterialType',
        'need_count': 'NeedCount',
        'owner': 'Owner',
        'page_number': 'PageNumber',
        'page_size': 'PageSize',
        'query': 'Query',
        'sort_name': 'SortName',
        'sort_params': 'SortParams',
        'sort_reg': 'SortReg'
    }

    def __init__(self, auto_del=None, exclude_infos=None, extra=None, fetch_internal_domain=None, field_infos=None, full_path=None, material_type=None, need_count=None, owner=None, page_number=None, page_size=None, query=None, sort_name=None, sort_params=None, sort_reg=None, _configuration=None):  # noqa: E501
        """SearchAssetRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._auto_del = None
        self._exclude_infos = None
        self._extra = None
        self._fetch_internal_domain = None
        self._field_infos = None
        self._full_path = None
        self._material_type = None
        self._need_count = None
        self._owner = None
        self._page_number = None
        self._page_size = None
        self._query = None
        self._sort_name = None
        self._sort_params = None
        self._sort_reg = None
        self.discriminator = None

        if auto_del is not None:
            self.auto_del = auto_del
        if exclude_infos is not None:
            self.exclude_infos = exclude_infos
        if extra is not None:
            self.extra = extra
        if fetch_internal_domain is not None:
            self.fetch_internal_domain = fetch_internal_domain
        if field_infos is not None:
            self.field_infos = field_infos
        if full_path is not None:
            self.full_path = full_path
        if material_type is not None:
            self.material_type = material_type
        if need_count is not None:
            self.need_count = need_count
        if owner is not None:
            self.owner = owner
        if page_number is not None:
            self.page_number = page_number
        if page_size is not None:
            self.page_size = page_size
        if query is not None:
            self.query = query
        if sort_name is not None:
            self.sort_name = sort_name
        if sort_params is not None:
            self.sort_params = sort_params
        if sort_reg is not None:
            self.sort_reg = sort_reg

    @property
    def auto_del(self):
        """Gets the auto_del of this SearchAssetRequest.  # noqa: E501


        :return: The auto_del of this SearchAssetRequest.  # noqa: E501
        :rtype: int
        """
        return self._auto_del

    @auto_del.setter
    def auto_del(self, auto_del):
        """Sets the auto_del of this SearchAssetRequest.


        :param auto_del: The auto_del of this SearchAssetRequest.  # noqa: E501
        :type: int
        """

        self._auto_del = auto_del

    @property
    def exclude_infos(self):
        """Gets the exclude_infos of this SearchAssetRequest.  # noqa: E501


        :return: The exclude_infos of this SearchAssetRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._exclude_infos

    @exclude_infos.setter
    def exclude_infos(self, exclude_infos):
        """Sets the exclude_infos of this SearchAssetRequest.


        :param exclude_infos: The exclude_infos of this SearchAssetRequest.  # noqa: E501
        :type: list[str]
        """

        self._exclude_infos = exclude_infos

    @property
    def extra(self):
        """Gets the extra of this SearchAssetRequest.  # noqa: E501


        :return: The extra of this SearchAssetRequest.  # noqa: E501
        :rtype: str
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """Sets the extra of this SearchAssetRequest.


        :param extra: The extra of this SearchAssetRequest.  # noqa: E501
        :type: str
        """

        self._extra = extra

    @property
    def fetch_internal_domain(self):
        """Gets the fetch_internal_domain of this SearchAssetRequest.  # noqa: E501


        :return: The fetch_internal_domain of this SearchAssetRequest.  # noqa: E501
        :rtype: bool
        """
        return self._fetch_internal_domain

    @fetch_internal_domain.setter
    def fetch_internal_domain(self, fetch_internal_domain):
        """Sets the fetch_internal_domain of this SearchAssetRequest.


        :param fetch_internal_domain: The fetch_internal_domain of this SearchAssetRequest.  # noqa: E501
        :type: bool
        """

        self._fetch_internal_domain = fetch_internal_domain

    @property
    def field_infos(self):
        """Gets the field_infos of this SearchAssetRequest.  # noqa: E501


        :return: The field_infos of this SearchAssetRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._field_infos

    @field_infos.setter
    def field_infos(self, field_infos):
        """Sets the field_infos of this SearchAssetRequest.


        :param field_infos: The field_infos of this SearchAssetRequest.  # noqa: E501
        :type: list[str]
        """

        self._field_infos = field_infos

    @property
    def full_path(self):
        """Gets the full_path of this SearchAssetRequest.  # noqa: E501


        :return: The full_path of this SearchAssetRequest.  # noqa: E501
        :rtype: str
        """
        return self._full_path

    @full_path.setter
    def full_path(self, full_path):
        """Sets the full_path of this SearchAssetRequest.


        :param full_path: The full_path of this SearchAssetRequest.  # noqa: E501
        :type: str
        """

        self._full_path = full_path

    @property
    def material_type(self):
        """Gets the material_type of this SearchAssetRequest.  # noqa: E501


        :return: The material_type of this SearchAssetRequest.  # noqa: E501
        :rtype: str
        """
        return self._material_type

    @material_type.setter
    def material_type(self, material_type):
        """Sets the material_type of this SearchAssetRequest.


        :param material_type: The material_type of this SearchAssetRequest.  # noqa: E501
        :type: str
        """

        self._material_type = material_type

    @property
    def need_count(self):
        """Gets the need_count of this SearchAssetRequest.  # noqa: E501


        :return: The need_count of this SearchAssetRequest.  # noqa: E501
        :rtype: int
        """
        return self._need_count

    @need_count.setter
    def need_count(self, need_count):
        """Sets the need_count of this SearchAssetRequest.


        :param need_count: The need_count of this SearchAssetRequest.  # noqa: E501
        :type: int
        """

        self._need_count = need_count

    @property
    def owner(self):
        """Gets the owner of this SearchAssetRequest.  # noqa: E501


        :return: The owner of this SearchAssetRequest.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this SearchAssetRequest.


        :param owner: The owner of this SearchAssetRequest.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def page_number(self):
        """Gets the page_number of this SearchAssetRequest.  # noqa: E501


        :return: The page_number of this SearchAssetRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number):
        """Sets the page_number of this SearchAssetRequest.


        :param page_number: The page_number of this SearchAssetRequest.  # noqa: E501
        :type: int
        """

        self._page_number = page_number

    @property
    def page_size(self):
        """Gets the page_size of this SearchAssetRequest.  # noqa: E501


        :return: The page_size of this SearchAssetRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this SearchAssetRequest.


        :param page_size: The page_size of this SearchAssetRequest.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def query(self):
        """Gets the query of this SearchAssetRequest.  # noqa: E501


        :return: The query of this SearchAssetRequest.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this SearchAssetRequest.


        :param query: The query of this SearchAssetRequest.  # noqa: E501
        :type: str
        """

        self._query = query

    @property
    def sort_name(self):
        """Gets the sort_name of this SearchAssetRequest.  # noqa: E501


        :return: The sort_name of this SearchAssetRequest.  # noqa: E501
        :rtype: str
        """
        return self._sort_name

    @sort_name.setter
    def sort_name(self, sort_name):
        """Sets the sort_name of this SearchAssetRequest.


        :param sort_name: The sort_name of this SearchAssetRequest.  # noqa: E501
        :type: str
        """

        self._sort_name = sort_name

    @property
    def sort_params(self):
        """Gets the sort_params of this SearchAssetRequest.  # noqa: E501


        :return: The sort_params of this SearchAssetRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._sort_params

    @sort_params.setter
    def sort_params(self, sort_params):
        """Sets the sort_params of this SearchAssetRequest.


        :param sort_params: The sort_params of this SearchAssetRequest.  # noqa: E501
        :type: list[str]
        """

        self._sort_params = sort_params

    @property
    def sort_reg(self):
        """Gets the sort_reg of this SearchAssetRequest.  # noqa: E501


        :return: The sort_reg of this SearchAssetRequest.  # noqa: E501
        :rtype: int
        """
        return self._sort_reg

    @sort_reg.setter
    def sort_reg(self, sort_reg):
        """Sets the sort_reg of this SearchAssetRequest.


        :param sort_reg: The sort_reg of this SearchAssetRequest.  # noqa: E501
        :type: int
        """

        self._sort_reg = sort_reg

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchAssetRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchAssetRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SearchAssetRequest):
            return True

        return self.to_dict() != other.to_dict()
