# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class SetWatermarkSwitchStatusRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bright_watermark': 'bool',
        'broadcast_service_provider': 'bool',
        'company': 'str',
        'compose_service_provider': 'bool',
        'dark_watermark': 'bool',
        'social_credit_code': 'str'
    }

    attribute_map = {
        'bright_watermark': 'BrightWatermark',
        'broadcast_service_provider': 'BroadcastServiceProvider',
        'company': 'Company',
        'compose_service_provider': 'ComposeServiceProvider',
        'dark_watermark': 'DarkWatermark',
        'social_credit_code': 'SocialCreditCode'
    }

    def __init__(self, bright_watermark=None, broadcast_service_provider=None, company=None, compose_service_provider=None, dark_watermark=None, social_credit_code=None, _configuration=None):  # noqa: E501
        """SetWatermarkSwitchStatusRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._bright_watermark = None
        self._broadcast_service_provider = None
        self._company = None
        self._compose_service_provider = None
        self._dark_watermark = None
        self._social_credit_code = None
        self.discriminator = None

        if bright_watermark is not None:
            self.bright_watermark = bright_watermark
        if broadcast_service_provider is not None:
            self.broadcast_service_provider = broadcast_service_provider
        if company is not None:
            self.company = company
        if compose_service_provider is not None:
            self.compose_service_provider = compose_service_provider
        if dark_watermark is not None:
            self.dark_watermark = dark_watermark
        if social_credit_code is not None:
            self.social_credit_code = social_credit_code

    @property
    def bright_watermark(self):
        """Gets the bright_watermark of this SetWatermarkSwitchStatusRequest.  # noqa: E501


        :return: The bright_watermark of this SetWatermarkSwitchStatusRequest.  # noqa: E501
        :rtype: bool
        """
        return self._bright_watermark

    @bright_watermark.setter
    def bright_watermark(self, bright_watermark):
        """Sets the bright_watermark of this SetWatermarkSwitchStatusRequest.


        :param bright_watermark: The bright_watermark of this SetWatermarkSwitchStatusRequest.  # noqa: E501
        :type: bool
        """

        self._bright_watermark = bright_watermark

    @property
    def broadcast_service_provider(self):
        """Gets the broadcast_service_provider of this SetWatermarkSwitchStatusRequest.  # noqa: E501


        :return: The broadcast_service_provider of this SetWatermarkSwitchStatusRequest.  # noqa: E501
        :rtype: bool
        """
        return self._broadcast_service_provider

    @broadcast_service_provider.setter
    def broadcast_service_provider(self, broadcast_service_provider):
        """Sets the broadcast_service_provider of this SetWatermarkSwitchStatusRequest.


        :param broadcast_service_provider: The broadcast_service_provider of this SetWatermarkSwitchStatusRequest.  # noqa: E501
        :type: bool
        """

        self._broadcast_service_provider = broadcast_service_provider

    @property
    def company(self):
        """Gets the company of this SetWatermarkSwitchStatusRequest.  # noqa: E501


        :return: The company of this SetWatermarkSwitchStatusRequest.  # noqa: E501
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this SetWatermarkSwitchStatusRequest.


        :param company: The company of this SetWatermarkSwitchStatusRequest.  # noqa: E501
        :type: str
        """

        self._company = company

    @property
    def compose_service_provider(self):
        """Gets the compose_service_provider of this SetWatermarkSwitchStatusRequest.  # noqa: E501


        :return: The compose_service_provider of this SetWatermarkSwitchStatusRequest.  # noqa: E501
        :rtype: bool
        """
        return self._compose_service_provider

    @compose_service_provider.setter
    def compose_service_provider(self, compose_service_provider):
        """Sets the compose_service_provider of this SetWatermarkSwitchStatusRequest.


        :param compose_service_provider: The compose_service_provider of this SetWatermarkSwitchStatusRequest.  # noqa: E501
        :type: bool
        """

        self._compose_service_provider = compose_service_provider

    @property
    def dark_watermark(self):
        """Gets the dark_watermark of this SetWatermarkSwitchStatusRequest.  # noqa: E501


        :return: The dark_watermark of this SetWatermarkSwitchStatusRequest.  # noqa: E501
        :rtype: bool
        """
        return self._dark_watermark

    @dark_watermark.setter
    def dark_watermark(self, dark_watermark):
        """Sets the dark_watermark of this SetWatermarkSwitchStatusRequest.


        :param dark_watermark: The dark_watermark of this SetWatermarkSwitchStatusRequest.  # noqa: E501
        :type: bool
        """

        self._dark_watermark = dark_watermark

    @property
    def social_credit_code(self):
        """Gets the social_credit_code of this SetWatermarkSwitchStatusRequest.  # noqa: E501


        :return: The social_credit_code of this SetWatermarkSwitchStatusRequest.  # noqa: E501
        :rtype: str
        """
        return self._social_credit_code

    @social_credit_code.setter
    def social_credit_code(self, social_credit_code):
        """Sets the social_credit_code of this SetWatermarkSwitchStatusRequest.


        :param social_credit_code: The social_credit_code of this SetWatermarkSwitchStatusRequest.  # noqa: E501
        :type: str
        """

        self._social_credit_code = social_credit_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SetWatermarkSwitchStatusRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SetWatermarkSwitchStatusRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SetWatermarkSwitchStatusRequest):
            return True

        return self.to_dict() != other.to_dict()
