# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class ShowPopupResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'item_list': 'list[str]',
        'open_status': 'str',
        'type_description': 'str'
    }

    attribute_map = {
        'item_list': 'ItemList',
        'open_status': 'OpenStatus',
        'type_description': 'TypeDescription'
    }

    def __init__(self, item_list=None, open_status=None, type_description=None, _configuration=None):  # noqa: E501
        """ShowPopupResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._item_list = None
        self._open_status = None
        self._type_description = None
        self.discriminator = None

        if item_list is not None:
            self.item_list = item_list
        if open_status is not None:
            self.open_status = open_status
        if type_description is not None:
            self.type_description = type_description

    @property
    def item_list(self):
        """Gets the item_list of this ShowPopupResponse.  # noqa: E501


        :return: The item_list of this ShowPopupResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._item_list

    @item_list.setter
    def item_list(self, item_list):
        """Sets the item_list of this ShowPopupResponse.


        :param item_list: The item_list of this ShowPopupResponse.  # noqa: E501
        :type: list[str]
        """

        self._item_list = item_list

    @property
    def open_status(self):
        """Gets the open_status of this ShowPopupResponse.  # noqa: E501


        :return: The open_status of this ShowPopupResponse.  # noqa: E501
        :rtype: str
        """
        return self._open_status

    @open_status.setter
    def open_status(self, open_status):
        """Sets the open_status of this ShowPopupResponse.


        :param open_status: The open_status of this ShowPopupResponse.  # noqa: E501
        :type: str
        """

        self._open_status = open_status

    @property
    def type_description(self):
        """Gets the type_description of this ShowPopupResponse.  # noqa: E501


        :return: The type_description of this ShowPopupResponse.  # noqa: E501
        :rtype: str
        """
        return self._type_description

    @type_description.setter
    def type_description(self, type_description):
        """Sets the type_description of this ShowPopupResponse.


        :param type_description: The type_description of this ShowPopupResponse.  # noqa: E501
        :type: str
        """

        self._type_description = type_description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShowPopupResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShowPopupResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ShowPopupResponse):
            return True

        return self.to_dict() != other.to_dict()
