# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class UpdateFilmRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_extra_info': 'str',
        'copyright_status': 'int',
        'description': 'str',
        'duration': 'int',
        'media_id': 'str',
        'nle_data': 'str',
        'section_data': 'str',
        'source_from': 'str',
        'store_id': 'str',
        'tags': 'list[str]',
        'title': 'str',
        'update_resources': 'list[str]',
        'userdefined_category': 'list[str]'
    }

    attribute_map = {
        'client_extra_info': 'ClientExtraInfo',
        'copyright_status': 'CopyrightStatus',
        'description': 'Description',
        'duration': 'Duration',
        'media_id': 'MediaId',
        'nle_data': 'NleData',
        'section_data': 'SectionData',
        'source_from': 'SourceFrom',
        'store_id': 'StoreId',
        'tags': 'Tags',
        'title': 'Title',
        'update_resources': 'UpdateResources',
        'userdefined_category': 'UserdefinedCategory'
    }

    def __init__(self, client_extra_info=None, copyright_status=None, description=None, duration=None, media_id=None, nle_data=None, section_data=None, source_from=None, store_id=None, tags=None, title=None, update_resources=None, userdefined_category=None, _configuration=None):  # noqa: E501
        """UpdateFilmRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._client_extra_info = None
        self._copyright_status = None
        self._description = None
        self._duration = None
        self._media_id = None
        self._nle_data = None
        self._section_data = None
        self._source_from = None
        self._store_id = None
        self._tags = None
        self._title = None
        self._update_resources = None
        self._userdefined_category = None
        self.discriminator = None

        if client_extra_info is not None:
            self.client_extra_info = client_extra_info
        if copyright_status is not None:
            self.copyright_status = copyright_status
        if description is not None:
            self.description = description
        if duration is not None:
            self.duration = duration
        if media_id is not None:
            self.media_id = media_id
        if nle_data is not None:
            self.nle_data = nle_data
        if section_data is not None:
            self.section_data = section_data
        if source_from is not None:
            self.source_from = source_from
        if store_id is not None:
            self.store_id = store_id
        if tags is not None:
            self.tags = tags
        if title is not None:
            self.title = title
        if update_resources is not None:
            self.update_resources = update_resources
        if userdefined_category is not None:
            self.userdefined_category = userdefined_category

    @property
    def client_extra_info(self):
        """Gets the client_extra_info of this UpdateFilmRequest.  # noqa: E501


        :return: The client_extra_info of this UpdateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_extra_info

    @client_extra_info.setter
    def client_extra_info(self, client_extra_info):
        """Sets the client_extra_info of this UpdateFilmRequest.


        :param client_extra_info: The client_extra_info of this UpdateFilmRequest.  # noqa: E501
        :type: str
        """

        self._client_extra_info = client_extra_info

    @property
    def copyright_status(self):
        """Gets the copyright_status of this UpdateFilmRequest.  # noqa: E501


        :return: The copyright_status of this UpdateFilmRequest.  # noqa: E501
        :rtype: int
        """
        return self._copyright_status

    @copyright_status.setter
    def copyright_status(self, copyright_status):
        """Sets the copyright_status of this UpdateFilmRequest.


        :param copyright_status: The copyright_status of this UpdateFilmRequest.  # noqa: E501
        :type: int
        """

        self._copyright_status = copyright_status

    @property
    def description(self):
        """Gets the description of this UpdateFilmRequest.  # noqa: E501


        :return: The description of this UpdateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UpdateFilmRequest.


        :param description: The description of this UpdateFilmRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def duration(self):
        """Gets the duration of this UpdateFilmRequest.  # noqa: E501


        :return: The duration of this UpdateFilmRequest.  # noqa: E501
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this UpdateFilmRequest.


        :param duration: The duration of this UpdateFilmRequest.  # noqa: E501
        :type: int
        """

        self._duration = duration

    @property
    def media_id(self):
        """Gets the media_id of this UpdateFilmRequest.  # noqa: E501


        :return: The media_id of this UpdateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._media_id

    @media_id.setter
    def media_id(self, media_id):
        """Sets the media_id of this UpdateFilmRequest.


        :param media_id: The media_id of this UpdateFilmRequest.  # noqa: E501
        :type: str
        """

        self._media_id = media_id

    @property
    def nle_data(self):
        """Gets the nle_data of this UpdateFilmRequest.  # noqa: E501


        :return: The nle_data of this UpdateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._nle_data

    @nle_data.setter
    def nle_data(self, nle_data):
        """Sets the nle_data of this UpdateFilmRequest.


        :param nle_data: The nle_data of this UpdateFilmRequest.  # noqa: E501
        :type: str
        """

        self._nle_data = nle_data

    @property
    def section_data(self):
        """Gets the section_data of this UpdateFilmRequest.  # noqa: E501


        :return: The section_data of this UpdateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._section_data

    @section_data.setter
    def section_data(self, section_data):
        """Sets the section_data of this UpdateFilmRequest.


        :param section_data: The section_data of this UpdateFilmRequest.  # noqa: E501
        :type: str
        """

        self._section_data = section_data

    @property
    def source_from(self):
        """Gets the source_from of this UpdateFilmRequest.  # noqa: E501


        :return: The source_from of this UpdateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._source_from

    @source_from.setter
    def source_from(self, source_from):
        """Sets the source_from of this UpdateFilmRequest.


        :param source_from: The source_from of this UpdateFilmRequest.  # noqa: E501
        :type: str
        """

        self._source_from = source_from

    @property
    def store_id(self):
        """Gets the store_id of this UpdateFilmRequest.  # noqa: E501


        :return: The store_id of this UpdateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._store_id

    @store_id.setter
    def store_id(self, store_id):
        """Sets the store_id of this UpdateFilmRequest.


        :param store_id: The store_id of this UpdateFilmRequest.  # noqa: E501
        :type: str
        """

        self._store_id = store_id

    @property
    def tags(self):
        """Gets the tags of this UpdateFilmRequest.  # noqa: E501


        :return: The tags of this UpdateFilmRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this UpdateFilmRequest.


        :param tags: The tags of this UpdateFilmRequest.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def title(self):
        """Gets the title of this UpdateFilmRequest.  # noqa: E501


        :return: The title of this UpdateFilmRequest.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this UpdateFilmRequest.


        :param title: The title of this UpdateFilmRequest.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def update_resources(self):
        """Gets the update_resources of this UpdateFilmRequest.  # noqa: E501


        :return: The update_resources of this UpdateFilmRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._update_resources

    @update_resources.setter
    def update_resources(self, update_resources):
        """Sets the update_resources of this UpdateFilmRequest.


        :param update_resources: The update_resources of this UpdateFilmRequest.  # noqa: E501
        :type: list[str]
        """

        self._update_resources = update_resources

    @property
    def userdefined_category(self):
        """Gets the userdefined_category of this UpdateFilmRequest.  # noqa: E501


        :return: The userdefined_category of this UpdateFilmRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._userdefined_category

    @userdefined_category.setter
    def userdefined_category(self, userdefined_category):
        """Sets the userdefined_category of this UpdateFilmRequest.


        :param userdefined_category: The userdefined_category of this UpdateFilmRequest.  # noqa: E501
        :type: list[str]
        """

        self._userdefined_category = userdefined_category

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateFilmRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateFilmRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateFilmRequest):
            return True

        return self.to_dict() != other.to_dict()
