# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class UpdateDraftRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'composition_id': 'str',
        'cover_id': 'str',
        'cover_url': 'str',
        'media_id': 'str',
        'nle_data': 'str'
    }

    attribute_map = {
        'composition_id': 'CompositionId',
        'cover_id': 'CoverId',
        'cover_url': 'CoverUrl',
        'media_id': 'MediaId',
        'nle_data': 'NleData'
    }

    def __init__(self, composition_id=None, cover_id=None, cover_url=None, media_id=None, nle_data=None, _configuration=None):  # noqa: E501
        """UpdateDraftRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._composition_id = None
        self._cover_id = None
        self._cover_url = None
        self._media_id = None
        self._nle_data = None
        self.discriminator = None

        if composition_id is not None:
            self.composition_id = composition_id
        if cover_id is not None:
            self.cover_id = cover_id
        if cover_url is not None:
            self.cover_url = cover_url
        if media_id is not None:
            self.media_id = media_id
        if nle_data is not None:
            self.nle_data = nle_data

    @property
    def composition_id(self):
        """Gets the composition_id of this UpdateDraftRequest.  # noqa: E501


        :return: The composition_id of this UpdateDraftRequest.  # noqa: E501
        :rtype: str
        """
        return self._composition_id

    @composition_id.setter
    def composition_id(self, composition_id):
        """Sets the composition_id of this UpdateDraftRequest.


        :param composition_id: The composition_id of this UpdateDraftRequest.  # noqa: E501
        :type: str
        """

        self._composition_id = composition_id

    @property
    def cover_id(self):
        """Gets the cover_id of this UpdateDraftRequest.  # noqa: E501


        :return: The cover_id of this UpdateDraftRequest.  # noqa: E501
        :rtype: str
        """
        return self._cover_id

    @cover_id.setter
    def cover_id(self, cover_id):
        """Sets the cover_id of this UpdateDraftRequest.


        :param cover_id: The cover_id of this UpdateDraftRequest.  # noqa: E501
        :type: str
        """

        self._cover_id = cover_id

    @property
    def cover_url(self):
        """Gets the cover_url of this UpdateDraftRequest.  # noqa: E501


        :return: The cover_url of this UpdateDraftRequest.  # noqa: E501
        :rtype: str
        """
        return self._cover_url

    @cover_url.setter
    def cover_url(self, cover_url):
        """Sets the cover_url of this UpdateDraftRequest.


        :param cover_url: The cover_url of this UpdateDraftRequest.  # noqa: E501
        :type: str
        """

        self._cover_url = cover_url

    @property
    def media_id(self):
        """Gets the media_id of this UpdateDraftRequest.  # noqa: E501


        :return: The media_id of this UpdateDraftRequest.  # noqa: E501
        :rtype: str
        """
        return self._media_id

    @media_id.setter
    def media_id(self, media_id):
        """Sets the media_id of this UpdateDraftRequest.


        :param media_id: The media_id of this UpdateDraftRequest.  # noqa: E501
        :type: str
        """

        self._media_id = media_id

    @property
    def nle_data(self):
        """Gets the nle_data of this UpdateDraftRequest.  # noqa: E501


        :return: The nle_data of this UpdateDraftRequest.  # noqa: E501
        :rtype: str
        """
        return self._nle_data

    @nle_data.setter
    def nle_data(self, nle_data):
        """Sets the nle_data of this UpdateDraftRequest.


        :param nle_data: The nle_data of this UpdateDraftRequest.  # noqa: E501
        :type: str
        """

        self._nle_data = nle_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateDraftRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateDraftRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateDraftRequest):
            return True

        return self.to_dict() != other.to_dict()
