# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class UpdateCompositionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'patches': 'str'
    }

    attribute_map = {
        'id': 'Id',
        'patches': 'Patches'
    }

    def __init__(self, id=None, patches=None, _configuration=None):  # noqa: E501
        """UpdateCompositionRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._patches = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if patches is not None:
            self.patches = patches

    @property
    def id(self):
        """Gets the id of this UpdateCompositionRequest.  # noqa: E501


        :return: The id of this UpdateCompositionRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UpdateCompositionRequest.


        :param id: The id of this UpdateCompositionRequest.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def patches(self):
        """Gets the patches of this UpdateCompositionRequest.  # noqa: E501


        :return: The patches of this UpdateCompositionRequest.  # noqa: E501
        :rtype: str
        """
        return self._patches

    @patches.setter
    def patches(self, patches):
        """Sets the patches of this UpdateCompositionRequest.


        :param patches: The patches of this UpdateCompositionRequest.  # noqa: E501
        :type: str
        """

        self._patches = patches

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateCompositionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateCompositionRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateCompositionRequest):
            return True

        return self.to_dict() != other.to_dict()
