# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class UpdateMaterialRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aspect_ratio': 'str',
        'client_extra_info': 'str',
        'copyright': 'str',
        'description': 'str',
        'extra': 'str',
        'media_first_category': 'str',
        'media_id': 'str',
        'params_definition': 'str',
        'related_media_list': 'list[str]',
        'script_json': 'str',
        'tags': 'list[str]',
        'team_visibility': 'bool',
        'template_slot_guide_video': 'str',
        'title': 'str',
        'update_resources': 'list[str]',
        'userdefined_category': 'list[str]'
    }

    attribute_map = {
        'aspect_ratio': 'AspectRatio',
        'client_extra_info': 'ClientExtraInfo',
        'copyright': 'Copyright',
        'description': 'Description',
        'extra': 'Extra',
        'media_first_category': 'MediaFirstCategory',
        'media_id': 'MediaId',
        'params_definition': 'ParamsDefinition',
        'related_media_list': 'RelatedMediaList',
        'script_json': 'ScriptJson',
        'tags': 'Tags',
        'team_visibility': 'TeamVisibility',
        'template_slot_guide_video': 'TemplateSlotGuideVideo',
        'title': 'Title',
        'update_resources': 'UpdateResources',
        'userdefined_category': 'UserdefinedCategory'
    }

    def __init__(self, aspect_ratio=None, client_extra_info=None, copyright=None, description=None, extra=None, media_first_category=None, media_id=None, params_definition=None, related_media_list=None, script_json=None, tags=None, team_visibility=None, template_slot_guide_video=None, title=None, update_resources=None, userdefined_category=None, _configuration=None):  # noqa: E501
        """UpdateMaterialRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._aspect_ratio = None
        self._client_extra_info = None
        self._copyright = None
        self._description = None
        self._extra = None
        self._media_first_category = None
        self._media_id = None
        self._params_definition = None
        self._related_media_list = None
        self._script_json = None
        self._tags = None
        self._team_visibility = None
        self._template_slot_guide_video = None
        self._title = None
        self._update_resources = None
        self._userdefined_category = None
        self.discriminator = None

        if aspect_ratio is not None:
            self.aspect_ratio = aspect_ratio
        if client_extra_info is not None:
            self.client_extra_info = client_extra_info
        if copyright is not None:
            self.copyright = copyright
        if description is not None:
            self.description = description
        if extra is not None:
            self.extra = extra
        if media_first_category is not None:
            self.media_first_category = media_first_category
        if media_id is not None:
            self.media_id = media_id
        if params_definition is not None:
            self.params_definition = params_definition
        if related_media_list is not None:
            self.related_media_list = related_media_list
        if script_json is not None:
            self.script_json = script_json
        if tags is not None:
            self.tags = tags
        if team_visibility is not None:
            self.team_visibility = team_visibility
        if template_slot_guide_video is not None:
            self.template_slot_guide_video = template_slot_guide_video
        if title is not None:
            self.title = title
        if update_resources is not None:
            self.update_resources = update_resources
        if userdefined_category is not None:
            self.userdefined_category = userdefined_category

    @property
    def aspect_ratio(self):
        """Gets the aspect_ratio of this UpdateMaterialRequest.  # noqa: E501


        :return: The aspect_ratio of this UpdateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._aspect_ratio

    @aspect_ratio.setter
    def aspect_ratio(self, aspect_ratio):
        """Sets the aspect_ratio of this UpdateMaterialRequest.


        :param aspect_ratio: The aspect_ratio of this UpdateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._aspect_ratio = aspect_ratio

    @property
    def client_extra_info(self):
        """Gets the client_extra_info of this UpdateMaterialRequest.  # noqa: E501


        :return: The client_extra_info of this UpdateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_extra_info

    @client_extra_info.setter
    def client_extra_info(self, client_extra_info):
        """Sets the client_extra_info of this UpdateMaterialRequest.


        :param client_extra_info: The client_extra_info of this UpdateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._client_extra_info = client_extra_info

    @property
    def copyright(self):
        """Gets the copyright of this UpdateMaterialRequest.  # noqa: E501


        :return: The copyright of this UpdateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._copyright

    @copyright.setter
    def copyright(self, copyright):
        """Sets the copyright of this UpdateMaterialRequest.


        :param copyright: The copyright of this UpdateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._copyright = copyright

    @property
    def description(self):
        """Gets the description of this UpdateMaterialRequest.  # noqa: E501


        :return: The description of this UpdateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UpdateMaterialRequest.


        :param description: The description of this UpdateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def extra(self):
        """Gets the extra of this UpdateMaterialRequest.  # noqa: E501


        :return: The extra of this UpdateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """Sets the extra of this UpdateMaterialRequest.


        :param extra: The extra of this UpdateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._extra = extra

    @property
    def media_first_category(self):
        """Gets the media_first_category of this UpdateMaterialRequest.  # noqa: E501


        :return: The media_first_category of this UpdateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._media_first_category

    @media_first_category.setter
    def media_first_category(self, media_first_category):
        """Sets the media_first_category of this UpdateMaterialRequest.


        :param media_first_category: The media_first_category of this UpdateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._media_first_category = media_first_category

    @property
    def media_id(self):
        """Gets the media_id of this UpdateMaterialRequest.  # noqa: E501


        :return: The media_id of this UpdateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._media_id

    @media_id.setter
    def media_id(self, media_id):
        """Sets the media_id of this UpdateMaterialRequest.


        :param media_id: The media_id of this UpdateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._media_id = media_id

    @property
    def params_definition(self):
        """Gets the params_definition of this UpdateMaterialRequest.  # noqa: E501


        :return: The params_definition of this UpdateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._params_definition

    @params_definition.setter
    def params_definition(self, params_definition):
        """Sets the params_definition of this UpdateMaterialRequest.


        :param params_definition: The params_definition of this UpdateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._params_definition = params_definition

    @property
    def related_media_list(self):
        """Gets the related_media_list of this UpdateMaterialRequest.  # noqa: E501


        :return: The related_media_list of this UpdateMaterialRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._related_media_list

    @related_media_list.setter
    def related_media_list(self, related_media_list):
        """Sets the related_media_list of this UpdateMaterialRequest.


        :param related_media_list: The related_media_list of this UpdateMaterialRequest.  # noqa: E501
        :type: list[str]
        """

        self._related_media_list = related_media_list

    @property
    def script_json(self):
        """Gets the script_json of this UpdateMaterialRequest.  # noqa: E501


        :return: The script_json of this UpdateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._script_json

    @script_json.setter
    def script_json(self, script_json):
        """Sets the script_json of this UpdateMaterialRequest.


        :param script_json: The script_json of this UpdateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._script_json = script_json

    @property
    def tags(self):
        """Gets the tags of this UpdateMaterialRequest.  # noqa: E501


        :return: The tags of this UpdateMaterialRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this UpdateMaterialRequest.


        :param tags: The tags of this UpdateMaterialRequest.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def team_visibility(self):
        """Gets the team_visibility of this UpdateMaterialRequest.  # noqa: E501


        :return: The team_visibility of this UpdateMaterialRequest.  # noqa: E501
        :rtype: bool
        """
        return self._team_visibility

    @team_visibility.setter
    def team_visibility(self, team_visibility):
        """Sets the team_visibility of this UpdateMaterialRequest.


        :param team_visibility: The team_visibility of this UpdateMaterialRequest.  # noqa: E501
        :type: bool
        """

        self._team_visibility = team_visibility

    @property
    def template_slot_guide_video(self):
        """Gets the template_slot_guide_video of this UpdateMaterialRequest.  # noqa: E501


        :return: The template_slot_guide_video of this UpdateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._template_slot_guide_video

    @template_slot_guide_video.setter
    def template_slot_guide_video(self, template_slot_guide_video):
        """Sets the template_slot_guide_video of this UpdateMaterialRequest.


        :param template_slot_guide_video: The template_slot_guide_video of this UpdateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._template_slot_guide_video = template_slot_guide_video

    @property
    def title(self):
        """Gets the title of this UpdateMaterialRequest.  # noqa: E501


        :return: The title of this UpdateMaterialRequest.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this UpdateMaterialRequest.


        :param title: The title of this UpdateMaterialRequest.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def update_resources(self):
        """Gets the update_resources of this UpdateMaterialRequest.  # noqa: E501


        :return: The update_resources of this UpdateMaterialRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._update_resources

    @update_resources.setter
    def update_resources(self, update_resources):
        """Sets the update_resources of this UpdateMaterialRequest.


        :param update_resources: The update_resources of this UpdateMaterialRequest.  # noqa: E501
        :type: list[str]
        """

        self._update_resources = update_resources

    @property
    def userdefined_category(self):
        """Gets the userdefined_category of this UpdateMaterialRequest.  # noqa: E501


        :return: The userdefined_category of this UpdateMaterialRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._userdefined_category

    @userdefined_category.setter
    def userdefined_category(self, userdefined_category):
        """Sets the userdefined_category of this UpdateMaterialRequest.


        :param userdefined_category: The userdefined_category of this UpdateMaterialRequest.  # noqa: E501
        :type: list[str]
        """

        self._userdefined_category = userdefined_category

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateMaterialRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateMaterialRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateMaterialRequest):
            return True

        return self.to_dict() != other.to_dict()
