# coding: utf-8

"""
    kickart

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class ValidateAvatarImageResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error_code': 'int',
        'is_valid': 'bool'
    }

    attribute_map = {
        'error_code': 'ErrorCode',
        'is_valid': 'IsValid'
    }

    def __init__(self, error_code=None, is_valid=None, _configuration=None):  # noqa: E501
        """ValidateAvatarImageResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._error_code = None
        self._is_valid = None
        self.discriminator = None

        if error_code is not None:
            self.error_code = error_code
        if is_valid is not None:
            self.is_valid = is_valid

    @property
    def error_code(self):
        """Gets the error_code of this ValidateAvatarImageResponse.  # noqa: E501


        :return: The error_code of this ValidateAvatarImageResponse.  # noqa: E501
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this ValidateAvatarImageResponse.


        :param error_code: The error_code of this ValidateAvatarImageResponse.  # noqa: E501
        :type: int
        """

        self._error_code = error_code

    @property
    def is_valid(self):
        """Gets the is_valid of this ValidateAvatarImageResponse.  # noqa: E501


        :return: The is_valid of this ValidateAvatarImageResponse.  # noqa: E501
        :rtype: bool
        """
        return self._is_valid

    @is_valid.setter
    def is_valid(self, is_valid):
        """Sets the is_valid of this ValidateAvatarImageResponse.


        :param is_valid: The is_valid of this ValidateAvatarImageResponse.  # noqa: E501
        :type: bool
        """

        self._is_valid = is_valid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ValidateAvatarImageResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ValidateAvatarImageResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ValidateAvatarImageResponse):
            return True

        return self.to_dict() != other.to_dict()
