# coding: utf-8

"""
    ecs20251101

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from byteplussdkcore.configuration import Configuration


class RunInstancesRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_token': 'str',
        'count': 'int',
        'eip_address': 'EipAddressForRunInstancesInput',
        'image_id': 'str',
        'instance_charge_type': 'str',
        'instance_name': 'str',
        'instance_type_id': 'str',
        'min_count': 'int',
        'network_interfaces': 'list[NetworkInterfaceForRunInstancesInput]',
        'project_name': 'str',
        'public_key': 'str',
        'tags': 'list[TagForRunInstancesInput]',
        'user_data': 'str',
        'volumes': 'list[VolumeForRunInstancesInput]',
        'zone_id': 'str'
    }

    attribute_map = {
        'client_token': 'ClientToken',
        'count': 'Count',
        'eip_address': 'EipAddress',
        'image_id': 'ImageId',
        'instance_charge_type': 'InstanceChargeType',
        'instance_name': 'InstanceName',
        'instance_type_id': 'InstanceTypeId',
        'min_count': 'MinCount',
        'network_interfaces': 'NetworkInterfaces',
        'project_name': 'ProjectName',
        'public_key': 'PublicKey',
        'tags': 'Tags',
        'user_data': 'UserData',
        'volumes': 'Volumes',
        'zone_id': 'ZoneId'
    }

    def __init__(self, client_token=None, count=None, eip_address=None, image_id=None, instance_charge_type=None, instance_name=None, instance_type_id=None, min_count=None, network_interfaces=None, project_name=None, public_key=None, tags=None, user_data=None, volumes=None, zone_id=None, _configuration=None):  # noqa: E501
        """RunInstancesRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._client_token = None
        self._count = None
        self._eip_address = None
        self._image_id = None
        self._instance_charge_type = None
        self._instance_name = None
        self._instance_type_id = None
        self._min_count = None
        self._network_interfaces = None
        self._project_name = None
        self._public_key = None
        self._tags = None
        self._user_data = None
        self._volumes = None
        self._zone_id = None
        self.discriminator = None

        if client_token is not None:
            self.client_token = client_token
        if count is not None:
            self.count = count
        if eip_address is not None:
            self.eip_address = eip_address
        self.image_id = image_id
        if instance_charge_type is not None:
            self.instance_charge_type = instance_charge_type
        self.instance_name = instance_name
        self.instance_type_id = instance_type_id
        if min_count is not None:
            self.min_count = min_count
        if network_interfaces is not None:
            self.network_interfaces = network_interfaces
        if project_name is not None:
            self.project_name = project_name
        self.public_key = public_key
        if tags is not None:
            self.tags = tags
        if user_data is not None:
            self.user_data = user_data
        if volumes is not None:
            self.volumes = volumes
        self.zone_id = zone_id

    @property
    def client_token(self):
        """Gets the client_token of this RunInstancesRequest.  # noqa: E501


        :return: The client_token of this RunInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_token

    @client_token.setter
    def client_token(self, client_token):
        """Sets the client_token of this RunInstancesRequest.


        :param client_token: The client_token of this RunInstancesRequest.  # noqa: E501
        :type: str
        """

        self._client_token = client_token

    @property
    def count(self):
        """Gets the count of this RunInstancesRequest.  # noqa: E501


        :return: The count of this RunInstancesRequest.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this RunInstancesRequest.


        :param count: The count of this RunInstancesRequest.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def eip_address(self):
        """Gets the eip_address of this RunInstancesRequest.  # noqa: E501


        :return: The eip_address of this RunInstancesRequest.  # noqa: E501
        :rtype: EipAddressForRunInstancesInput
        """
        return self._eip_address

    @eip_address.setter
    def eip_address(self, eip_address):
        """Sets the eip_address of this RunInstancesRequest.


        :param eip_address: The eip_address of this RunInstancesRequest.  # noqa: E501
        :type: EipAddressForRunInstancesInput
        """

        self._eip_address = eip_address

    @property
    def image_id(self):
        """Gets the image_id of this RunInstancesRequest.  # noqa: E501


        :return: The image_id of this RunInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._image_id

    @image_id.setter
    def image_id(self, image_id):
        """Sets the image_id of this RunInstancesRequest.


        :param image_id: The image_id of this RunInstancesRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and image_id is None:
            raise ValueError("Invalid value for `image_id`, must not be `None`")  # noqa: E501

        self._image_id = image_id

    @property
    def instance_charge_type(self):
        """Gets the instance_charge_type of this RunInstancesRequest.  # noqa: E501


        :return: The instance_charge_type of this RunInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._instance_charge_type

    @instance_charge_type.setter
    def instance_charge_type(self, instance_charge_type):
        """Sets the instance_charge_type of this RunInstancesRequest.


        :param instance_charge_type: The instance_charge_type of this RunInstancesRequest.  # noqa: E501
        :type: str
        """

        self._instance_charge_type = instance_charge_type

    @property
    def instance_name(self):
        """Gets the instance_name of this RunInstancesRequest.  # noqa: E501


        :return: The instance_name of this RunInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._instance_name

    @instance_name.setter
    def instance_name(self, instance_name):
        """Sets the instance_name of this RunInstancesRequest.


        :param instance_name: The instance_name of this RunInstancesRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and instance_name is None:
            raise ValueError("Invalid value for `instance_name`, must not be `None`")  # noqa: E501

        self._instance_name = instance_name

    @property
    def instance_type_id(self):
        """Gets the instance_type_id of this RunInstancesRequest.  # noqa: E501


        :return: The instance_type_id of this RunInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._instance_type_id

    @instance_type_id.setter
    def instance_type_id(self, instance_type_id):
        """Sets the instance_type_id of this RunInstancesRequest.


        :param instance_type_id: The instance_type_id of this RunInstancesRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and instance_type_id is None:
            raise ValueError("Invalid value for `instance_type_id`, must not be `None`")  # noqa: E501

        self._instance_type_id = instance_type_id

    @property
    def min_count(self):
        """Gets the min_count of this RunInstancesRequest.  # noqa: E501


        :return: The min_count of this RunInstancesRequest.  # noqa: E501
        :rtype: int
        """
        return self._min_count

    @min_count.setter
    def min_count(self, min_count):
        """Sets the min_count of this RunInstancesRequest.


        :param min_count: The min_count of this RunInstancesRequest.  # noqa: E501
        :type: int
        """

        self._min_count = min_count

    @property
    def network_interfaces(self):
        """Gets the network_interfaces of this RunInstancesRequest.  # noqa: E501


        :return: The network_interfaces of this RunInstancesRequest.  # noqa: E501
        :rtype: list[NetworkInterfaceForRunInstancesInput]
        """
        return self._network_interfaces

    @network_interfaces.setter
    def network_interfaces(self, network_interfaces):
        """Sets the network_interfaces of this RunInstancesRequest.


        :param network_interfaces: The network_interfaces of this RunInstancesRequest.  # noqa: E501
        :type: list[NetworkInterfaceForRunInstancesInput]
        """

        self._network_interfaces = network_interfaces

    @property
    def project_name(self):
        """Gets the project_name of this RunInstancesRequest.  # noqa: E501


        :return: The project_name of this RunInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this RunInstancesRequest.


        :param project_name: The project_name of this RunInstancesRequest.  # noqa: E501
        :type: str
        """

        self._project_name = project_name

    @property
    def public_key(self):
        """Gets the public_key of this RunInstancesRequest.  # noqa: E501


        :return: The public_key of this RunInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._public_key

    @public_key.setter
    def public_key(self, public_key):
        """Sets the public_key of this RunInstancesRequest.


        :param public_key: The public_key of this RunInstancesRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and public_key is None:
            raise ValueError("Invalid value for `public_key`, must not be `None`")  # noqa: E501

        self._public_key = public_key

    @property
    def tags(self):
        """Gets the tags of this RunInstancesRequest.  # noqa: E501


        :return: The tags of this RunInstancesRequest.  # noqa: E501
        :rtype: list[TagForRunInstancesInput]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this RunInstancesRequest.


        :param tags: The tags of this RunInstancesRequest.  # noqa: E501
        :type: list[TagForRunInstancesInput]
        """

        self._tags = tags

    @property
    def user_data(self):
        """Gets the user_data of this RunInstancesRequest.  # noqa: E501


        :return: The user_data of this RunInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._user_data

    @user_data.setter
    def user_data(self, user_data):
        """Sets the user_data of this RunInstancesRequest.


        :param user_data: The user_data of this RunInstancesRequest.  # noqa: E501
        :type: str
        """

        self._user_data = user_data

    @property
    def volumes(self):
        """Gets the volumes of this RunInstancesRequest.  # noqa: E501


        :return: The volumes of this RunInstancesRequest.  # noqa: E501
        :rtype: list[VolumeForRunInstancesInput]
        """
        return self._volumes

    @volumes.setter
    def volumes(self, volumes):
        """Sets the volumes of this RunInstancesRequest.


        :param volumes: The volumes of this RunInstancesRequest.  # noqa: E501
        :type: list[VolumeForRunInstancesInput]
        """

        self._volumes = volumes

    @property
    def zone_id(self):
        """Gets the zone_id of this RunInstancesRequest.  # noqa: E501


        :return: The zone_id of this RunInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._zone_id

    @zone_id.setter
    def zone_id(self, zone_id):
        """Sets the zone_id of this RunInstancesRequest.


        :param zone_id: The zone_id of this RunInstancesRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and zone_id is None:
            raise ValueError("Invalid value for `zone_id`, must not be `None`")  # noqa: E501

        self._zone_id = zone_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RunInstancesRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunInstancesRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RunInstancesRequest):
            return True

        return self.to_dict() != other.to_dict()
